xournalpp/xournalpp

src/gui/XournalView.cpp

I have added space and shift-space to help with navigation of journals. The behaviour is the same as in many other apps (evince, Chrome, Firefox): space scrolls one screen down, shift-space in the opposite direction

Added support to space and shift-space to scroll the document

---

src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/widgets/XournalWidget.cpp

Use root coordinates as handtool reference instead of relative coordinates to avoid jittering. (see GNOME/evince@1adce54). Should fix issue #162.
Second commit is the (non-centered) pinch-to-zoom functionality. Issue #160

Fix for hand tool jitter; pinch-to-zoom

---

src/control/ZoomControl.cpp
src/control/ZoomControl.h
src/gui/Layout.cpp
src/gui/Layout.h
src/gui/MainWindow.cpp
src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/toolbarMenubar/ToolZoomSlider.cpp

-turned off kinetic scrolling; 
-hardcoded the min/max zoom levels via "#define" to have them consistent in zoomcontrol and the slider
-Shift-Mousewheel works via scrollRelativ while the gesture uses absolute adjustments
- performance should be improved in a future commit
See issue #161.

Centered zooming for pinch-to-zoom gesture and Shift-Mousewheel;

---

configure.ac

Use "pkg-config python2" to find PYTHON_{CFLAGS,LIBS} unless $PYTHON is
set.  This makes simplifies the configure command line invocation and enables
cross compiling. All major Linux distros ship their python-{dev,devel} package
with a pkg-config file. The systems that don't can fallback to setting $PYTHON.

configure.ac: fix python support when the $PYTHON envvar isn't set

---

ui/main.glade

just a simple edit to main.glade
selecting latex objects can be pretty bothersome, unless using the Select Object tool.

add keyboard accellerator for Select Object (ctrl-shift-o)

---

src/gui/XournalView.cpp

Having event compression enabled extra unprocessed motion events in the event
queue can be discarded. Only the most recent event will be delivered.
This may result in edgy strokes.
This is solved by disabling event compression.
Reference: #109

Disable motion event compression

---

src/gui/MainWindow.cpp

Kinetic scrolling seems to work perfectly, and makes navigating on a touchscreen much easier.

enable kinetic scrolling

---

src/control/ScrollHandler.cpp
src/gui/Layout.cpp
src/gui/XournalView.cpp
src/gui/XournalView.h

This fixes #91 and also completes presentation mode, at least for me. Happy to take notes or adjust implementation, especially considering the "Things that aren't done" section in the commit message.
I remove any "padding" between or around pages, except for the padding
between dual-page layouts (I don't know how people want to use dual-page
and presentation at the same time, is padding desirable?). Then just
force the zoom to be the appropriate value when in presentation mode,
and skip to next/previous pages as buttons are pressed.
Things that aren't done:
- Toolbars aren't hiding. I don't actually want this, since I want to
be able to draw on presentations. Maybe as an option it could be done.
- Scrollbar is visible. Honestly, I couldn't yet work out how to hide
it. It should be easy, I …

Fix up presentation mode

---

src/control/ToolHandler.cpp

Fixes #194 which is caused by some hardware sending multiple touch
events. This ensures that a stored tool is not over-written by a
repeated touch event.
An alternative implementation idea is to maintain a stack of stored
tools, but that seems unnecessary.

Only store a tool if one hasn't been stored.

---

CMakeLists.txt

Building poppler inside the source dir means a subsequent call to make will fail, such as calling make install. This is important if I want to build debian packages that's possibly suitable for upstream inclusion.
This also pins the poppler version to a constant version so the build is more "repeatable". I used the standard `CMAKE_ARGS` argument for `ExternalProject` so we don't rely on manually calling cmake for poppler.
Fixes #241.

Don't build poppler inside the source dir

---

src/gui/SearchBar.cpp

Emptying the search field of the find function caused the program to crash (because NULL was passed as parameter, and not a valid string)
Fixes #257

Fixed bug in find function causing crash

---

src/control/settings/Settings.cpp
src/util/StringUtils.cpp

Resolves issue #168 and uses pull request #223.
Platform: using Arch Linux, Linux 4.14.27, GTK3 3.22.28-1. Latest pull to the master branch, cherry-picked these fixes to my own repo.
I have tried combining both fixes (Hoeze's `UTF-8` fix from issue #168 and the official pull request to the development branch https://github.com/xournalpp/xournalpp/pull/223) and they seem to work well! Just to be sure, I've deleted the existing settings.xml file to avoid other issues. I also tried it with my existing `ISO-8859-1` encoded file, and it seems to work just fine with the new commits, maybe because the string is being read properly.
I've tried a few different settings (e.g. Xinput, sidebar on the right hand side, and zoom ruler DPI setting) and tested it in the master branch with mathtex flag in …

Fix preferences not saving to settings.xml file, both within the application and when restarting it

---

src/gui/XournalView.cpp
src/gui/XournalView.h

Enabling full screen first resizes the layout, and then the
display/pages, which breaks presentation mode. Rather than chase this
loop directly, this fix catches the resize event on the widget holding
the pages, and calls layoutPages again, which makes presentation mode
work in full screen, and when resizing the window directly.
It currently uses a static proxy function for the gtk signal handler, I
couldn't get std::bind to work and gtk doesn't support member function
callbacks (obviously, they're C bindings). The std::bind handler
probably could be made to work, or other alternatives.
This fixes issue #260 but I am definitely happy to take feedback into consideration, especially since the proxy static function feels like a hack.

Fix fullscreen/resize in presentation mode.

---

src/model/Layer.cpp

xournalpp segfaults upon item restore from deletion.
How to replicate the issue:
1) draw something on the page
2) delete it with CTRL+X or `canc`
3) CTRL+Z
I'm not entirely sure why do we have to sum `pos` to the element list.
Anyway the program segfaults upon element restoration due to negative array index.
I've inserted the -1 check and everything seem to work alright.

[BUGFIX] - CTRL-Z deletion recovery segfault

---

README.md

Also added a warning for libopenjpeg which is not available
on newer Ubuntus
This works adding a backslash at the end of every line, so that the shell will read it as a single line.

Make apt command in README cut-n-paste compatible.

---

src/pdf/popplerdirect/PdfObjectWriter.cpp
src/pdf/popplerdirect/poppler/XojPopplerAction.cpp
src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp
src/pdf/popplerdirect/poppler/XojPopplerIter.cpp

Doesn't build in Ubuntu 18.10 (Cosmic Cuttlefish) with errors like:
```make
error: invalid conversion from ‘const GooString*’ to ‘GooString*’ [-fpermissive]
```
So I temporarily fix it with `const_cast<GooString *>()` so that it builds. Tested it and it works for my use case (import PDF, write something using pencil, export PDF).

Quick hacks to make it build in Ubuntu 18.10

---

src/control/stockdlg/XojOpenDlg.cpp
src/util/XojPreviewExtractor.cpp
src/util/XojPreviewExtractor.h
src/xoj-preview-extractor/xournal-thumbnailer.cpp
test/util/XojPreviewExtractorTest.cpp

There was a std::string used a binary container, gives errors, probably
signed / unsigned stuff. Fixed with unsinged char array, preview is
working now.

Fixed Preview Image

---

CMakeLists.txt

When running "make DEST=<path> install" only the path set previously with CMAKE_INSTALL_PREFIX ist used.

DEST parameter ignored in make install

---

CMakeLists.txt

Install the poppler libs with native cmake functions without the need of an uninstall workaround (tested) and detect poppler libs to enable -DPOPPLER_GIT_VER without manual adjustments (tested with v0.69.0, v0.61.1).

Properly install workaround libs

---

src/gui/dialog/SelectBackgroundColorDialog.cpp

Small change as seen on https://stackoverflow.com/questions/29743745/c-member-array-initalisation-without-default-constructors fixes small build error on clang (mac os)

fixed build error on clang ( now using C++11 standard )

---

src/control/LatexController.cpp
src/control/LatexController.h
src/gui/dialog/LatexDialog.cpp
src/gui/dialog/LatexDialog.h
ui/texdialog.glade

Hi!
I was so interested in your project that I wanted to help a little bit!
I liked the LaTex functionality a lot but I tought that a real time display of what a user was 'LaTexting' could have been really handy, so I added it!
Basically I modified only the LaTex Dialog/Controller sources in order to intercept a 'text changed' signal from the Dialog and re-render a new LaTex image while deleting the old one.
I needed to add a white background to the render displayer inside the dialog because for those who use a dark themed DE (as I do), reading the black-fonted Tex would have been really hard.
I tried to follow your code formatting rules and your 'developing pattern' as much as I could, I hope you'll like this feature!

Added real-time LaTex rendering in LatexDialog

---

CMakeLists.txt

necessary changes (remove colon and whitespaces) in the package version so rpmbuild accept to build rpm

addaption to build rpm removed colons

---

CMakeLists.txt
cmake/include/Version.cmake
cmake/postinst.in

The second commit is only a proposal to change the version number to a valid one, as installing deb packages with the previous version is not possible. The version style is adopted from kodi (former xbmc), but of couse I can remove that part again.
By the way, their code could speedup implementing ppa support as their license match the xournalpp license.

Improve CPack package generation and version number

---

.gitignore
CMakeLists.txt
src/control/LatexController.cpp

Hi!
I found out the problem which caused an error when LaTex dialog was lauched: basically I previously put `insertTexImage(true)` in the `LatexController->showTexEditDialog()` but when that method is executed, there isn't the tex.png image yet, so I removed it because the first effective tex.png file is created right when the Dialog appears, because a "changed" signal is launched at its creation!
I also added `.vscode` to the gitignore and raised the `POPPLER_MAX_VERSION` to 0.69 since it works!

Fixed Error when launching LatexDialog when tex.png is missing

---

src/control/LatexController.cpp

I noticed that pressing cancel in the LatexDialog caused an empty png to be added to the doc, adding the check not only to the empty string but also in the trimmed one solved the problem!

Fixed LaTex addition even if text is empty, adding to doc empty png

---

src/control/tools/EditSelection.cpp

Upon compiling the most recent `master` branch, I found that the compilation found due to a missing header.
The call to `atan` in line 465 of the function `EditSelection::mouseMove()` caused the crash as the `math` header for `atan` was missing.

Add missing math header.

---

src/control/AudioController.cpp
src/control/AudioController.h
src/control/Control.cpp
src/control/Control.h
src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
ui/settings.glade

* Prevent crash by showing an error to the user if the Audio recording folder is not being set when "Record" is hit.
* Improve file name convention for audio recordings to be supported on platforms other than Linux
* Fix audio recording description under settings

Audio folder check set

---

src/gui/Cursor.cpp

Hi! 
As the title says, i changed the icon of the cursor when in Big Cursor mode in order to make it look like a pencil.
I still have that problem in Text Box as in #470 , but even checking for imContext or event for NULL values didn't solve the issue. My debugger found a Segmentation Error in the 
`gtk_im_context_filter_keypress(this->imContext, event)` condition.

Added Pen icon when in BigCursor mode

---

po/cs.po
po/de.po
po/pl.po
po/zh.po
po/zh_HK.po
po/zh_TW.po
src/gui/dialog/LatexDialog.cpp
src/gui/dialog/LatexDialog.h

Hi!
I managed to downscale the LaTex preview when long strings are inserted.
I still need to change the Dialog entry from a simple one-line entry to a small TextView (is this the right way?), but for now let me know if the scaling works a little better!
(I didn't change .po files, I don't know why they're different)

Fixed LaTex scaling for long text

---

src/control/Control.cpp
src/control/jobs/BaseExportJob.cpp
src/control/settings/Settings.cpp
src/model/Document.cpp
src/model/Document.h

Generalizes the autonaming to the document. Supposed to fix: #463 .

Fix export autonames

---

CMakeLists.txt

Since the standard cairo pdf export, we don't need for MacOs target to compile POPPLER by default

disabling POPPLER compile if not specified otherwise

---

src/gui/Cursor.cpp
src/gui/dialog/ExportDialog.cpp

Nothing fancy
* Edited the Pen Icon's drawing method in order to change the layout of the Highlighter in BigCursor mode
* Fixed a return statement in an Export as dialog which caused the impossibility to cancel the operation by exiting the dialog
Fixes #514

Added icon for highlighter and fixed method in Export dialog

---

src/control/XournalMain.cpp
src/gui/Cursor.cpp

Hi! I added a check on the env variable GTK_IM_MODULE which, if set to "xim", caused the Text tool to crash
Fixes #470

 Added Input method check (xim unsupported) 

---

utility/usr/local/bin/xopp-recording.sh

Future plans are to:
- do not relay on `arecord` anymore (not multiplatform)
- get rid completely of `xopp-recording.sh` script (for the same reason)
- use vlc backend for cross-platform audio recording

added vlc recording backend

---

src/model/Stroke.cpp
src/model/Stroke.h

Hi! 
I think this could be a fix to #713 , but since I don't have a teblet to try this on yet, I'd like to ask you if this could be a solution and if not, which are the consequences.
If you could test this "fix" that would be perfect, even if I think this could mess up other things which don't involve Shape Recognition

DO NOT MERGE - Stroke recognizer width

---

po/cs.po
po/de.po
po/it.po
po/pl.po
po/xournalpp.pot
po/zh.po
po/zh_HK.po
po/zh_TW.po
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/Cursor.cpp
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Hi! I added the feature requested in #786 .
Now under Preferences -> View you can enable the highlighting option.
Right now I made it available only when in "Big Cursor" mode, but if you think that it should be available without that mode too, no problem, we only need to move one if outside a block ;)
Fixes #786

Highlight cursor position - added

---

src/gui/dialog/ButtonConfigGui.cpp
src/gui/dialog/ButtonConfigGui.h
src/gui/dialog/SettingsDialog.cpp
src/util/DeviceListHelper.cpp
src/util/DeviceListHelper.h

Do not allow to configure GTK Touch Screen - there is a separated tab
for this, and this causes crashes on some devices

Fixed #764

---

src/control/XournalMain.cpp

Fix for issue #859 
Do not crash if system default locale cannot be set but log a warning.

Do not crash when system default locale could not be found

---

org.github.xournalpp.xournalpp.yaml

This a flatpak manifest i came up with. It is working for me, but as this is the very first app i wrote a flatpak  manifest for, this might be totally buggy. I'm also new to Xournalpp so i might not even notice if something is not working what should work. 
In #857 i posted a json manifest which i converted to yaml as it supports comments properly. I also dumped the sox dependecie and added libsndfile instead. 
To create a flatpak file the following to commands are needed.  ./flatpak-build and ./repo are arbitrary
folder names.
```
flatpak-builder ./flatpak-build org.github.xournalpp.xournalpp.yaml --force-clean --repo=./repo 
flatpak build-bundle ./repo  xournalpp.flatpak com.github.xournalpp.xournalpp
```

Flatpak: Initial manifest proposal

---

src/control/Control.cpp
src/gui/Cursor.cpp
src/gui/Cursor.h

Hi! 
This should  fix #856 
I thought one thing tho, right now we re-draw the cursor every time the cursor goes off and on the paper, even if it's not a really big issue, I think we could speed up things a little more by creating the cursor's image file in the .xournalpp folder only once, and then we could just load them when needed.
I'm saying this because we would only need 6 small pngs, 3 for the eraser's size, and 3 for the pen (big cursor, highlight position, both of them combined)
What do you think?

Eraser's cursor's size now matches the actual eraser size

---

README.md

The installation process on openSUSE has changed somewhat since the merging of xournalpp into official repositories. Updated the README.md file to reflect current guidelines

Update installation guidelines for openSUSE.

---

src/.vscode/c_cpp_properties.json
src/gui/Cursor.cpp
src/gui/XournalView.cpp

Hi!
This should fix #894 
I think I'm going to implement the stuff we we're saying about "saving a pre-rendered icon" for some tools and use it when needed instead of re-draw them every time. At least I'd like to see if this could be less "resources extensive", not that it is right now but... why not?

Update eraser's cursor's size on zoom change

---

src/gui/dialog/PluginDialogEntry.cpp
src/plugin/PluginController.cpp

Fix the build if Lua is not present. Refers to #926. It works for me, but I don't know how Xournal++ should look with plugins.

fix build without Plugins

---

ui/settings.glade

Simple fix to get rid of extra mangled tooltip.

Remove duplicate tooltip

---

src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/control/tools/EditSelectionContents.cpp
src/control/tools/EditSelectionContents.h
src/gui/pageposition/PagePositionHandler.cpp
src/gui/pageposition/PagePositionHandler.h

This is in regard to the movement of selected objects between pages after selection.
This functionality was broken in the multilayout code changes.
This is a slightly different implementation to consider:
It uses the page found under the cursor ( instead of the one with the biggest overlap );
It doesn't delete the item if finalized off-page but instead resets to original page and position.

Edit selection movement between and going off page

---

src/gui/Layout.cpp

This enables Add Horizontal and Add Vertical preference settings to work after multiLayout changes.

Add Horizontal/Vertical

---

src/control/Control.cpp
src/control/Control.h
src/control/zoom/ZoomControl.cpp
src/control/zoom/ZoomControl.h
src/control/zoom/ZoomGesture.cpp
src/enums/ActionGroup.enum.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/toolbarMenubar/ToolMenuHandler.cpp
src/gui/toolbarMenubar/ToolZoomSlider.cpp

I fixed various problems with the zoom fit mode.
- Calculation of zoomFitValue after zooming in and out
- Make the zoom fit Button indicate, zoomFitMode is active
- recalculate and zoom, when Window is resized
- recalculate and zoom, when loading new file
At some places, I'm not sure wether its the way to do this. And I kind of fear calling calcZoomFitSize bit too often.
I would request others to test the behavior, before merging. For me everything works well now.

fix various problems with zoom-fit-mode

---

src/control/tools/StrokeHandler.cpp
src/view/StrokeView.cpp

Currently, highlighting text with the highlighter tool covers it with transparent strokes, so it looks like this (on the right side, I highlighted several times to emphasize the point):
This pull request changes the compositing operator for the highlighter tool to MULTIPLY, so that instead the text stays dark:
I think I changed it everywhere that is appropriate, but those more familiar with the source should probably check.

keep text dark when highlighting

---

src/gui/LayoutMapper.cpp

A minor fix I came across working on another issue which required an accurate recalc of the rows when paired pages forced the addition of an extra column.

recalculate rows when paired pages forces an extra column.

---

src/control/Control.cpp

I've done a bit of testing and I'm fairly confident this fixes #1016 and #998.
#998 has comments about doing things the way GIMP does to use the GTK warning dialog which we may want to consider. See my comments there.  In the meantime I think this fix will be sufficient.

Fix double warnings

---

src/gui/LayoutMapper.cpp
src/gui/LayoutMapper.h

Code review mentioned mapper init/configure functions.
Renamed and better ordered them for readability.

minor touchup to mapper functions for readability

---

src/gui/Cursor.cpp

Crash in KDE when Big Cursor or Highlight Cursor option is enabled in settings.
Ref: Issue #842 & #1001

Fixed BigCursor  Crash on KDE

---

po/cs.po
po/de.po
po/it.po
po/pl.po
po/xournalpp.pot
po/zh.po
po/zh_HK.po
po/zh_TW.po
ui/main.glade

Minor bug: Under the Tools menu, the "Draw Arrow" is duplicated (the bottom one does "Draw Coordinate System")
I built the latest version from the `xournalpp-git` AUR package.
Screenshot of bug:
This time, I was able to find the source of the issue! :) The PR contains the fix. I tested it by building from source. Tested on Arch Linux, built manually with this tutorial: https://github.com/xournalpp/xournalpp/blob/master/readme/LinuxBuild.md
I also edited the translation files to make sure that it was consistently recognizing it across all languages (some of them had "" in msgstr, would that mean it would replace with nothing, or would it replace it with the default string? I'm not very familiar with potfiles. I kept the name lowercase to make it consistent with other places where we have …

Fix the Draw Arrow/Draw Coordinate System issue/inconsistency in the Tools menu

---

src/gui/Layout.cpp
src/gui/Layout.h
src/gui/inputdevices/InputSequence.cpp
src/gui/inputdevices/InputSequence.h

The hand tool was scrolling with int but the scrolling works with doubles. The result was that you couldn't move the page up nor to the left slowly using the grab tool.

fixes 1042: Mouse grab: Can't move page up slowly

---

src/gui/Layout.cpp
src/gui/Layout.h
src/gui/MainWindow.cpp
src/gui/PageView.cpp
src/gui/PageView.h
src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/toolbarMenubar/ToolZoomSlider.cpp

This PR adds page navigation with respect to the position of the pages as laid out.
Explores  keymappings as below:
Arrow Keys:  
no modifier - as before, scrolls view
shifted arrow and
numeric keypad arrow keys - - selects page found in given direction.
Note: removes ability for zoom control to have focus so that keys don't mysteriously stop working after you adjust zoom with the mouse.

Layout relative page navigation

---

src/gui/inputdevices/InputSequence.cpp

Re-implement the 0 movement event filter. It can be effective for different hardware or GTK versions.
Of note is the state of flux of the GTK event filtering methods and events generated by different input hardware.

Re-implement Hand movement filter

---

src/model/eraser/EraseableStroke.cpp

Fixes #1043.
This is my first ever pull request, so please let me know if I'm doing anything wrong.

Preserve line style when erasing partial strokes

---

ui/settings.glade

Settings.glade could't be loaded into Glade 3.18 any more.
Glade 3.18 complained about missing id's for objects.
For reference, the missing id's were added with this gawk command.
If we need to run it again the generated id's will need a new prefix ( not "sid");
gawk '/.*object class="[[:alnum:]]*">/ {sub(/<object class="[[:alnum:]]*"/, "& " sprintf("id=\"sid%02d\"",++c))} 1' ui/settings.glade

Fix to allow editing with glade 3.18

---

src/control/tools/EditSelection.cpp

Minor fix - discovered issue when compiling on latest MX Linux.
abs(num)    ->     std:abs(num)

Fix errors on build on GCC 6.3.0: error: call of overloaded ‘abs(double)’ is ambiguous

---

.gitignore
build-flatpack.sh
com.github.xournalpp.xournalpp.yaml

This should fix bugs with building the Flatpak, in a addition to updating the build manifest to build the latest release (1.0.10)

Update Flatpak build

---

src/control/RecentManager.cpp

fixes #1071 - Check for null result from gtk_recent_info_get_uri()

fixes #1071   - Check for null result from gtk_recent_info_get_uri()

---

src/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp

Changed the custom widget base for SidebarPreviewBaseEntry from gtk_drawing_area to gtk_button.
Respond to clicked event now (instead of button_press_event which was interfering with touch scrolling).

fixes #1072 - can now touch-scroll sidebar

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/tools/BaseStrokeHandler.cpp
src/control/tools/BaseStrokeHandler.h
src/control/tools/InputHandler.h
src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h
src/gui/PageView.cpp
src/gui/dialog/SettingsDialog.cpp
src/gui/inputdevices/InputSequence.cpp
src/gui/inputdevices/InputSequence.h
src/gui/inputdevices/NewGtkInputDevice.cpp
src/gui/inputdevices/PositionInputData.h
ui/settings.glade

Adds experimental feature to ignore short scratches which in turn allow the user to select items without changing from the drawing tool.

Tap select

---

src/gui/TextEditor.cpp
src/gui/TextEditor.h

Since text pasting is asynchronous according to https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-paste-clipboard, the repaint calls are
triggered before the text is actually pasted. This commit attaches the repaint
calls to the `paste-done` signal that is fired by the text buffer once the
pasting completes.
This fixes #1103.

Fix TextEditor not updating correctly after text is pasted

---

readme/LinuxBuild.md

I added a list of packages needed for compilation on Solus Linux to the `LinuxBuild.md` readme.

Add build instructions for Solus Linux

---

src/gui/TextEditor.cpp

This fixes the issue (#1026) with the text editor copying to the PRIMARY selection instead of the CLIPBOARD selection.

Fix issue #1026

---

src/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp

Fixes #1110. Please check if other input methods (touch) work with this fix before merging.

Fix regression in SidebarPreviewBaseEntry (#1110)

---

src/control/Control.cpp
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/stockdlg/XojOpenDlg.cpp

Fixes #1108 and fixes #1056. In particular:
* Adds a new setting that stores the last opened file.
* Fixes `lastSaveFile` and `lastImageFile` being incorrectly saved in the settings.
* The file open dialog now displays the folder of the last opened file by default.
* When opening a file, the folder of the last saved file is added as a shortcut on the left sidebar. When saving, the folder of the last opened file is added.

Improve file dialog history handling

---

src/control/LatexController.cpp
src/control/LatexController.h
src/gui/dialog/LatexDialog.cpp
src/gui/dialog/LatexDialog.h
src/util/Path.cpp
src/util/Path.h
src/util/Util.cpp
src/util/Util.h
test/util/PathTest.cpp
ui/texdialog.glade

Improve/fix Latex tool usability

---

src/control/LatexController.cpp
src/gui/dialog/LatexDialog.cpp
src/gui/dialog/LatexDialog.h

With this change, users won't have to delete the default x^2 LaTeX
formula before adding their own. The x^2 is selected so upon typing it
will vanish.
Fixes: #1140

Preselect default text in LaTeX input dialog

---

src/control/Control.cpp
src/control/jobs/AutosaveJob.cpp

Fixes #1142. In particular:
* Changes how autosaves of new unsaved documents are renamed. Before, they were renamed from `~/.xournalpp/autosave/<pid>.autosave.xopp` to `~/.xournalpp/autosave/<pid><pid>.xopp`. Now, they are renamed to `~/.xournalpp/autosave/<pid>.old.autosave.xopp`.
* Adds additional diagnostic information messages (on stdout) about autosaving
Feedback is welcome, but this PR is immediately ready for merge (the fix has been confirmed to work and doesn't seem to break any behavior).

Fix autosave file name for new unsaved documents

---

src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/gui/inputdevices/MouseInputHandler.cpp
src/gui/inputdevices/PenInputHandler.cpp
src/gui/inputdevices/PenInputHandler.h
src/gui/inputdevices/StylusInputHandler.cpp

Implements #1137 for the new input system only.

Allow double clicks on selected objects to begin editing

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/tools/BaseStrokeHandler.cpp
src/control/tools/BaseStrokeHandler.h
src/control/tools/InputHandler.h
src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h
src/gui/PageView.cpp
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

In preparation for use with a popup/floatingToolbox. Changed tapSelect/scratch filtering to use screen length and distance from buttondown to buttonup independent of stroke points.  Settings and variable name changes to better reflect new implementation.

Tap select/filtering improvements

---

src/gui/PageView.cpp
src/gui/PageView.h
src/gui/TextEditor.cpp
src/gui/TextEditor.h
src/gui/TextEditorWidget.h
src/gui/inputdevices/MouseInputHandler.cpp
src/gui/inputdevices/PenInputHandler.cpp
src/gui/inputdevices/StylusInputHandler.cpp

Makes multiple clicks on during text editors select words and lines. This will implement and close #841. In particular:

Multiple clicks in text editor

---

src/control/XournalMain.cpp

Had to amend my commit 3 times, since you use tabs. But it should be alright now.
This PR implements support for relocatable installations, such as AppImages. Paths such as in `/usr` should never be hardcoded to `/`, not even if you respect the install prefix (you seem to do, the header responsible for that data is auto-generated). Instead, it's much better to detect paths relative to the currently running binary directory. Since this is `.../usr/bin` and the data is installed into `.../usr/share/xournalpp`, it's quite simple to deduce the relative path from the executable dir. Your code already provides that directory as a variable, so it was quite simple to fix this.
More information: https://docs.appimage.org/reference/best-practices.html#binaries-must-not-use-compiled-in-absolute-paths …

Fix support for relocatable installations

---

src/control/Control.cpp
src/util/Path.cpp
test/util/PathTest.cpp

Fixes https://github.com/xournalpp/xournalpp/issues/962
as well as it fixes an issue where the AutoloadPdfXoj feature would only look for *.pdf.xopp which however couldn't exist.
If it is preferred not to keep the .pdf part of the filename only line 2351 of Control.cpp should be changed, as this will fix the autoload issue.
This might be a good behavior once the background is saved in the file itself.

Allow "*.pdf.xopp" as a filename

---

src/control/LatexController.cpp
src/control/LatexController.h
src/gui/dialog/LatexDialog.cpp
src/gui/dialog/LatexDialog.h

This PR refactors the LaTeX tool code to be simpler, purely for maintenance purposes.
- Removed redundant variables
- Made data flow of the latex string explicit
- Marked the "invalid latex" message for localization
- Renamed some variables/methods for clarity
- Minor code cleanup
- Added documentation
Let me know if there are any regressions. If not, I will be merging this in three days.

Simplify and refactor latex tool code

---

src/gui/inputdevices/MouseInputHandler.cpp
src/gui/inputdevices/PenInputHandler.cpp
src/gui/inputdevices/StylusInputHandler.cpp

Previously, #1164 fixed the cursor becoming invisible after editing a text field, but it seems to only work when the cursor is pressed and moved. This PR makes the cursor visibile when the cursor moves in general, not just when the mouse/stylus is pressed.

Make cursor visible on general movement after typing in text field

---

po/de.po
src/gui/Redrawable.h
src/gui/toolbarMenubar/icon/ColorSelectImage.cpp
src/gui/toolbarMenubar/icon/ColorSelectImage.h
src/model/Stroke.cpp
src/view/DocumentView.cpp
src/view/StrokeView.cpp
src/view/StrokeView.h

Spelling fix
po.de.po   <- should I be checking this in  - updated by cmake and constantly getting in the way of other checkins. Did someone forget to check it in?

spelling fix, po/de.po

---

CMakeLists.txt

This should silence warnings related to deprecations in newer versions but keep any warnings relevant to the minimum versions around.

Set glib and gdk minimum version macros in CMakeLists.txt

---

src/gui/PageView.cpp

Needed to save and restore cairo drawing context around scale+search->paint in Pageview:paintPageSync().

fixes #1217 - Corrupted drawing after Search - missing cairo save/restore

---

src/control/LatexController.cpp
src/control/LatexController.h

Fixes #1178. In particular:
* Now requires `kpsewhich` to be installed (provided by most latex distributions)
* Uses `kpsewhich` to check for `standalone`.

Make latex tool check for latex package dependencies

---

CMakeLists.txt

We forgot to update the version number to `1.0.13` after we released `1.0.12`, so we'll should at least remember to do it now.

Update version number in CMakeLists

---

src/control/XournalMain.cpp
src/control/XournalMain.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/util/XojMsgBox.cpp
ui/main.glade
ui/xournalpp.css

I've meant to look into this for a while...
This PR will load a CSS file called  ui/xournalpp.css
We can pretty up Xournal using it and the users can make adjustments as well.
Non-coding contributors can potentially contribute css stylings.
I'm going to be doing some cursors using it ( I've converted all except custom cursors to css  - my next PR ).
NOTE:  The CSS selector uses the "name" property NOT the id. So I had to change main.glade:
```
<object class="GtkRevealer" id="floatingToolbox">
<property name="name">floatingToolbox</property>
<property name="visible">True</property>
...
```
**Note the** `<property name="name">floatingToolbox</property>`
We will have to go through the glade files and do some proper naming in order to allow clean css selectors.
--------------
I've also …

Let's Do CSS

---

readme/WindowsBuild.md
windows-setup/build-lua.sh

This adds the build script for lua in Windows. This was a longstanding todo.
The build script is optimized to handle also newer versions of lua if they are released and we should decide to update.

Add build script for lua

---

src/gui/XournalppCursor.cpp
src/gui/XournalppCursor.h

Rewrote much of the cursor code to make it consistent. 
Uses css cursor definitions ( now preferred by gtk ) as well as Custom drawn cursors ( many of which can be migrated to pngs eventually).
Now compares requested cursor change to last cursor to avoid rebuilding and assigning cursors constantly.
Part 2 of cursorCleanup ( PR #1222 )

css cursors

---

azure-pipelines/clang-format-applied.yml
azure-pipelines/format_diff_lines.pl

This PR makes the format check less aggressive by only checking lines changed by a commit/PR.
The test file is temporary and is meant to test the check; it will be removed by a rebase before merge.

Only apply clang-format to changed lines

---

src/gui/widgets/gtkmenutooltogglebutton.cpp

The tool toggle buttons (e.g. to select pen, eraser modes etc.) now use the appropriate icons from the icon theme instead of using the deprecated GtkArrow class.
Ideally, we should be replacing the entire `gtkmenutooltogglebutton` with a widget built out of existing widgets rather than copying and modifying a GTK file.

Replace use of GtkArrow with GtkImage in tool toggle buttons

---

po/cs.po
po/de.po
po/it.po
po/pl.po
po/xournalpp.pot
po/zh.po
po/zh_HK.po
po/zh_TW.po
src/gui/toolbarMenubar/ToolMenuHandler.cpp
ui/main.glade

Simple fix, I think I found everywhere it was misspelled.

Correct "dash-/ doted" typo in drop down menu

---

ui/about.glade
ui/exportSettings.glade
ui/fillTransparency.glade
ui/goto.glade
ui/images.glade
ui/main.glade
ui/pageTemplate.glade
ui/pagesize.glade
ui/pdfpages.glade
ui/plugin.glade
ui/pluginEntry.glade
ui/settings.glade
ui/settingsButtonConfig.glade
ui/settingsDeviceClassConfig.glade
ui/texdialog.glade
ui/toolbarCustomizeDialog.glade
ui/toolbarManageDialog.glade

Now that there is a xournalpp.css file  someone might want to style parts of Xournal++
I've added CSS accessible names to the glade file which match the id's. Only objects with non-generic id's have been done.
Script used:
```
#do not run twice... be careful but do delete current name="names" lines before 
#running this again by using:
#Note: remove the -i to test.
gawk -i inplace 'match($0, /(\s*).*class="(\S+)".*id="(\S+)"/,arr){ print $0; if(arr[2] != "GtkAdjustment") print arr[1] "  <property name=\"name\">" arr[3] "</property>"; next}{print}'  ui/*.glade
#now remove lines generated from for non-generic id's:
for xx in sid label vbox hbox box separatormenuitem menuitem image grid menu button; \
do sed -r -i  "/.*name=\"name\".*\\b$xx[0-9]+\\b/d" ui/*.glade;done
```

Support CSS:  Add name="name" property matching id's for all non-default id's

---

src/control/LatexController.cpp

By default, newly created latex objects are placed in the top left corner of the current page. This PR now sets convenient default locations:
* If the center of the viewport is on the current page, then place the new latex in the center of the viewport.
* Otherwise, place the new latex in the center of the current page (which may possibly be out of the viewport).
The default placement can obviously be improved, so feedback is welcome.
(There's also the option of turning the LaTeX tool into a real selectable tool, but that would require some work.)
I will be merging this in three days if there are no objections.

Place newly created latex objects in the center of the screen/page

---

src/util/XournalType.h

this is a commit from refactor_layout_resize but has nothing to do with the layout or the resize.
But it is recommended change, since it removes nearly all warnings regarding the XournalType checks. 
(empty statement)

Refactored XournalType to remove empty statement warnings of clang-tidy

---

src/undo/AddUndoAction.cpp
src/undo/AddUndoAction.h

Decrease translation complexity by removing redundant translation strings that differ by one whitespace.
Do some minor code cleanup

Translation cleanup

---

README.md

This adds the link to Crowdin to the Readme document to simplify the translation process for our users.

Add link to Crowdin to Readme

---

src/control/Control.cpp

Thats by the way why we should use the AAA style.
/home/febbe/ClionProjects/xournalpp/src/control/Control.cpp:2921:8: error: case value evaluates to -3, which cannot be narrowed to type 'guint' (aka 'unsigned int') [-Wc++11-narrowing]
case GTK_RESPONSE_ACCEPT:
^
/home/febbe/ClionProjects/xournalpp/src/control/Control.cpp:2931:8: error: case value evaluates to -2, which cannot be narrowed to type 'guint' (aka 'unsigned int') [-Wc++11-narrowing]
case GTK_RESPONSE_REJECT:

Fixed a bug, preventing some compilers to compile (narrowing conversion)

---

src/gui/XournalView.cpp

As the presentation remotes use the left and right keys for navigation, add the setting to enable them in presentation mode. The presenter can then use the remote and the xournalpp features, but not move elements with those keys anymore, hence its better to be an option.
This is a very tiny first step towards the wish list in #1168

Left and right key for navigation in presentation mode

---

.gitignore
readme/WindowsBuild.md

Since I reinstalled msys2 recently, I went through the Windows build process again. I found that you need the following msys2 packages:
- mingw-w64-x86_64-gcc
- mingw-w64-x86_64-cmake
- mingw-w64-x86_64-make
- patch (for the lua setup)

Windows build: needed packages update

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/MainWindow.cpp
src/gui/dialog/ButtonConfigGui.cpp
src/gui/dialog/DeviceClassConfigGui.cpp
src/gui/dialog/SettingsDialog.cpp
src/gui/inputdevices/InputContext.cpp
src/gui/inputdevices/InputContext.h
src/gui/inputdevices/InputEvents.cpp
src/gui/inputdevices/InputEvents.h
src/util/DeviceListHelper.cpp
src/util/DeviceListHelper.h

This inherits the changes from #1242. Including the fix to actually list the devices.
@michaelschufi please try it out.
There seems to still be a problem with the automatic mapping of the devices as a pen is currently automatically mapped to a mouse (or this is just Windows for you...)

Add device listing for devices not recognized by GDK

---

src/control/LatexController.cpp

Otherwise glib will provide a (likely spurious) last element in argv,
causing EFAULT to be returned from execve in the child:
```
...
[pid 32237] execve("/usr/local/bin/kpsewhich", ["kpsewhich", "standalone", 0x1], 0x7ffe7141a078 /* 69 vars */) = -1 ENOENT (No such file or directory)
[pid 32237] execve("/usr/bin/kpsewhich", ["kpsewhich", "standalone", 0x1], 0x7ffe7141a078 /* 69 vars */) = -1 EFAULT (Bad address)
...
```

NULL-terminate argument vector given to kpsewhich.

---

src/util/XojMsgBox.cpp

Fixes #1266 by using a Windows-specific API on windows. As usual, will merge in three days if there are no objections.

Fix help document web page not opening on Windows

---

src/control/Control.cpp

Now images pasted aren't zoomed in anymore because element sizes are now correctly represented by doubles.

Fix #1365 by correcting variable types from integer to double

---

src/gui/SearchBar.cpp

Implements and closes #1302. Not really happy with how jumping to previous is implemented, but we'll need to implement proper keybindings to make it nicer.

Enable search bar next/previous on enter/shift+enter keypress

---

src/control/Control.cpp

This fixes #877 by implementing the same pasting behavior used when pasting images/text/etc. from outside xournal (new generated xournal Elements). When pasting a selection though different behavior was used.

Fix #877 by copying pasting behavior other parts

---

src/gui/SearchBar.cpp

The "activate" signal is not necessary because as soon as text is changed
a new search is started anyway. key-press-events have to be handed to
the underlying widget after processing.

Fix #1385 search input not recognized

---

desktop/xournalpp.desktop

At the moment, Xournal++ is listed in "Utility" on most desktops, which is IMO not a suitable location. I think it belongs to "Office". Unfortunately "TextEditor" has been specified to belong to "Utility", therefore it must be removed. A replacement might be "WordProcessor", which belongs to "Office", but on the other hand a top level category should be sufficient.
See also https://specifications.freedesktop.org/menu-spec/latest/apas02.html, https://specifications.freedesktop.org/menu-spec/latest/apa.html.

Improve desktop entry categories

---

src/control/Control.cpp
src/control/xojfile/LoadHandler.cpp

Fixes #1397.
Test files used (.xopp files are in the .zip files), thanks to @tumb1er for the detailed report and the files!:
[new_corrupted.zip](https://github.com/xournalpp/xournalpp/files/3468831/new_corrupted.zip)
[2019-08-03-Note-16-17.zip](https://github.com/xournalpp/xournalpp/files/3468835/2019-08-03-Note-16-17.zip)
With this PR and the latest Xournal++ build from `master`:
- Opening 2019-08-03-Note-16-17.xopp gives the error `XML Parser error: Wrong count of points (1)` and keeps the current document in view, regardless of save/discard
- Opening new_corrupted.**xopp** gives the error `Document has no pages, so it is corrupted` and keeps the current document in view, regardless of save/discard
- Opening new_corrupted.**zip** DIRECTLY with the GTK type-to-search feature gives the …

Issue #1397: File contents are now kept if load fails, add "no pages" loading error

---

src/view/DocumentView.cpp

Fixes #1394. Will merge in 3 days if there are no objections.
The issue was that the cairo operator changes in
https://github.com/xournalpp/xournalpp/blob/a6276cd2955ba9762eba19d476b5fe67e55681bb/src/view/StrokeView.cpp#L84-L91
but the appropriate operator was not set before rendering text objects. Thus the text objects were rendered with the multiply operator instead of e.g. the over operator.

Fix text objects not rendering with the correct cairo operator

---

src/control/jobs/CustomExportJob.cpp
src/control/jobs/PdfExportJob.cpp
src/util/Path.cpp
src/util/Path.h
test/util/PathTest.cpp

Since #1117, we allow for extension like ".pdf.xopp". This change led to
a bug where overwrithing an existing ".pdf" file in pdf export created a
new file with the extension ".pdf.pdf" instead of overwriting the old
one. This is fixed and additionally all current and future export
filetypes show the same behaviour now.

correctly handle extensions when exporting

---

src/control/LatexController.cpp

Indicate the latex package that includes standalone when telling the user they need to install standalone.

improve hint for latex first timers.

---

src/model/Stroke.cpp

fixes #1425 
Now properly centered
and takes into account variable (pressure) width strokes.

Fix calculation of stroke's bounding rectangle

---

src/control/zoom/ZoomControl.cpp

Fixes scrolling when using zoom fit and resizing window.
Underlying issue was missing repaint of child widget. (refactor_layout_resize should be merged first)
Closes #1383
Closes #1132 
Closes #941

Fix zoom fit scroll

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/MainWindow.cpp
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Scrollbars normally fade out after a short time which makes it
impossible to use the scrollbars on touchscreens.

Add option to disable overlay scrolling

---

CMakeLists.txt
readme/LinuxBuild.md

Implements CPack configuration for `.deb` files. Addresses part of #1176 and fixes #959. We could also provide a Debian build on our CI setup.
Please let me know if I missed or misspecified a dependency.
TODO:

Add .deb cpack configuration

---

ui/settings.glade

As pointed out  by Spanish translator Adolfo Jayme
Changed from:    Background color for window Background
To:            Background color between pages

changed wording for preferences setting 

---

src/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
ui/xournalpp.css

Fixes two toolbar glitches:
- Icons changing size after customization (#1395)
-  Misaligned drop point during customization (#1455 )
It also adds instructions in css file for those who want to modify toolbar icon sizes (specifically see #1395)

Toolbars: icon size glitch and Customization misalignment

---

azure-pipelines/release.yml
mac-setup/build-app.sh
mac-setup/xournalpp.bundle

While packages are now created they miss parts of the application. This is because the Path was hardcoded which is not compatible with our pipeline setup. This PR makes the path parameterized.

Fix app generation for MacOS

---

CMakeLists.txt

build: use FindBacktrace.cmake instead of just assuming backtrace is available

---

src/control/ClipboardHandler.cpp
src/control/Control.cpp
src/control/jobs/ImageExport.cpp
src/model/FormatDefinitions.cpp
src/util/Util.h

This spares us from hardcoding it everywhere.
fixes #1368

refactor(Util): add DPI_NORMALIZATION_FACTOR

---

src/gui/XournalView.cpp

The  XournalView::clearMemoryTimer was going through the list of hidden pages from those viewed long ago  to latest viewed, skipping the first 4 and freeing the rest past a 2.8MB memory threshold..
this reverses that behaviour and goes through from recently viewed  to older so that we keep more recently viewed pages.

fix #1477  now freeing older pagebufs before newer .

---

ui/toolbarManageDialog.glade

* Fixed a regression (caused by #1283) in the toolbar manage dialog causing the `View > Toolbars > Manage` menu option to crash the application
* Fixed the toolbar manage dialog icon having the wrong path due to the AppStream id refactor

Fix toolbar manage dialog issues

---

.gitignore
readme/WindowsBuild.md

I updated the readme:
- We need `make` because PortAudio doesn't build using `mingw-w64-x86_64-make`.
- Added `lua-*` to gitignore.
- `cmake --build .` instead of `make`

Updating and clarifying Windows build readme

---

src/model/Stroke.cpp

Fixes #1542. Temporary point array was allocated using `g_malloc` instead of `new`, and should be deallocated using `free` instead of `delete[]`.
Since this is a serious issue, I will merge by tomorrow at the latest.

Fix segfault when pasting strokes (regression due to #1511)

---

azure-pipelines/release.yml

Fixed conditions and optimized tag matching for the Azure pipeline to push official releases via tags.
The new tag filter will take everything that starts with a version string or something resembling one. 
E.g. `1.0.1`, `1.0.1-alpha` but also `a.b.c` or `a-b.c.d` will trigger a release. Unfortunately a better trigger is not possible.
The releases will use the official git tag instead of using the generated version number from the CMakefile.

Fix automatic releases by pushing tags

---

azure-pipelines/util/format_diff_lines.pl
azure-pipelines/util/sample.cpp

* Now autodetects whether clang-format is called `clang-format` or `clang-format-8`
* Fixes an issue where irrelevant lines are formatted due to changed lines being formatted one-at-a-time. This should make the CI format checks way more reliable.
Merging in 3 days if there are no objections. A `sample.cpp` file is provided to demonstrate the changes; it will be removed in a rebase before merging. You can try out the new formatting logic by messing up the formatting on specific lines and then running
```bash
git --no-pager diff -U0 -- '*.cpp' | perl azure-pipelines/util/format_diff_lines.pl
````

Improve format_diff_lines.pl utility script

---

src/control/LatexController.cpp

User can now use \newline,\\\,  etc, to write on a new line in Latex Mode. Previously, all text would go in 1 single line and fill the entire width, so user would have to start a new TexMode if equation was getting too long

Enabled newlines in Latex

---

CMakeLists.txt
cmake/find/FindCXX17.cmake
src/util/CMakeLists.txt

Fixes #1553 (tested on a Ubuntu 18.04 image on Docker).
Note that CI did not catch this issue because the "new toolchain" PPA was added before installing build dependencies.
`readme/LinuxBuild.md` will need to be updated to indicate the new dependency on a compiler that supports C++17.

Fix build configuration

---

azure-pipelines/CI.yml
azure-pipelines/release.yml
azure-pipelines/steps/build_windows.yml
azure-pipelines/util/mingw-blob.yml

Building of the Windows dependencies is now outsourced to a separate pipeline saving three minutes of buildtime for CI and release jobs.

Outsource Windows dependency creation to separate pipeline

---

README.md
desktop/com.github.xournalpp.xournalpp.appdata.xml
readme/LinuxBuild.md

The correct spelling of openSUSE can be checked on https://en.opensuse.org/Portal:Distribution and of SUSE on https://www.suse.com.

Fixed misspelling of openSUSE and SUSE.

---

src/control/Control.cpp

Fixes #1341, now calls `this->clearSelectionEndText();` before exporting a document. Tested in my local environment (Kubuntu 19.04) and works correctly.

Fix textbox issues when exporting pdf

---

windows-setup/build-setup.sh

Partial fix for #1600 
Adds all libraries starting with the path `/c/windows/SYSTEM32/lib*`
As native Windows libaries do not start with `lib` this will only catch preinstalled libraries on the machine like OpenSSL.

Add ssl libraries to Windows setup

---

debian/rules

The fix for building translations added in #1602 breaks the build in a clean source tree.
```
$ git clone https://github.com/xournalpp/xournalpp.git
$ cd xournalapp/
$ dh_make -s --createorig -p xournalapp_1.0.6
$ debuild
[..]
debian/rules override_dh_auto_build
make[1]: Entering directory '/tmp/git3/xournalpp'
make translations all
make[2]: Entering directory '/tmp/git3/xournalpp'
make[2]: *** No rule to make target 'translations'.  Stop.
make[2]: Leaving directory '/tmp/git3/xournalpp' 
```
This fixes the command as described in the [Debian New Maintainers Guide](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#customrules):
>  If the Makefile in the source for gentoo requires you to specify build as its target to build it [52], you create an override_dh_auto_build target to …

Fix Debian build

---

src/control/stockdlg/ImageOpenDlg.cpp

Resolved the application crash while adding an image to the document as reported in #1648
Fixes #1648

Image Insert Crash Resolved

---

src/gui/dialog/GotoDialog.cpp
ui/goto.glade

This fixes bug #975.
Key changes:
- removed the "accelerator" that linked the enter key to the OK button. It appeared this forced the dialog to close before the value in the spin button was handled.
- used `gtk_entry_set_activates_default` to specify that when the Enter key is pressed in the spin box, the default option should be activated.
- included some settings that specified that the OK button was the one to activate by default (i.e. when the Enter key is pressed)
Additional changes:
- the Close button was changed to a Cancel button to be consistent with other dialogs
- Instead of the buttons creating values 1 and 2 (hardcoded), the OK and Close buttons response codes were replaced with the GTK-specified constants. (Unfortunately, this means there are weird -5 and -6 in the `.glade` …

Enable Ctrl-G dialog to be closed by "Enter"

---

azure-pipelines/steps/build_linux.yml
azure-pipelines/steps/install_deps_ubuntu.yml
azure-pipelines/translation.yml
src/control/AudioController.cpp
src/control/AudioController.h
src/util/audio/AudioPlayer.cpp
src/util/audio/AudioPlayer.h
src/util/audio/AudioQueue.h
src/util/audio/AudioRecorder.cpp
src/util/audio/AudioRecorder.h
src/util/audio/PortAudioConsumer.cpp
src/util/audio/PortAudioConsumer.h
src/util/audio/PortAudioProducer.cpp
src/util/audio/PortAudioProducer.h
src/util/audio/VorbisConsumer.cpp
src/util/audio/VorbisConsumer.h
src/util/audio/VorbisProducer.cpp
src/util/audio/VorbisProducer.h

While fixing clang-tidy warnings, I found possible bugs I fixed:
- The AudioQueue's threads could be unaware of changes done in other threads, 
because those changes were done non atomic or not in a fixed memory ordering ensured by a mutex/lock.
- Same for VorbisConsumer and VorbisProducer
- Fixed possible ressource leak of the "SNDFILE_tag" - ressource
- Fixed memory leaks of undeleted std::thread's 
--
- Refactored all touched files.

Fixed possible PortAudio integration bugs

---

src/gui/inputdevices/AbstractInputHandler.cpp
src/gui/inputdevices/AbstractInputHandler.h
src/gui/inputdevices/HandRecognition.cpp
src/gui/inputdevices/InputContext.h
src/gui/inputdevices/TouchInputHandler.cpp
src/gui/inputdevices/TouchInputHandler.h

Fix for issue #1668
I decided to call the reset method of the TouchInputHandler from HandRecognition, so it also works without the internal hand recognition turned on.

Zoom + Pen fix

---

.clang-format
azure-pipelines/clang-format-applied.yml
azure-pipelines/util/format_diff_lines.pl

Hello there,
I modernized the formatting in our .clang-format file.
Currently it's hardly aligned on googles style, as we discussed.
But I also did some changes, wanted by @LittleHuba and a bit of personal preference influenced it.
Please take a look and give fast feedback, I want to merge it tomorrow. And format all files accordingly so the pr-freeze can finally come to an end.
Aditionally I want to merge all current merge requests before.

Modernize formatting

---

.clang-tidy

I adjusted the readability-identifier-naming options to match our coding convention:
>* Names are CamelCase (namespaces, classes, structs, enums, etc.)
>* Members are camelBack
>* Functions are camelBack
>* No underlines are used
note: I left some aNy_CasE to give some versatility in source files. So 
> * No underlines are used
may not correct any more.

adjusted formatting

---

src/control/Control.cpp
src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/control/tools/EditSelectionContents.cpp
src/control/tools/EditSelectionContents.h
src/model/Layer.cpp
src/model/Layer.h

Addresses the bug half of #810. The feature request (bring to front / bring forward / send to back / send backward) still should be resolved.
When selecting elements, the elements are be pulled to the top. The bug this PR addresses was that these elements were not returned to their original order within the layer. 
Happy to take constructive criticism on design choices; it's been a long while since I've worked in C++ on a large project.

Preserve element ordering within layer during selection

---

azure-pipelines/steps/build_mac.yml

Latest Ninja requires Catalina or newer, so stick on Ninja 1.9.0 for now.

Fix MacOS builds

---

azure-pipelines/steps/build_mac.yml
src/control/Control.cpp
src/control/jobs/RenderJob.cpp
src/control/tools/EditSelection.cpp
src/control/zoom/ZoomControl.cpp
src/gui/MainWindow.cpp
src/gui/PageView.cpp
src/gui/RepaintHandler.cpp
src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/XournalppCursor.cpp
src/gui/inputdevices/AbstractInputHandler.cpp
src/gui/inputdevices/InputContext.cpp
src/gui/inputdevices/InputContext.h
src/gui/inputdevices/KeyboardInputHandler.cpp
src/gui/inputdevices/MouseInputHandler.cpp
src/gui/inputdevices/PenInputHandler.cpp
src/gui/inputdevices/StylusInputHandler.cpp
src/gui/inputdevices/TouchDrawingInputHandler.cpp
src/gui/inputdevices/old/InputSequence.cpp
src/gui/inputdevices/old/NewGtkInputDevice.cpp
src/gui/inputdevices/old/NewGtkInputDevice.h
src/gui/scroll/ScrollHandlingGtk.cpp
src/gui/scroll/ScrollHandlingGtk.h
src/gui/scroll/ScrollHandlingXournalpp.cpp
src/gui/scroll/ScrollHandlingXournalpp.h
src/gui/widgets/XournalWidget.cpp
src/gui/widgets/XournalWidget.h
windows-setup/build-setup.sh

As I've mentioned in multiple issues, we'll need to refactor some of the rendering/zooming/scrolling code to fix the outstanding bugs and to prepare for the new file format features. Basically, we can start out by refactoring some of the existing code, i.e. dealing with #1433.
This PR removes the custom GTK widget in `src/gui/widgets/XournalWidget.cpp` and replaces it with a wrapper around a `GtkDrawingArea`.
TODO:
Notes:
* This PR will be as minimal as possible since it touches a lot of files.
* `GtkDrawingArea` is connected to the `GDK_CONFIGURE` event by default, which is fired on window visibility changes. This is useful for figuring out when to re-layout the document, but it's also causing several new problems.
* #1694 shows up here, whereas it didn't with the previous widget. …

Viewport rewrite: Round 1

---

appimagecraft.yml

An appimagecraft-only workaround that ensures the translations are updated before the actual build.
Not an alternative to #1617 but actually a hack that only fixes problems related to appimagecraft builds on clean Git repository checkouts. I strongly recommend going for #1617, if possible.
This PR is safe to merge, as it won't affect any build pipelines, and it's future proof in that it is unnecessary but won't harm after merging #1617.
CC #1448.

Make sure translations are built before installation (workaround)

---

src/util/Path.cpp
test/util/PathTest.cpp

If `Path::fromUri` is passed an invalid location, `g_filename_from_uri` will return NULL, which will cause xournal++ to crash. 
The error below happened when attempting to start xournal++. The crash happens from what appears to be an invalid recent files entry from VMware (`file://[nfs-vm2] WIN10-WKS-14/WIN10-WKS-14.vmx`).
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
Thread 1 "xournalpp" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff64d33eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff64b2899 in __GI_abort () at abort.c:79
#2 …
```

Prevent crash on invalid recent files entries

---

src/pdf/base/XojCairoPdfExport.cpp
src/pdf/base/XojCairoPdfExport.h

Fixes #1740. This feature is only available with Cairo 1.16 or newer; it will be automatically enabled if supported. Ubuntu 19.04 has Cairo 1.16, as well as the popular rolling releases (e.g. ArchLinux, Solus).
Merging in 3 days if no objections.

Preserve PDF outline information in exported PDF

---

po/CMakeLists.txt

Fixes #1596. Supersedes #1617.
Apparently, the `gettext_create_translations` function has a parameter called `NOUPDATE` that generates the `.po` file in the build directory rather than updating it in place. 
In hindsight, we could've saved a lot more time if we had taken a closer look at that `cmake/find/Gettext.cmake`.
We can probably remove some of the translation build commands in the CI config to catch packaging/translation errors in the future.

Fix translation target

---

src/control/XournalMain.cpp

When the "dark theme" option is set, the iconsDark directory should be
the first dir where the icon theme should search for the icon. By
prepending this path after the default icons path has been set, we make
sure that this dir is indeed the first in the list of dirs to look up
icons.
Fixes issue #1746.

Prepend iconsDark path after setting default path.

---

src/gui/dialog/ExportDialog.cpp
src/pdf/base/XojCairoPdfExport.cpp

When choosing to export a custom page range (either a single page or multiple ones) xournalpp has been crashing every time because indices were out of range.

Fix crash when exporting single pages

---

azure-pipelines/continuous-integration.yml
azure-pipelines/release.yml
azure-pipelines/steps/build_mac.yml

Working version of #1779. Changes:
* Switch to Catalina image on CI
* Set `macosx-version-min` flag. Currently, we are backwards compatible with 10.13.
* Change Boost source mirror
Merging if build succeeds; we can fix other issues (like pipeline dependencies) later since it's important to stop CI from failing every commit first.

Fix MacOS build

---

src/control/tools/SplineHandler.cpp
src/control/tools/SplineHandler.h
src/model/SplineSegment.cpp
src/model/SplineSegment.h

This commit implements cubic splines. At every knot you can adjust the tangent by click-dragging. The longer the drawn tangent, the stronger its influence. If all tangents are trivial (only click, no click-drag), it will be a linear spline as before.
The last set knot and the last set tangent can be modified using the keyboard (e, s, r, b for extend, shrink, rotate and back rotate).
If the spline is closed the tangent of the first knot will be used for the last knot as well, so the join will be smooth (if the tangent of the first knot is non-trivial).

Implementation of cubic splines

---

src/model/Stroke.cpp
src/model/eraser/EraseableStroke.cpp

This should fix the bug from issue #1818. 
I can't say what this padding is supposed to be for (it seems to work fine without), that the original author coded (more than 9 years ago). Should I simply remove it?

fix eraser bug

---

src/control/zoom/ZoomControl.cpp

Fixes #1753
Fixes #1587 (which is listed as a duplicate of #1516 though I'm not sure it is)
The 'zoomWidgetPosX' and 'zoomWidgetPosY' are actually offsets, not
positions, and the current code was not taking that into account when
setting the variables.
In addition, I don't believe the size of the toolbars (essentially
'wx' and 'wy' from what I can tell) are relevant. I tested and found
less scrolling when these were removed.

Fix zooming with ctrl + scroll 

---

plugins/ToggleGrid/togglegrid.lua
src/control/tools/BaseStrokeHandler.cpp

I find the grid size too large.  Since I was the one who originally put it at the same size as the squares on the grid paper, and I found that too large, I'm being bold enough to change it to half that for now.  Really, it would be nice to have an easy way to change it back and forth.
I also looked over the lua plugin examples.  I changed the example so there were not so many menu items.  
I determined that using the plugin API wasn't going to be super easy, so I ditched it for now.  Maybe someone more familiar with glade and gtk can add to the GUI to change the grid size.  It really seems to me that having the gridSize variable set locally in BaseStrokeHandler.cpp is not the best, but it is how I did it last year.  It seems that it should be something that is set in the GUI, and …

Cut grid size in half; tidied up the togglegrid lua plugin.

---

src/gui/PageViewFindObjectHelper.h

Fixes #1718.
The current first-matching-object algorithm has poor UX when attempting to
select from overlapping objects.

Change Select Object algorithm to search for closest element

---

azure-pipelines/clang-format-applied.yml
azure-pipelines/continuous-integration.yml
azure-pipelines/release.yml
azure-pipelines/steps/install_deps_ubuntu.yml
azure-pipelines/translation.yml

This PR moves CI from Ubuntu 16.04 to 18.04. We are dropping support for 16.04 for `1.1.0` since we are using C++17 (`1.0.x` will be kept on 16.04 as it does not need C++17 features). Also, Ubuntu 20.04 LTS was released today and there's going to be even less of a reason to support 16.04 now.
Fixes #1732.

Move CI to Ubuntu 18.04

---

src/gui/Layout.cpp
src/gui/Layout.h

Fixes #1660. The scroll now jumps awkwardly instead of crashing, but it's better than crashing. ¯\\\_(ツ)\_/¯
Merging if CI passes.

Hotfix for #1660

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/XournalppCursor.cpp
src/gui/dialog/SettingsDialog.cpp
src/util/Util.cpp
src/util/Util.h
ui/settings.glade

This PR enhances the cursor highlight.
* The color can now be adjusted (implements #1891).
* The radius of the circle can now be adjusted.
* Allowing a border on the circle along with a customizable color/thickness.
I may also look into:
* Separating the highlight from the cursor, which will serve as an alternative to #1778 and possibly combine features from #1822.
Preview:

Add options to customize cursor highlight color and radius

---

src/control/XournalMain.cpp

This pull request adds a command line option to print the version of xournalpp on the commandline.
Example:
```bash
$ build/src/xournalpp --version
Xournal++ 1.1.0+dev
```

Add option to print version from cli

---

src/control/settings/Settings.cpp
src/control/tools/ArrowHandler.cpp
src/control/tools/BaseStrokeHandler.cpp
src/control/tools/BaseStrokeHandler.h
src/control/tools/CircleHandler.cpp
src/control/tools/CoordinateSystemHandler.cpp
src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/control/tools/RectangleHandler.cpp
src/control/tools/RulerHandler.cpp
src/control/tools/RulerHandler.h
src/control/tools/SnapToGridInputHandler.cpp
src/control/tools/SnapToGridInputHandler.h
src/control/tools/SplineHandler.cpp
src/control/tools/SplineHandler.h
src/model/Snapping.cpp
src/model/Snapping.h
ui/settings.glade

With this commit all knots of the spline are snapped to grid if the corresponding setting is activated.
I reused the snapToGrid code from BaseStrokeHandler.cpp. There was probably a better way of doing it, but I don't know what is the best way. Hence I just copied this function to the SplineHandler.
Now I will take care of user tapping.

snap to grid and user tapping for splines

---

src/gui/Layout.cpp

When moving to the last page of the following PDF document, https://dx.doi.org/10.1109/TSE.1985.232210,
xournal++ hangs (segfaults). You can try to move to the last page either by scrolling
or by setting the page number in the spinpage box, the result will be the same.
After some debugging, I narrowed it down to the latest statement of Layout::updateVisibility():
this->view->getControl()->firePageSelected(mostPageNr). For some reason, this was triggering an
infinite storm of events.
My solution was to avoid firing the page selected event by checking if any change indeed occurred
in the layout. I used the variable mostPageNr to detect if there was any change: if it wasn't
changed by the updateVisibility()'s algorithm, the value would be the same as of its initilization.
By not calling …

Fix issue #1867.

---

CMakeLists.txt
cmake/README.md
src/config-dev.h.in
src/control/Control.cpp
src/control/XournalMain.cpp
src/control/XournalMain.h
src/gui/MainWindow.cpp
src/util/CrashHandlerUnix.h
src/util/Util.cpp
src/util/Util.h

Fix https://github.com/xournalpp/xournalpp/issues/1101:

Respect the XDG base directory specification

---

src/gui/XournalppCursor.cpp

This Commit changes the Pen/Highlighter Cursor to have the form of a
circle (via `cairo_arc`) and also uses the set size to give a correct
impression on how big the line one is about to draw is.
This PR would resolve #1513. Note that it would make my previous PR #1941 obsolete.

Implement Pen/Highlighter Cursor correct size

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/dialog/SettingsDialog.cpp
src/gui/inputdevices/StylusInputHandler.cpp
src/gui/inputdevices/StylusInputHandler.h
ui/settings.glade

Add option to ignore the first events of the stylus when touching the screen to avoid artifacts at the beginnings of strokes. The number of ignored events can be set in the preferences.
I had this problem on Kubuntu 18.04: When the stylus is pressed on the screen, the accuracy and update rate of its recognized position increases. Because of the lower precision before, when hitting the screen the cursor might jump from its previous position to the more precise point (this is especially far if the pen tip was in rapid movement right before touching), while beeing recognized as writing. This can result in artifacts that e.g. make handwritten text very hard to read. To work around this, the first events since the triggering event can be ignored.
This works great for me (when ignoring the …

Add option to ignore the first events of the stylus when touching the screen.

---

src/control/ToolEnums.cpp
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/dialog/SettingsDialog.cpp

This pull request addresses issue #1961 (button-related settings are saved and used in the wrong order).

Fixes #1961

---

src/control/tools/Selection.cpp
src/control/tools/Selection.h
src/gui/PageView.cpp

This PR implements the following feature: when using the Select Rectangle or Select Region tools, clicking on an object (without dragging to create the rectangle or the selection region) selects the object. This is similar to the experimental feature "Tapping" that allows the selection of an object when drawing.
I find this particularly useful as it allows me to use a single selection tool (I associate Select Rectangle to the middle mouse button) both to select multiple objects (dragging a rect around them) or a single one (with a single click).

Allow "tapping" when using the Select Rectangle and Select Region tools

---

src/gui/XournalppCursor.cpp

This PR fixes #1954.
**Root Cause:**
The functions `createHighlighterOrPenCursor` and `getEraserCursor` were
returning early if the cursor type had not changed. This prevented the
update of the cursor size, based on the new setting.

Fix cursor update to apply always

---

src/control/pagetype/PageTypeHandler.cpp
src/model/PageType.h
src/view/background/IsometricBackgroundPainter.cpp
src/view/background/IsometricBackgroundPainter.h
src/view/background/MainBackgroundPainter.cpp
ui/pagetemplates.ini

This PR adds isometric paper backgrounds in two flavours:
* Full Graph `isograph`
* Dotted `isodotted`
I implemented both in the  `IsometricBackgroundPainter` and added templates to the `pagetemplates.ini`.
**Example**
**Reviewers**
Please check that I implemented all required handlers. I am new to the code-base and not sure if I found all places.
Closes #1942

Add Isometric Paper Background

---

azure-pipelines/steps/build_windows.yml
readme/WindowsBuild.md

Delete the existing msys64 installation before building. This is a temporary hack until we figure out a better solution.

Windows CI quickfix

---

src/control/xojfile/LoadHandler.cpp
src/control/xojfile/LoadHandler.h
src/model/Document.cpp
src/model/Document.h

This PR speeds up the loading of PDFs and annotated PDFs significantly.
Main changes:
* Introduced an index from pdf page number to document page number, which reduces the lookup times of `Document::findPdgPage()` from `O(n)` to constant time.
This index is generated on document read and on demand.
Interactive document changes such as adding/inserting/deleting a page simply invalidate this index to keep the user interface snappy.
This speeds-up the load-time of PDFs with many labels such as books.
* Changed the `xojfile/LoadHandler` to add pages in a bulk after parsing instead of calling `addPage` once per page while parsing. This required to add a bulk version `addPages`, which is templated and thus visible in the header. I hope that's not against some coding rules. 
Starting point for …

Speedup Document Loading

---

src/control/PdfCache.h
src/gui/XournalView.cpp
src/gui/sidebar/previews/base/SidebarPreviewBase.cpp

This prevent previous PDF pages being rendered instead of new PDF ones.
Fixes #1964

Clear PDF cache when document changes

---

src/control/Control.cpp
src/control/Control.h
src/control/XournalMain.cpp

This pull request resolves #1872  .
I chose to create a new file by default when the filename does not yet exist, as this is the standard behaviour for most command-line-tools I know (e.g. vim). However, I realized that inkscape and gimp through an error if the file does not yet exist. Thus, I'm sure what the best solution is. Using a flag like `--new` to explicitly request a new file would also be an easy addition to this pull request

Add feature to create new xopp file from cli

---

CMakeLists.txt
azure-pipelines/release.yml
azure-pipelines/steps/build_mac.yml
cmake/find/FindFilesystem.cmake
src/CMakeLists.txt
src/gui/Layout.cpp

This PR fixes the MacOS builds. Although the issues have actually been present since the forced move to MacOS 10.15 due to the Azure Pipelines update, they had not been exposed until we also updated the regular CI runner to check backwards compatibility with 10.13.
* Switch from Boost filesystem to https://github.com/gulrak/filesystem, which is mostly compliant with C++17 filesystem. Note that the supplementary filesystem library is only used if `std::filesystem` is not supported. The new library will be downloaded automatically by CMake at compile time.
* Fix some backwards compatibility issues.

Fix MacOS 10.13 compatibility issues (build and CI)

---

src/pdf/base/XojCairoPdfExport.cpp

As suggested by the bug reporter, the pdf title will now be without path, just the filename.

fix  bug #2038

---

src/CMakeLists.txt

Fixes #2048.
I'm surprised that this got past CI given that we're using Ubuntu 18.04 as our CI image.

Fix compilation error on CMake >= 3.10 and < 3.12

---

azure-pipelines/jobs/release_ubuntu.yml
azure-pipelines/release.yml

Adds Ubuntu 20.04 to release builds. This should help discoverability and resolve a lot of installation problems.
Also removes the `condition: always()` since the only thing that it achieves is preventing build cancellations.
After merging, this needs a change in the deployment pipeline in the renaming step.
```diff
- for f in linux-ubuntu-packages/xournalpp-* linux-debian-packages/xournalpp-*; do
+ for f in linux-ubuntu-*-packages/xournalpp-* linux-debian-packages/xournalpp-*; do
```

Add Ubuntu 20.04 to release builds

---

src/control/xojfile/SaveHandler.cpp
src/model/Document.cpp

This commit makes it possible to move pdf+xopp files into a new folder, without running into the problem that (by default) the absolute path to the pdf is saved in the xopp file. 
All you need to do is to choose "Annotate pdf" in the menu, check the "attach file to the journal" option on the bottom left of the file dialog and then save the xopp-file. If you name your xopp file `foo.xopp`, a copy of the pdf will be saved with the name `foo.xopp.bg.pdf` . You can then move both files simultaneously to another directory. You can also rename both files simultaneously to `bar.xopp` and `bar.xopp.bg.pdf`, just make sure that they only differ by the ".bg.pdf"-ending.
In the save file dialog I have stripped the suggested name for the xopp-file from the .pdf ending in "attach file to the journal" …

fix attached mode pdf saving

---

src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

This commit implements the change suggested in #2091. It also changes
the unmatched combo box label value "91000" to "96100" to reflect the
integer value that the `load` settings function expects.

Add 16kHz sample rate and fix 91kHz CB label.

---

src/gui/PageViewFindObjectHelper.h

The code used for selecting an object was flawed. Apparently the idea was to allow selecting an object on all visible layers, but in reality only the first visible layer was checked. I think it makes more sense to only allow selecting objects from the currently selected layer. This explains my fix. The PR fixes #2081 and avoids the "selection-crash" examined in #2133.

fix crash after selecting object from other  layer

---

src/control/Control.cpp
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/settings/SettingsEnums.cpp
src/control/settings/SettingsEnums.h
src/gui/XournalppCursor.cpp
src/gui/dialog/SettingsDialog.cpp
src/gui/dialog/SettingsDialog.h
ui/settings.glade

Support a "no icon" cursor type for stylus use for a more "like paper and pen" experience with less distraction.
See issue #2093
I have replaced the `showBigCursor` boolean setting with a `stylusCursorType` enum and updated the settings and preference pages.
- Followed the settings config for `scrollbarHideType`
- used toString/fromString methods to avoid repetition of constants
- saved the setting as text rather than an int to be readable
- add an xml comment for the available options
- Followed the ui config for `cbAudioSampleRate`
- Followed the dialog layout for the stylus screen
- used a frame and full width combo
- I have copied the alignment
- Replaced use `showBigCursor` cursor with an enum
- Defaulted the enum to the current DOT cursor
- I have run git-clang-format
I have tested: …

Support "no icon" stylus cursor type #2093

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
ui/main.glade

This is a suggested fix for #2074 to hide toolbars as easily as other screen furniture. It is based on the toggle menu item for hiding the sidebar and bound to the F9 accelerator.
- I have cached the currently visible toolbar as `ToolbarData* lastToolbar`. I don't know the implications of storing that (e.g. could it become invalidated?) or where it should best be kept. Could just store the id if necessary.
- Unlike the `show sidebar` I haven't created a persistent setting for hidden toolbars
- It's kind of odd that menu accelerators no longer work if you hide menus
- I think it would be neater to have _Zen Mode_ to disable toolbars/menu/side-bar in one step
- If this is accepted, we can also remove the `Empty Toolbar` toolbar type which I find a bit weird

Add "Show toolbars" menu toggle item bound to F9

---

README.md

I added notices about the availability of Xournal++ Mobile as official mobile app in the readme as well as a notice about Xournal++ as a early preview version.
Moreover, I included Xournal++ Mobile into the `Installation` list and into the `Building` list.
Should the back links pointing to the Xournal++ Mobile repo point to the GitHub mirror or to the original upstream on GitLab?

Included Xournal++ Mobile into README

---

CMakeLists.txt
resources/default_template.tex
src/control/LatexController.cpp
src/control/LatexController.h
src/control/XournalMain.cpp
src/control/latex/LatexGenerator.cpp
src/control/latex/LatexGenerator.h
src/control/settings/LatexSettings.cpp
src/control/settings/LatexSettings.h
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/xml/XmlTexNode.cpp
src/control/xml/XmlTexNode.h
src/control/xojfile/LoadHandler.cpp
src/control/xojfile/SaveHandler.cpp
src/gui/dialog/LatexSettingsPanel.cpp
src/gui/dialog/LatexSettingsPanel.h
src/gui/dialog/SettingsDialog.cpp
src/gui/dialog/SettingsDialog.h
src/model/TexImage.cpp
src/model/TexImage.h
ui/latexSettings.glade
ui/settings.glade

This PR implements various enhancements for the LaTeX tool, including:
* Apparently this is already supported by pressing <kbd>Shift</kbd><kbd>Enter</kbd>

Latex tool enhancements

---

src/util/PathUtil.cpp

std::filesystem::create_directories returns false if no folders were created which can be the case if the folder already exists (which will be most of the time). This simply adds a check beforehand to ensure no errors are presented if none occured.

Check if folder exists in ensure folder exists

---

src/control/XournalMain.cpp
src/gui/toolbarMenubar/model/ToolbarColorNames.cpp

This happened because a unknown flag "e" for g_fopen has been used. This is defined as "undefined/implementation defined" behaviour. Maybe introduced due to an patch to the underliing C-API on windows.

fixup crash when closing xournalpp on windows

---

src/util/PathUtil.cpp

This commit handles a bug in mingw: fs::copy_options::overwrite_existing is ignored on copy
Fixes #2210

Delete existing file before override:

---

src/control/Control.cpp
src/control/jobs/BaseExportJob.cpp
src/control/stockdlg/ImageOpenDlg.cpp
src/control/stockdlg/XojOpenDlg.cpp
src/gui/dialog/LatexSettingsPanel.cpp
src/gui/dialog/PageTemplateDialog.cpp
src/gui/dialog/SettingsDialog.cpp
src/util/PathUtil.cpp
src/util/PathUtil.h

For that a new utility function has been introduced `Util::fromGtkFilename`
Which parses an owned char* to an fs::path and deletes the char*

Fixed several memory leaks after the use of gtk_file_chooser

---

src/model/Document.cpp
src/util/PathUtil.cpp

This happened, when the `fs::path` object is relative.
fixes #2226

fixed bug in `Util::toUri`, which prevented the generation of a URI.

---

src/pdf/base/XojCairoPdfExport.cpp

Fixes #2236. This PR resolves the exporting issue, while d2665ed resolves a related loading issue (but does not directly fix the bug).
Note: this fixes a regression from 1.0.17.

Fix PDF export crash when outline is empty

---

README.md

I have also enabled builds for `armhf`, `arm64`, PowerPC, and `s390x` architectures.
See https://github.com/xournalpp/xournalpp/issues/1013#issuecomment-692656810 for more details.
I am watching releases, and will initiate the build process when a new stable version is released.
I mentioned that this PPA is _not_ maintained by the Xournal++ team. Any suggestions on that?

Add stable PPA to README. Fixes #1013, Fixes #2198

---

src/gui/XournalppCursor.cpp

When rebasing PR #2011 and solving merge conflicts I accidentally deleted a line, which defines the cursor for the resizing cursor while near top and bottom anchor. This is fixed here.

fix bug for top and bottom resize anchor cursor

---

src/control/Control.cpp
src/control/Control.h
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/dialog/LanguageConfigGui.cpp
src/gui/dialog/LanguageConfigGui.h
src/gui/dialog/SettingsDialog.cpp
src/gui/dialog/SettingsDialog.h
ui/settings.glade
ui/settingsLanguageConfig.glade

If the user hasn't set up locales properly, or wants a different language due to any reason, it would be easiest if they can select their preferred language from a drop-down menu.
This PR:
- adds a GUI for selecting the language (depicted below)
- searches  for the available languages by searching any directories in PACKAGE_LOCALE_DIR for xournalpp.mo files
- writes the selected language to the config
- automatically sets the previously selected language as the default in the menu
Currently untested on macOS and working on a few banal translations (as not offering translations for the language settings would be a bit ironic).
Currently available translations:
- German
- Russian
- Spanish
- French
Should help in cases such as https://github.com/xournalpp/xournalpp/issues/2181.

Select the language from settings

---

CMakeLists.txt
debian/package_description

Everything is done according to Debian guidelines and  informations printed by `lintian`
lintian report for currently available packages:
```
E: xournalpp: debian-changelog-file-missing
E: xournalpp: extended-description-is-empty
E: xournalpp: missing-dependency-on-libc needed by usr/bin/xournal-thumbnailer and 1 others
E: xournalpp: no-copyright-file
E: xournalpp: unstripped-binary-or-object usr/bin/xournalpp
W: xournalpp: binary-without-manpage usr/bin/xournal-thumbnailer
W: xournalpp: binary-without-manpage usr/bin/xournalpp
W: xournalpp: script-not-executable usr/share/xournalpp/ui/icons/hicolor/update-icon-cache.sh
W: xournalpp: script-not-executable usr/share/xournalpp/ui/iconsDark/hicolor/update-icon-cache.sh
```
lintian report after these patches:
```
E: xournalpp: …
```

Debian packaging improvements

---

src/control/Control.cpp
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/XournalView.cpp

Fix for #2082 and #1002 and progress towards user defined keymaps #919 for @rolandlo to test.
Keyboard accelerators for things like copy/paste/fullscreen/tools are bound by the menubar definition in glade. When the menubar is hidden, they no longer work.
There is no way to use the menubar programmatically when hidden and no other way I could find to hide it that preserved the accelerators so the only path I could see was to manually rebind them when the menubar is hidden. We can't have menubar and manual accelerators bound at the same time so they have to be toggled on/off when the menubar is reshown.
This means we have duplication of the accelerator definitions in glade and `initGlobalAccelerators` that must be kept in sync. If we removed the accelerators from glade then we would lose …

Rebind accelerators when the menubar is hidden

---

src/gui/MainWindow.cpp

Fixes #2291 by only setting those toolbar widgets visible, which have at least one child.

fixup borders from empty toolbars

---

src/control/Control.cpp
src/gui/Layout.h
src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/scroll/ScrollHandlingGtk.cpp
src/gui/widgets/XournalWidget.cpp

Try once more to fix the page layout updating. I had to open a new PR, because I messed up the old one (#2312).
This PR should fix #2289 and #1926 about focus shift to the beginning of the document after inserting a page. It may also fix the freeze from #2211 and #2144 when inserting a blank page in a pdf document.
The page layout now gets updated immediately after inserting the page. That only happens after some time (usually too late) without this fix. It also removes an unnecessary call to firePageSelected, since this action is called from scrollToPage anyway.

Fix page layout update

---

debian/control
debian/package_description

- Copied dependencies from official .deb package of 1.0.19 to debian/control (otherwise, the PPA package could not be installed in Ubuntu 18.04, as some of the automatically generated dependencies were missing from the repositories)
- Updated suggests and description in debian/control
- fixed typo in description - preassure --> pressure
This is ready for merge.

1.0.x - update dependencies in debian/control, fix typo in package_description

---

src/control/RecentManager.cpp

Resolves #2225.
Please note that while this solves the "crash and burn" issue Xournal++ encounters when even a simple `fs::exists` failes, in #2225 I also had quite high timeouts – 10s or 30s _for every affected file in recents_.
10s alone is quite a bummer, but it adds up. My case is quite special, but let's assume that one just has a very slow network drive. 10 files that take 3s each for `fs::exists`, that's 30s just to start Xournal++. Maybe we just want to drop `fs::exists` here and only call that when we actually want to open a single file?

Drop fs::exists check for recent files

---

src/control/Control.cpp
src/gui/XournalView.cpp
src/gui/scroll/ScrollHandlingGtk.cpp

backport of 23aee5dd847d10204b62fd8b406c91888b114a9e
I did this by updating my local 1.0.x branch (via 
```term
git checkout 1.0.x
git fetch upstream
git merge upstream/1.0.x
git push origin 1.0.x
```
and then I cherry-picked via 
```term
git cherry-pick -x 23aee5dd847d10204b62fd8b406c91888b114a9e
```
and resolved all conflicts. 
Is that the way that is done in general? To solve the merge conflicts was tedious, since the git patched the incoming changes mostly at the wrong line numbers.
Anyway I managed to solve all conflicts. I tested out the back-ported fix and it worked fine.

1.0.x - fix page layout update after inserting a new page

---

debian/control
debian/package_description

- Copied the dependencies from the official debian package. Otherwise, the generated debian package (in the PPA) had  dependencies which were unavailable in Ubuntu 18.04, and as a result, the (stable releases) PPA package for 1.0.19 could not be installed in Ubuntu 18.04.
I have verified that these updated dependencies make it possible to use the PPA in Ubuntu 18.04, and I could not notice any regression in either 18.04 or 20.04.
- Also updated suggests field
- Also updated description
This will automatically add current dependencies to the official daily builds PPA.

Updated dependencies and description in debian/control

---

src/control/zoom/ZoomControl.cpp

Fixes #1690 according to my tests. 
I included a warning so that we would see it right away if this code change created any unintended complications. The warning can be removed later.

fix presentation mode after startup

---

src/control/AudioController.cpp
src/control/settings/PageTemplateSettings.cpp
src/control/xojfile/SaveHandler.cpp
src/gui/MainWindow.cpp
src/gui/toolbarMenubar/ColorToolItem.cpp
src/gui/toolbarMenubar/model/ToolbarColorNames.cpp
src/util/Stacktrace.cpp
src/util/logger/Logger.cpp
src/util/serializing/HexObjectEncoding.cpp
test/util/I18nTest.cpp
test/util/StringUtilsTest.cpp
test/util/XojPreviewExtractorTest.cpp
windows-setup/xournalpp_launcher.cpp

I made the following changes:
- Changes some C headers to C++ headers,
- `NULL` changed to `nullptr`
- `sprintf` changed to `snprintf` (not in every occurrence, but some where I deemed it OK)
- Changed `%x` format specifiers of `sprintf` with `PRIuxN` where appropriate (where `uintN_t` was used).
- Removed a use of `g_strdup_printf` thus avoiding the dynamic allocation.

Minor touchups for C++17

---

src/control/XournalMain.cpp
src/gui/XournalView.cpp
src/gui/XournalView.h

Fixes #1777. 
Partially fixes #2411.
Also fixes page update after page deletion (which is relevant for navigating through pages in plugins) and after other changes of page layout than switching from paired view to non-paired view.
I also simplified the code in `XournalMain::run`, since the timing issue is solved with the new page layout method anyway.
Note that zooming in and out may still change the active page (although not drastically any more). This is due to the fact, that the `Layout::updateVisibility() method computes the most visible page and makes that page the active page and that `scrollToPage` makes the top of the page visible.

Fix page layout update in a unified way

---

src/gui/PageViewFindObjectHelper.h

Fixes #2477
I have also included a slight simplification and clarification of the algorithm, since the matching rectangle `matchRect` is only used locally and not updated in any way.

Fix select object algorithm bug

---

README.md

See #2231
The current version may lead to the idea, the PPA should also be used by Debian users, which is not the case (https://github.com/xournalpp/xournalpp/issues/2231#issuecomment-691574344).
This PR adds more infos to the README by marking PPA as Ubuntu only in a hint targeted to Debian/Ubuntu users and adding a short paragraph for Debian users linking to the GitHub releases page.

Added more infos about installation on Debian to README

---

src/gui/inputdevices/TouchInputHandler.cpp

Fixes #2509.
After being annoyed at this bug for a long time and finally reporting it, I decided to poke around in the source and found the bug surprisingly easily. To me, that means that the code is well organised!
To be clear, the bug was that `zoomMotion` and `zoomEnd` were called even if zoom gestures were disabled. The existing check only prevented `zoomStart` from having any effect.

Don't try to zoom on two finger touches if zoom gestures are disabled

---

cmake/find/FindFilesystem.cmake
src/Xournalpp.cpp
src/control/Control.cpp
src/control/Control.h
src/control/XournalMain.cpp
src/control/XournalMain.h
src/gui/PageView.h
src/gui/toolbarMenubar/model/ToolbarColorNames.cpp
src/gui/toolbarMenubar/model/ToolbarColorNames.h
src/util/PathUtil.cpp
src/util/Stacktrace.cpp

Since this is a huge change and this change should be merged into the next release we need to test it well.
Here a suggested list what's to test:
- ~~All commands of the command-line-interface work.~~
- ~~All icons are still displayed.~~
- ~~Xournalpp starts.~~
- ~~everything works after installation~~
- ~~Plugins are loaded~~
- ~~Append this list if desired.~~
This may fix problems with icons.
It will use the config folder name xournalpp instead of com.github.xournalpp.xournalpp

Rewrite main to use the gtk3 initialisation instead of the deprecated gtk2 method

---

azure-pipelines/clang-format-applied.yml
azure-pipelines/release.yml
src/CMakeLists.txt

- fixed a bug, that prevented the creation of debug symbols on Windows
- fixed a bug, that no stacktrace is shown anymore
- fixed a small clang-format issue

Mini fixups to the CMake script and the CI

---

cmake/include/Version.cmake

Without this fix, builds fail if git is configured to show PGP signatures by default (the `log.showSignature` config option). Adding the `--no-show-signature` option disables the display of PGP signatures regardless of the user's git configuration.
Closes #2491

Add --no-show-signature option to git log commands during build

---

src/control/XournalMain.cpp

I had a segfault message due to the lack of nullptr at the end of the option array. See
[Gtk's documentation](https://developer.gnome.org/gio/stable/GApplication.html#g-application-add-main-option-entries):
`void
g_application_add_main_option_entries (GApplication *application,
const GOptionEntry *entries);`
>application: a GApplication
>
>entries: (array zero-terminated=1) (element-type GOptionEntry) a NULL-terminated list of GOptionEntrys
**Edit** Fixed link and added quote

Fix Segfault due to missing nullptr

---

src/control/XournalMain.cpp
src/control/jobs/CustomExportJob.cpp
src/control/jobs/CustomExportJob.h
src/control/jobs/ImageExport.cpp
src/control/jobs/ImageExport.h
src/gui/dialog/ExportDialog.cpp
src/gui/dialog/ExportDialog.h
src/util/PageRange.cpp
src/util/PageRange.h
ui/exportSettings.glade

Hey,
Here is a first commit implementing a --export-range=... option for the command line. It works as is but I have a question.
As this new option (obiously) uses the same backend as the ExportDialog, I also fixed a bug (not listed) making the ExportDialog fail to understand a page range of the form "n-" (from page n until the end). Now, there are two ways of handling such a page range:
1) Set the end of the range to -1 and implement this possibility in the export job
2) Set the end of the range to the number of the last page **when we parse the string**
I chose option 2 (it was simpler to implement, and I don't yet see a possible benefit of option 1). However, andreasb123, who implemented PageRange::parse (in [this commit](https://github.com/xournalpp/xournalpp/commit/2d412eec34f5cb2f21b …

Add command line export options

---

src/util/XojMsgBox.cpp

Fixes #2355 introduced in backport of #1989

[1.0.x] Fixup overwrite file in pdf export

---

src/control/Control.cpp

This commit changes the behaviour back to always using the last tool
selected at startup, rather then the default button Tool.
This fixes #2535.

Fix regression default tool at startup

---

src/gui/toolbarMenubar/ColorToolItem.cpp

This change removes code that was erroneously implemented but leads to a
nullptr being referenced in case no ColorToolItem is present in the
toolbar and a buttontool is activated that has no color capability.
This fixes #2533.
The code removed cannot be called in any case where it would not lead to a segmentation fault so removing it should not affect any functionality. It's actually kind of stupid :sweat_smile:

Fix segmentation fault for missing ColorToolItem

---

src/control/ToolHandler.cpp
src/control/ToolHandler.h
src/control/settings/ButtonConfig.cpp
src/control/settings/ButtonConfig.h

Fix the behaviour of "Don't Change" settings for the Buttons to use the corresponding Tool from the toolbar as reference.
This fixes #2521 .

Take toolsize and erasertype from corresponding toolbar tool when triggered by Button

---

debian/changelog

This updates the debian changelog, which will be used to set the version number for the stable PPA.

[1.0.x] Update debian/changelog

---

azure-pipelines/release.yml

Attempt to fix the failure of building the 1.0.20 debian release package
```term
CMake Error at CMakeLists.txt:3 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.```

fix debian release pipeline

---

plugins/LayerActions/main.lua
plugins/LayerActions/plugin.ini
src/gui/sidebar/Sidebar.cpp
src/gui/sidebar/Sidebar.h
src/plugin/luapi_application.h

This PR adds various new functions to the Lua Plugin API. Moreover a plugin is added for cloning all handwritten layers to the next page. 
The **new Plugin API functions** are:
- `app.sidebarAction` for actions accessible in the sidebar
- `app.layerAction` for actions accessible in the layer controller
- `app.changePdfBackgroundPageNr` to change the pdf background page number
- `app.getDocumentStructure` to get lots of useful info on the document, also used for applying operations on all/selected pages
- `app.scrollToPage`scrolls relatively or absolutely to a page
- `app.scrollToPos` scrolls relatively or absolutely to a new position on the same page
- `app.setCurrentPage` sets the given page as new current page
- `app.setPageSize` to set the size of the current page
- …

Extend the Lua Plugin API for page and layer operations

---

debian/package_description

This fixes the Debian package for version 1.0.20
The problem were the spaces at the end of lines (there shouldn't be any) and missing spaces at the beginning of lines starting from the 2nd line (including otherwise empty lines).

[1.0.x] hotfix for debian package

---

CMakeLists.txt
azure-pipelines/release.yml
debian/changelog
debian/control
debian/package_description

The manual page says:
>        Description: short-description (recommended)
>         long-description
>               The format for the package description is a short brief
>               summary on the first line (after the Description field).
>               The following lines should be used as a longer, more
>               detailed description. Each line of the long description
>               must be preceded by a space, and blank lines in the long
>               description must contain a single ‘.’ following the
>               preceding space.

[1.0.x] Fix all debian packaging errors

---

src/gui/dialog/SettingsDialog.cpp
ui/exportSettings.glade
ui/latexSettings.glade
ui/pageTemplate.glade
ui/settings.glade
ui/xournalpp.css

Trying to improve the presentation of the Settings dialog by adding a bit of margin,
make the "LaTeX" tab behave more like the other tabs, and make the labels of subsections more recognizable.

settings dialog styling

---

src/view/PdfView.cpp

Note: I have not checked the effect of this on printing yet. It helps with the issue mentioned in #2575, though.
xournalpp paints a white background behind the PDF even for export (but
nor for printing). It does so by painting it after the PDF is rendered,
specifying CAIRO_OPERATOR_DEST_OVER as the compositing operator to get
it below the PDF rendering. When rendering to a SVG 1.2 surface cairo
turns this into a comp-op:dst-over style.
So what's the problem? SVG 1.2 never got accepted as a standard, and
thus it is supported only partially. The resulting SVG does not even
work in inkscape.
Instead, render the white background first and avoid the compositing
operator. This dies not change the resulting image for png outputs but
helps to produce simpler svg.

avoid SVG 1.2 compositing operators

---

src/control/XournalMain.cpp
src/control/jobs/BaseExportJob.cpp
src/control/jobs/CustomExportJob.cpp
src/control/jobs/CustomExportJob.h
src/control/jobs/PdfExportJob.cpp
src/gui/dialog/ExportDialog.cpp
src/gui/dialog/ExportDialog.h
src/pdf/base/XojCairoPdfExport.cpp
src/pdf/base/XojCairoPdfExport.h
src/pdf/base/XojPdfExport.h
ui/exportSettings.glade

Enhancement proposal: see Issue https://github.com/xournalpp/xournalpp/issues/2373
In order to save all layers as separate pages, two options:
1. use "Save as..." in the File menu, select "PDF File" or "PDF File with plain background", and in the "Document export setting" dialog, check the box "Export all layers as separate pages"
2. use the command-line, as in 
`xournalpp -p output.pdf --export-layers file.xopp`

export layers in different PDF pages

---

src/control/LatexController.cpp
src/control/tools/EditSelection.cpp
src/control/zoom/ZoomControl.cpp
src/control/zoom/ZoomControl.h
src/gui/Layout.cpp
src/gui/Layout.h
src/gui/MainWindow.cpp
src/gui/XournalView.cpp
src/gui/inputdevices/AbstractInputHandler.cpp
src/gui/inputdevices/old/InputSequence.cpp
src/gui/scroll/ScrollHandlingGtk.cpp
src/gui/widgets/XournalWidget.cpp

Fixes #2138 (and its duplicates #1699 and #2066)
The cause of the problem was that for the users that reported the problem the allocation width that was passed to `updateZoomFitValue` did not match with the width of the visible rectangle, which made the zoomFitValue alternate in rapid succession between two different values, which invoked `XournalView::scrollTo` method to keep the top part of the current page visible (if the whole page did not fit on the screen).
It must be checked carefully if we don't reintroduce a bug (#1139, #1132 ) that has been fixed in #1213. So far it seems, it doesn't reintroduce these bugs.

Fixes zoomFitValue update hindering scrolling

---

src/gui/MainWindow.h

An uninitialized variable was sometimes true, sometimes false, leading to inconsistent initial disabling of Gtk scrolling.
Should address #2626.
See https://github.com/xournalpp/xournalpp/issues/2626#issuecomment-756122243 for a full description.

Fix regression touchscreen disabling sometimes broken

---

src/gui/widgets/XournalWidget.cpp

This PR reverts the changes to `minimal_width` and `minimal_height` made in #2613, that lead to regression #2631. Fixes #2631.

fix page rendering regression

---

src/control/Control.cpp
src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/control/tools/EditSelectionContents.cpp
src/control/tools/EditSelectionContents.h
src/undo/LineStyleUndoAction.cpp
src/undo/LineStyleUndoAction.h
src/undo/UndoAction.h
src/undo/UndoRedoHandler.h

I have often struggled with line styles, because they could not be modified after the strokes have been drawn. With this PR the line style of a whole selection is made modifiable similarly as for the color of a selection. See animation.

Make line style modifiable after drawing

---

src/control/XournalMain.cpp
src/control/jobs/BaseExportJob.h
src/control/jobs/CustomExportJob.cpp
src/control/jobs/CustomExportJob.h
src/control/jobs/ImageExport.cpp
src/control/jobs/ImageExport.h
src/gui/dialog/ExportDialog.cpp
src/gui/dialog/ExportDialog.h
src/pdf/base/XojCairoPdfExport.cpp
src/pdf/base/XojCairoPdfExport.h
src/pdf/base/XojPdfExport.cpp
src/pdf/base/XojPdfExport.h
src/view/DocumentView.cpp
src/view/DocumentView.h
ui/exportSettings.glade

The aim of this series is to allow exports without ruling but with the other backgrounds, since the former are often auxiliary only, but the latter are essential. If you have documents with mixed background types or batch process documents with different background types then the new `--export-no-ruling` option should come in handy.
The 1st commit is an independent but technically related bugfix (do not export PDF background to PNG when asked not to).
The 2nd commit marks an existing bug as TODO (PDF backgrounds are never exported to SVG). I don't know if you prefer to carry TODOs in code. A proper fix would be to render the PDF to an image cairo surface and attach the image to the SVG surface, which is over my cairo head, unfortunately.
The remaining commits address the actual purpose: …

Allow exports without ruling (but with other backgrounds)

---

src/gui/PageView.cpp
src/gui/toolbarMenubar/FontButton.cpp

Updates the font button in the toolbar when entering and leaving edit mode of a text filed. That makes is easier to change the font relative to how it was before. When leaving the edit mode of a text field the font is reset to the font last chosen in the dialog.
Also, the creation of the string to set the font shown by the toolbar button is made independent of locale settings. Before, e.g. German locale caused the string to be formatted with a decimal comma instead of a decimal point, which wasn't recognized by the button. Therefore closes #1051 and #1061

Update font-button when editing text, make it work locale-independent

---

src/gui/TextEditor.cpp
src/gui/TextEditor.h

This uses the same setting which is also used by the built-in text entry widget.

Allow the user to disable cursor blinking.

---

src/control/zoom/ZoomControl.cpp
src/control/zoom/ZoomControl.h

This adds zooming on a touchpad pinch gesture.
This doesn't seem to work when the touch workaround is enabled, I guess the events are handled somewhere else then. If someone is able to point me in the right direction, it would be nice :)
About some things I'm not quite sure, see review comments.

Add touchpad pinch gesture support

---

src/control/Control.cpp

When writing on 2 (or more) different pages between two refreshing of the page preview (5 seconds between two successive refreshing), only the first modified page gets its preview updated. 
This PR fixes that.

Fix page preview only updating one page

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/XournalView.cpp
src/gui/XournalView.h
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

This PR updates the page cache algorithm and adds a page preloading feature. Fixes #2412.
TODO:

Rewrite and improve page load caching algorithm

---

src/control/tools/CircleHandler.cpp

When drawing a circle from the center, it makes sense to put the edge of the circle wherever the cursor is, but the current implementation is to take the maximum of the width and height, which corresponds to the cursor only at the principal axes, and makes a smaller circle everywhere else.
Apologies if there's an issue or PR about this already, there were a lot about circles to look through!

Make circle go up to cursor when drawing from center

---

src/gui/XournalView.cpp

This just makes the hjkl keys emulate the arrow keys instead of having separate behavior that doesn't also work in presentation view.

make vim keybindings behave exactly like arrows

---

ui/main.glade

Moving the sidebar's close button to the top of the sidebar allows the user to make the sidebar smaller than previously possible, while moving the "close" button further from the delete button.
<center>
</center>

Move close button to top of sidebar

---

src/control/Control.cpp
src/control/Control.h
src/control/PageBackgroundChangeController.cpp
src/control/PageBackgroundChangeController.h
src/control/pagetype/PageTypeMenu.cpp
src/control/pagetype/PageTypeMenu.h
src/gui/dialog/PageTemplateDialog.cpp
src/gui/dialog/PageTemplateDialog.h
src/gui/toolbarMenubar/ToolMenuHandler.cpp

This PR fixes the confusing behavior of the `Apply to current/all pages` buttons. Fixes #951.
* Fixes a bug where the `Journal > Paper background` apply page type button would use the page type from the new page type dropdown. The fix is a bit hacky but it's simple and straightforward.
* Fixes a bug where the selected page type in `Journal > Paper background` would not update after using `Apply to all pages` from the new page type dropdown.
* Removes the confusing check mark next to the Apply to current / all pages button.
Merging in 48 hours if there are no objections.

Fix confusing behavior of "Apply [page type] to current/all pages"

---

src/control/UndoRedoController.cpp
src/control/tools/EditSelection.cpp
src/control/tools/EditSelectionContents.cpp
src/model/Image.cpp
src/model/Stroke.cpp
src/model/TexImage.cpp
src/model/Text.cpp

- Fixes #2720 
- Removes creating unnecessary undo actions
- Makes cloning of elements complete. This may have been the cause for elements with width and height 0 in #2464. So it might partially fix #2464.

Fix element cloning

---

CMakeLists.txt
readme/LinuxBuild.md
src/util/XojPreviewExtractor.h
src/xoj-preview-extractor/CMakeLists.txt
src/xoj-preview-extractor/xournalpp-thumbnailer.cpp

Fixes #1612.
Old behavior: crash during gtk initialization.
New behavior: emit warning message and render the thumbnail without the icon if the icon cannot be found.
The icon search code is not very comprehensive, but this is just a quick fix for the bug.

Use librsvg directly in thumbnailer to add icon to previews

---

src/control/LatexController.cpp
src/control/LatexController.h

fixes https://github.com/xournalpp/xournalpp/issues/2332 by aborting the render instead of calling an assert to crash the program deliberately.

fix crash when closing the latex dialog early

---

src/model/Snapping.cpp

This fixes a bug in the application of the grid snapping tolerance in horizontal and vertical direction. This is experienced when resizing a selection horizontally or verticalling.

fix snapping in horizontal/vertical direction

---

src/gui/sidebar/Sidebar.cpp
src/gui/sidebar/Sidebar.h
src/gui/sidebar/previews/base/SidebarToolbar.cpp
src/gui/sidebar/previews/base/SidebarToolbar.h
src/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp
src/gui/sidebar/previews/page/SidebarPreviewPages.cpp
src/gui/sidebar/previews/page/SidebarPreviewPages.h
ui/main.glade

This PR solves a few issues with the sidebar, some of which are only noticable if you have a document with bookmarks:
- sidebar is not initialised properly (toolbar shows up even if it should not)
- toolbar is not reenabled properly (if it was disabled and you switch to page preview)
- toolbar tooltips refer to pages even when they act on layers
As a sidebar fix, PR #2674 could go on top of this, but because of the concerns mentioned there I'll save it for later (when I implement another sidebar mode with stacked previews).

Layer preview fixes

---

src/control/jobs/PreviewJob.cpp

A PDF background lives in the background layer just like any other
background. In the sidebar layer preview, however, PDF backgrounds are
drawn for every layer; all other backgrounds (ruling, image) are drawn
for the background layer only.
Move the corresponding codeblock to drawPage() where all the logic is
about what to draw in the preview, and make it draw PDF backgrounds on
the background layer (and combined page view) only.
**Note**: If we can rely on -100 and -1 being the only negative layer values then `layer == -100 || layer == -1` can be simplified to `layer < 0`, of course.

Layer preview: show PDF background in background layer only

---

src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/control/tools/EditSelectionContents.cpp
src/gui/XournalppCursor.cpp
src/gui/XournalppCursor.h
src/model/Element.cpp
src/model/Element.h
src/model/Stroke.cpp
src/model/Stroke.h

fixes https://github.com/xournalpp/xournalpp/issues/2718
fixes https://github.com/xournalpp/xournalpp/issues/1440
Simplifies the edit selection logic. Then adds in the mirror functionality, but
just like `aspectRatio` is fixed for some objects, also `mirror` is fixed for some objects.
The handling of the corners is now linear for all cases. Before this PR it was non linear for the corners, resulting in weird behavior when the mouse is not exactly on the grabbed corner.
Also adjusted cursors to match the mirrored scale directions in the corners.

add EditSelection mirror functionality for strokes and images

---

src/gui/inputdevices/PenInputHandler.cpp

This should fix #1679. Previously, calls to `PenInputHandler::actionMove` would result in drawing even when not `PenInputHandler::inputRunning`. This is a bit of a workaround. 
`PenInputHandler::actionMove` probably shouldn't be called if we're not drawing/the pen isn't down!
This should also fix #2762.

Fix #1679 -- Pen activates after exiting page when using floating toolbar

---

src/control/LatexController.cpp
src/control/LatexController.h

fixes https://github.com/xournalpp/xournalpp/issues/2775
I was debating if I should let the current (outdated) render finish or, if I should abort it to start the updated render. In the end, after some testing, letting the outdated render finish feels smoother for the user. That also means there is this simple fix.

Fix LaTeX dialog threading for Windows

---

src/gui/MainWindow.cpp
src/gui/MainWindow.h
ui/main.glade

This works around what seems to be a bug in Gtk: Hiding the sidebar created a dead region (for stylus/touch) in which the GtkPaned widget ate horizontal gestures.
This prevented horizontal strokes from starting in this region!
This is fixed by putting the main window content in a GtkBox, rather than a GtkPaned, when the sidebar is hidden.
This should fix #2759.

Fix dead region when sidebar is closed

---

debian/control
readme/LinuxBuild.md

The PPA (for the latest master) does not build since February 4, 2021 because `librsvg-2.0` is missing. It is required for the thumbnailer. So we must ensure that the package gets installed.

Fix librsvg dependency

---

ui/main.glade

Some themes (e.g. Adapta) draw large buttons when their container is missing the `linked` style class.
**Before**
**After**
This should address https://github.com/xournalpp/xournalpp/pull/2727#issuecomment-776191629.
Note that while this decreases the size of the sidebar in some themes, adding the `linked` class slightly increases the size of the sidebar in others.
For example, with the Breeze GTK theme,
**After**
**Before**

Fix regression large sidebar buttons in Adapta theme

---

debian/control

I am not sure it fixes the problem, but I don't see a way to try it out without merging the commit, letting it build on Launchpad and trying out the package.
Since `librsvg` is only used for the thumbnailer an option would be to add this dependency only to the `Recommends` field.

fix deb package with non-satisfiable dependency

---

src/gui/Layout.cpp
src/gui/Layout.h
src/gui/PageView.cpp
src/gui/PageView.h
src/gui/XournalView.cpp

fixes https://github.com/xournalpp/xournalpp/issues/2703
The fix was to make layout calculate the page height/width with double precision, because otherwise on page N a random error of ~N/2 would have been accumulated.
~~I also refactored some of the space conversion code to be less error prone to double-precision-errors. Also with the old code I noticed, that when zooming with the mouse on the last page, it would randomly jump to prior pages. That is fixed with the refactor. I did test a lot of things, but I am sure I left something untested, so testing is highly encouraged!~~
~~If requested I can split this PR into the refactor/jump fix and the jitter fix as they are mostly separate in code.~~
**Edit:** This PR got split.

Fix Zoom Jitter

---

resources/default_template.tex

% is required at end of line for some TeX commands. Without it, redundant space is inserted.

Remove redundant space from TeX object

---

src/view/background/BackgroundConfig.cpp
src/view/background/BackgroundConfig.h
src/view/background/BaseBackgroundPainter.cpp
src/view/background/BaseBackgroundPainter.h
src/view/background/DottedBackgroundPainter.cpp
src/view/background/GraphBackgroundPainter.cpp
src/view/background/GraphBackgroundPainter.h
src/view/background/IsometricBackgroundPainter.cpp
src/view/background/LineBackgroundPainter.cpp
src/view/background/StavesBackgroundPainter.cpp

This adds configurable alternative foreground colors to "pagetemplates.ini" to all views which are used if the background is darker than middle gray. #2055 did this for the graph view, however it also stopped configurable foreground colors from working specifically on that view. This is very similar to #2061, except that the color switching is more generalized.
I'm not exactly sure if this is the best solution though since pagetempletes.ini does simply allow you to add a dark version of the page manually. I'm personally not a fan of manually needing to configure a config file though which is also fairly hidden from the user.
This also prevents the foreground from becoming invisible, e.g. in the staves background, the foreground is a solid black and will become invisible if the same color …

Automatically switch foreground color based on background color

---

src/util/Rectangle.h

Intersection of rectangles was not computed properly. This fixes it.
Example: `{1, 0, 1, 0}.unite({0, 0, 1, 0})` resulted in `{0, 0, 1, 0}` instead of `{0, 0, 2, 0}`.

Fix Rectangle::unite not properly calculating the union

---

src/util/PathUtil.cpp

The searchpath separator under Windows is not `:` like on Linux/Unix, but `;`
To distinguish OS's we can use the `G_SEACHPATH_SEPARATOR` variable, see [this link](https://developer.gnome.org/glib/stable/glib-Standard-Macros.html#G-SEARCHPATH-SEPARATOR:CAPS).

Make TEXTDOMAINDIR work under Windows

---

src/control/xml/TextAttribute.cpp

On file load, linebreaks in XML attributes are ignored. Linebreaks were not escaped on file save. This PR escapes linebreaks on file save. 
This should be backwards compatible because we use a `GMarkupParseContext` to parse XML (on file load), which handles escape sequences for us.
Should fix #2526.

Escape linebreaks when saving LaTeX text

---

src/gui/TextEditor.cpp
src/gui/TextEditor.h

This PR deals with the attributes for preedit strings of IM.
1. Fix that attributes were not reflected.
2. Use attributes for the preedit strings set by IM.
**On the first point**
Seeing TextEditor.cpp, IM's preedit strings are to be displayed with underline.
But subsequent code for attributes of selections overrides it, and no underline appears.
Because TextSelection and PreEditingTexts are exclusive operation, there's no needs to compose their attributes.
So I moved the TextSelection code to PreEditing code's else clause.
**On the second point**
There are various IM programs, and they set attributes for preedit strings.  So Xournal++ should not set attributes for preedit string, but use IM's attributes. The PR uses only  IM's attributes, and does not intend to compose them with other …

Fix attributes of IM's preedit strings in TextEditor.

---

debian/control
plugins/MigrateFontSizes/dialog.glade
plugins/MigrateFontSizes/main.lua
plugins/MigrateFontSizes/plugin.ini
readme/LinuxBuild.md
src/plugin/luapi_application.h
src/view/TextView.cpp

This PR replaces PR #2182. 
It does not take care of line spacing in pdf export (for which we would need Pango's `pango_layout_set_line_spacing` to work correctly). 
Currently the plugin will derive the scaling factor from the display dpi setting (in the zoom panel of the preferences). This will usually be the correct choice, but it is not if the user has changed his display dpi setting since he created the document. So I think a display dpi that can be set from the GUI should be included. This could be done either by adding a GUI element in the Lua plugin API or by creating the GUI element in the plugin using the `lgi` module. In the latter case it may make sense to add the `lgi` module to the project. It is always needed when creating a non-trivial GUI.

Fix font size dpi scaling bug and search mark bug and add a plugin for migration of font sizes

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/tools/InputHandler.cpp
src/control/tools/InputHandler.h
src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h
src/control/tools/StrokeStabilizer.cpp
src/control/tools/StrokeStabilizer.h
src/control/tools/StrokeStabilizerEnum.h
src/gui/dialog/SettingsDialog.cpp
src/gui/dialog/SettingsDialog.h
src/model/SplineSegment.cpp
src/model/SplineSegment.h
src/model/Stroke.cpp
src/model/Stroke.h
src/util/CircularBuffer.h
ui/settings.glade

This follows up on #2320.
I implemented basic support for smoothing algorithms, as well as a a version of Gimp's smoothing algorithm (see #2320 for more details on this algorigthm). You can see the results in the following gifs (no smoothing vs Gimp's smoothing).
This is pretty rudimentary and there is no GUI control for now. To try out the smoother, you need to use --smoothing=GIMP in your command line. There are two parameters you can tweak: 
- A (double) coefficient sigma (through --smoothing-sigma=0.2 for instance). In the first gif, it was set to 1, in the second gif, it was set to 2.
- The size of the buffer used by the algorithm (through --smoothing-buffer-size=20). In the examples above, I let to 20.
[You can also try out --smoothing=ARITHMETIC which is fun but not very useful] …

Support for input stabilizing

---

src/control/zoom/ZoomControl.cpp
src/control/zoom/ZoomControl.h

This fixup introduces a check, whether the old selected page is still visible, only if not, the new zoom_to_fit value is calculated.
This has the drawback, that it defers the zooming to the page size until the old page is not visible anymore.
fixes #2770

Fixup Zoom loop, when using 2 different page sizes

---

src/control/settings/Settings.cpp

Should fix #2854
Due to the definition of `WRITE_INT_PROP`, the property name for `stabilizerAveragingMethod` and `stabilizerPreprocessor` included a `static_cast&lt;...`

Settings not saving: Fix stabilizer averaging method and preprocessor settings

---

src/control/Control.cpp
src/control/jobs/PreviewJob.cpp
src/control/jobs/PreviewJob.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
src/gui/sidebar/previews/base/SidebarPreviewBase.cpp
ui/xournalpp.css

Fixes broken selectors in `xournalpp.css` and changes applied styles when in dark mode.
* When in dark mode (i.e. using a dark Gtk theme), the page preview background would still be white
-  This led to low text contrast (layer titles). For example, below, the word "Background" is difficult to read.
-  The preview pane's background is now styled with CSS, rather than filled with Cairo.
* `xournal.css` was using selectors including `GtkButton` and `GtkWindow` that seem to no longer match parts of the page. For example, `GtkButton { color: red; }` wasn't changing the color of text in buttons. 
-  These have been replaced with `button`, `window`, etc. selectors. 
- This changes the selectors such that they match those used in [the GTK+ CSS …

Better dark mode: Fix & improve CSS styling

---

azure-pipelines/steps/build_windows.yml

Fixes #2601 by updating MSYS2 to include mingw-w64-x86_64-cairo-1.17.4-2 instead of mingw-w64-x86_64-cairo-1.17.4-1.
I just checked running the msys2-blob to check if the Cairo version gets really bumped to 1.17.4-2 (it does). 
**Edit:** The continuos integration pipeline shows the same result. The downside is, that it take about 15 minutes longer to build on Windows.
**Edit2:** I now replaced `pacman -Syuu` (twice) by `pacman -Sy` (once) to only update the package index without a full system upgrade.

update msys2 to get cairo 1.17.4-2

---

rpm/fedora/xournalpp.spec

This spec file is set for daily snapshot with very minimal maintenance. The comment is added to describe the purpose. The benefit is bringing more Fedora testers to find possible bugs and test improvement. The only change is `version_string` set for development release i.e. 1.1.0.

Daily snapshot release for Fedora

---

src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h

This is another proposal to fix #2858. See also #2859
Feel free to delete this if #2859 is favored.
[This also solve the (yet theoretical) issue about averaging with Point::NO_PRESSURE mentioned in [this post](https://github.com/xournalpp/xournalpp/pull/2859#issuecomment-784893294)]

Fix highligher initial rendering

---

ui/main.glade

Fixes #2754.
Added shortcut "Ctrl+Shift+D" for the default tool, which makes it accessible by keyboard.
I know that it's also possible to write a plugin for it, but imo this makes the UI more consistent since the majority of other tools(pen, eraser, etc) also have shortcuts, and if the default tool is considered important/popular it should have a built-in shortcut as well.
The only other main tools left that don't have shortcuts are: "Play Object" and "Record/Stop".

added shortcut for default tool

---

src/control/jobs/PreviewJob.cpp
src/control/jobs/PreviewJob.h
src/gui/sidebar/Sidebar.cpp
src/gui/sidebar/previews/base/SidebarPreviewBaseEntry.h
src/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.cpp
src/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.h
src/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp
src/gui/sidebar/previews/layer/SidebarPreviewLayers.h
ui/icons/hicolor/scalable/actions/sidebar-layerstack.svg

Here is the follow-up to PR #2674.
Things to note in addition to the commit messages:
- The existing layer preview shows layers irrespective of the "active" check-box (which is useful); I kept this behaviour.
- The new sidebar icon uses some screen real estate that - until a few days ago - was unused anyways. I still think both the sidebar "page" (tab) icon and the close box belong there.
- The technical implementation makes it easy to use a checkbox instead of a new sidebar tab.

Layer preview stacked

---

desktop/com.github.xournalpp.xournalpp.desktop

Fixes #1791
Under Ubuntu (20.10) the StartupWMClass is also needed to avoid duplication of the icon in the dock and to add a running Xournal++ to the favorites.

add StartupWMClass to desktop file

---

src/gui/TextEditor.cpp
src/gui/TextEditor.h

When InputMethod makes external window separate from the Xournal++'s one,
IM needs cursor position of Xournal++ to determine where to open the window.
Current Xournal++ doesn't notify the IM of the cursor position, so the IM window
is displayed at unexpected place.
For example, if I use uim-skk (IM) on dual monitor environment, the candidate
window is displayed on a monitor different from the monitor on which Xournal++
is displayed. This is very stressful.
This PR makes Xournal++ to notify the IM of the app's window and cursor position. 
To be precise, the cursor position is not the one Xournal++ has a mark (just after preedit string),
but the one somewhere in the preedit text which is indicated by IM. The following
movie shows how the candidate window of ibus-anthy is displayed. …

Notify the IM of its cursor position in Xournal++

---

azure-pipelines/continuous-integration.yml
azure-pipelines/release.yml

- macOS 10.13 High Sierra is EOL
- it prevented progress, regarding many c++17 features
- c++20 is released and c++23 knocks on the door

Dropped support for macOS 10.13 High Sierra

---

src/control/jobs/SaveJob.cpp

This PR fixes #2883
After the fix:
Backup will be created for the filepath that will be written to while saving.
Note backup here means aka. moving to `filename` + `~`.
Before the fix this was not always the case as non `.xopp` extensions where overwritten to `.xopp` upon saving, but only after the backup was already created for to original filepath.

Fix Backup on Save Mechanism

---

src/control/LatexController.cpp
src/gui/dialog/LatexDialog.cpp
src/model/TexImage.cpp
src/view/DocumentView.cpp

Most of the issues: `poppler_document_get_page()` results were not `g_object_unref`ed.
Others:
* Process object wasn't unref'ed in `LatexController`
* On LaTeX dialog close, a null `GCancellable` object pointer could be unreffed, causing a warning.
* `TexImage::clone()` set its clone's `pdf` pointer to its own PDF pointer, without increasing its reference count.

Fix several LaTeX-dialog-related memory bugs

---

src/control/jobs/BaseExportJob.cpp

- replaced `fs::equivalent` with 2 more robust calls to `fs::weakly_canonical`
- catches an error on failure.

Fix Crash on permission failure

---

src/CMakeLists.txt

This change fixes broken manual Windows build in which the application icon is created in a location other than the one pointed to by the resource file..

Fixed Windows build

---

src/gui/toolbarMenubar/ToolZoomSlider.cpp

Fixes #2923. 
The problem was that the `zoom100Value` is only 1, if the `displayDpi` is set to 72.

fix zoomSlider scale marks

---

man/CMakeLists.txt

This PR should fix the failure of building the PPA packages on Launchpad.
The problem lies in the DEPENDS field in the man page generation: 
``` 
make[4]: *** No rule to make target '../build/src/xournalpp', needed by 'man/xournalpp.1.gz'. Stop.
``` 
The assumption that the `CMAKE_BINARY_DIR` is the `build` subdirectory of the `CMAKE_SOURCE_DIR` does not need to be valid

Correct wrong assumption on location of build dir

---

src/plugin/luapi_application.h

The correct way to start a sidebar action is with `app.sidebarAction(...)`, not `app.sidebar_Action(...)`.

Fixed a small typo in Lua API documentation

---

src/plugin/luapi_application.h

In one of the two given examples the name of the function was correct, in the other it was `scrollToPage` rather than `scrollToPos`.
Let me know if these PRs are too silly.

Typo in Lua API documentation for scrollToPos

---

src/control/jobs/Job.cpp
src/control/jobs/Job.h
src/control/jobs/PreviewJob.cpp
src/control/jobs/PreviewJob.h
src/control/jobs/Scheduler.cpp
src/control/jobs/Scheduler.h
src/control/jobs/XournalScheduler.cpp
src/control/jobs/XournalScheduler.h

* A minor scheduler refactoring to use `std::deque`, `std::mutex`, and `std::condition_variable`.
* Fixes a crash on scrolling through long PDFs with the sidebar layers preview open.
* The crash was caused by a `nullptr` (or, possibly sometimes not, we weren't using a `std::atomic` to sync the object that was set to null between threads, but it **did** involve accessing freed memory) de-ref in `PreviewJob.cpp`.  
* I think a part of this was not waiting for preview jobs to finish, possibly freeing the SidebarPreview (that PreviewJob uses) before letting PreviewJobs finish running.
Fixes #2887.
See also #2907.

Fix crash on scroll with sidebar preview open

---

CMakeLists.txt
src/gui/inputdevices/touchdisable/TouchDisableX11.h

This was tested on a libX11-less wayland linux and another linux system with X11+Wayland.

CMake: Make X11 an optionnal dependency

---

ui/settings.glade

Remove confusing label from settings: "Requires new input system" no longer relevant

---

ui/main.glade

This is a proposition to change the` Ctrl+Del` shortcut for page deletion to `Ctrl+Shift+Del` to not interfere with text editing shortcuts according to #2679 .
The same was done for `Ctrl+Shift+Left` --> `Shift+PageDown`,  ` Ctrl+Shift+Right` --> `Shift+PageUp`  (see #2755). 
I don't mean to change the shortcut rationale randomly, please comment and I will change the PR as requested.

Changed shortcuts for page deletion and layer navigation

---

src/control/Control.cpp
src/control/PrintHandler.cpp
src/control/PrintHandler.h

PrintHandler uses now the actual GtkWindow.
PrintHandler is now more verbose and implements error handling.
Might fix #2974 
Effects #2995

Cleaned up PrintHandler - made more verbose - set parent

---

src/control/Control.cpp
src/enums/generateConvert.php
src/enums/generated/ActionGroup.generated.cpp
src/enums/generated/ActionType.generated.cpp

Fixes a crash reported in https://github.com/xournalpp/xournalpp/issues/919#issuecomment-821897950 resulting from wrong action type or group names, than can be called from a plugin.

avoid crash from wrong action group/type spelling

---

resources/legacy_template.tex
src/control/settings/LatexSettings.h

Fixes #2206 by adding a legacy LaTeX template, which works on older TeX distributions, that don't have the scontents package (which is needed for things like syntax highlighting via the `lslisting` package and other things that require verbatim inclusion of LaTeX formulas)
Fixes #3048 and fixes #1723 by adding the path to the pdflatex binary for MacOS (where the PATH environment variable is not passed to GUI applications when launched from GUI).

Fix latex problems

---

src/control/settings/Settings.cpp

The comments for `scrollbarHideType` and for new pages are misplaced in
`settings.xml`, for two different reasons: comments arise as nodes
attached to the node which they comment on in the tree but are output
before the node in a textual representation. Therefore, the code
generating the tree can generate a node comment only after the node it
comments on (1st reason). The usage of macros hides this fact, so when
you circumvent the macros you have to assign the node variable manually,
or else the comment will be attached to the wrong node (2nd reason).
Fix both.

fix settings comments placement

---

src/control/tools/EditSelection.cpp
src/control/tools/EditSelectionContents.cpp

Update EditSelection::sourcePage on mouseUp.
As far as I could tell this should be the expected behaviour.
This also partially fixes #3047.
Though reconstructing the new Selection on a new page is still broken.

Fix EditSelection page reference

---

src/gui/ToolitemDragDrop.cpp
src/gui/ToolitemDragDrop.h
src/gui/XojColor.cpp
src/gui/XojColor.h
src/gui/dialog/toolbarCustomize/CustomizeableColorList.cpp
src/gui/dialog/toolbarCustomize/CustomizeableColorList.h
src/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
src/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp
src/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.h
src/gui/dialog/toolbarCustomize/ToolbarDragDropHelper.cpp
src/gui/dialog/toolbarCustomize/ToolbarDragDropHelper.h
src/gui/toolbarMenubar/AbstractToolItem.h
src/gui/toolbarMenubar/icon/ToolbarSeparatorImage.cpp
src/gui/toolbarMenubar/icon/ToolbarSeparatorImage.h
src/gui/toolbarMenubar/model/ToolbarEntry.cpp
src/gui/toolbarMenubar/model/ToolbarEntry.h
src/gui/toolbarMenubar/model/ToolbarItem.cpp
src/gui/toolbarMenubar/model/ToolbarItem.h

This PR fixes multiple memory allocation bugs in the toolbar customizer.
* Fix double free when closing toolbar customization dialog.
* Fix separator icon not being rendered correctly when dragging to the toolbar.
* Fix errors involving the tool icons being left as floating references
* Refactor some of the toolbar customization code
There is a still a lingering issue where dragging & dropping a toolbar item may occasionally not trigger a redraw of the customization dialog.

Fix multiple memory bugs in toolbar customization

---

azure-pipelines/steps/build_windows.yml

Removing the updating of the package index like in this PR works, as my test on my personal dev.azure pipeline shows, and it does now uses Cairo 1.17.4-2. This is needed to have good pdf exports. So I suggest to merge this PR. From [the pipeline](https://dev.azure.com/rolandlo/xournalpp/_build/results?buildId=51&view=logs&j=5502ea34-1a31-5d2e-665e-0754f4413bc7&t=4d4fe241-2267-54df-e534-736dc4ac6f29):
```
downloading mingw-w64-x86_64-cairo-1.17.4-2-any.pkg.tar.zst...
```

Fix Windows Azure Pipeline

---

src/gui/toolbarMenubar/ToolPageSpinner.cpp
src/gui/toolbarMenubar/ToolPageSpinner.h
src/gui/widgets/SpinPageAdapter.cpp
src/gui/widgets/SpinPageAdapter.h

Fixes #3114. I've only tested this on Linux but I believe it should also work for Windows.

Fix null pointer dereference when no page spinner is used

---

src/control/settings/Settings.cpp

Set the default binding of the middle mouse button to 'hand tool' as proposed in #1594

Set default binding of middle mouse button to hand tool

---

src/control/zoom/ZoomControl.cpp
src/control/zoom/ZoomControl.h

Fixes #3036. This is a **temporary** fix for the infinite recursing zoom fit issue so that users of 1.1.0 won't get crashes. A quick run with the test file provided in #3036 suggests that the infinite recursing issue is caused, in part, by jumpy/nonlinear scrolling during the zoom (which should be improved by #2837).

Temporary hotfix for zoom fit loop

---

src/control/Control.cpp

Fix #2646 by mentioning the missing pdf name and its parent path.

show full path in error dialog box when background pdf is not found

---

src/view/TextView.cpp

This short PR aims to fix ~two annoying (high priority) bugs and another (yet unreported) minor bug~ the following bug:
- line spacing bug, leading to different results in screen view and pdf export of text elements:#1390,  #2073, #2104 (and #25)
The following bugs, that were previously part of this PR, have already been addressed in #2724
- dpi scaling bug, leading to different text size with different dpi settings: #1118
- search mark bug, leading to search marks that are one character too long (unreported)
The bugs are all easy to reproduce and the results can be compared with the fixed version. For instance take the following zip-file, consisting of a xopp-file with its pdf-export:
[TextLinesOfIncreasingSize.zip](https://github.com/xournalpp/xournalpp/files/5111212/TextLinesOfIncreasin …

Make line spacing be the same in export and on screen

---

azure-pipelines/steps/build_mac.yml

The GTK blob for MacOS is now split into 5 parts. In the pipeline, these parts are all downloaded and then extracted together.

curl split archive

---

src/gui/TextEditor.cpp

This commit fixes #3071. 
Before the change, using `pango_layout_get_attributes` meant that the previously selected text's changed background color persisted even when it was unselected. Now its working as expected.

fix text selection bug (#3071)

---

src/gui/inputdevices/StylusInputHandler.cpp

This reverts commit e442d57eb2312a91eeb4849f27c66e7b25eb1894.
In my opinion the cure was worse than the disease. Some users couldn't write any more, because strokes were ended suddenly. On Windows there were problems with stylus buttons as well. So I think it is better to revert this commit and wait for the more careful approach of #3039 to solve the issues addressed in that commit.

Revert "handle buggy driver events better to avoid vanishing lines"

---

README.md
debian/control
desktop/com.github.xournalpp.xournalpp.appdata.xml
package_description

We have four variants of a package description in Xournal++
1. the one from the `package_description` file
2. the one in the `README.md`
3. the one in `debian/control`
4. the one in the `com.github.xournalpp.xournalpp.appdata.xml` file (that is used for the `flatpak`). 
I streamlined them and made them all equal up to formatting details. I have also updated the appdata xml-file to some degree.
The appdata xml-file refers to four images, which are already seven years old, i.e. pretty outdated. We should create new images, that show how Xournal++ looks now and what we can do with it now.  Has anybody a nice .xopp-file that could be used to create such an image?
I think we need at least:
- an image for notetaking, maybe with multiple layers
- an image for PDF-annotation
- an image for using …

Streamline package descriptions and update appdata xml

---

ui/main.glade

This patch consists of 9 capitalization fixes scattered around various menus. I fixed them using Glade, so it also switched around the order of a few properties in the XML. I think that's just due to a Glade update, and will have no effect on the UI.

Fix capitalization in menus

---

windows-setup/xournalpp.nsi

This PR sets the working directory of the start menu link for Xournal++ to be the bin subfolder of the installaioin folder. This makes "../share/locale" point  to the correct locale directory.
It only works for launching Xournal++ from the start menu. It does not work from the context menu of a xopp-file or when running Xournal++ from terminal, when the present working directory is not the bin subfolder of the installation directory.
An alternative would be to use the TEXTDOMAINDIR environment variable or to use the execution path or maybe some resource path.
**Edit:** Fixed some typos

fix working directory for Windows start menu entry

---

src/control/Control.cpp
src/control/Control.h
src/control/RecentManager.cpp
src/control/RecentManager.h
src/control/XournalMain.cpp
src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Implements #3020.
I'm open for improvements as it is my second PR for a c++ project.
Changes on the settings dialog could be adjusted to be a completely new container to not touch existing things but i though it makes sense to put this setting and autoloading journal (pdf) into the same container.

Add open most recent document on application startup

---

src/control/Control.cpp

This commit does the following:
If one were to enable journal autoloading (Edit -> Preferences -> Load/Save -> Autoloading Journals)  and if the xournalpp file corresponding to `<name>.pdf` were named `<name>.xopp`, `<name>.xoj`,  `<name>.pdf.xopp` or  `<name>.pdf.xoj`, then loading the pdf would autoload the xournalpp file as well. 
Previously it autoloaded only `<name>.pdf.xopp` and `<name>.pdf.xoj`. The default save file name is `<name>.xopp` for the latest build, so it would be good if the xournalpp file with that name autoloaded too.

fix no autoloading journal for "filename.xopp" and "filename.xoj" problem

---

src/util/XojMsgBox.cpp

This is a solution to one of the issues mentioned in #3104. The reason why the message box was empty was because `g_markup_escape_text()` wasn't called on the message strings before passing it to `gtk_message_dialog_set_markup()`.
Before:
After:

 Fix some blank messageboxes that shows no context except the 'OK' button

---

src/util/XojMsgBox.cpp

The website is already more complete than the user manual and it links to the user manual, so I suggest to direct help seeking users to the website [help page](https://xournalpp.github.io/community/help/) and not to the user manual any more.

Update the web link in menu help > help

---

CHANGELOG.md

This is  #2839 squashed and rebased. While fixing the merge conflict I added the (second last) line about fixing the BigSur startup crash and removing the integration into the Mac menu bar.

Update changelog to prepare for 1.1.0

---

desktop/com.github.xournalpp.xournalpp.appdata.xml

I have updated the AppStream metadata to satisfy all of the following tests:
- `appstream-util validate com.github.xournalpp.xournalpp.appdata.xml`
- `appstream-util validate-relax com.github.xournalpp.xournalpp.appdata.xml`
- `appstreamcli validate com.github.xournalpp.xournalpp.appdata.xml`
- `flatpak run org.freedesktop.appstream-glib validate com.github.xournalpp.xournalpp.appdata.xml`
See also https://freedesktop.org/software/appstream/docs/chap-Metadata.html
and https://github.com/flathub/flathub/wiki/App-Requirements#Appstream
for the requirements

Update appdata screenshots and avoid deprecated mimetypes tag

---

src/control/Control.cpp
src/control/LatexController.cpp
src/control/ScrollHandler.cpp
src/control/jobs/ImageExport.cpp
src/control/jobs/RenderJob.cpp
src/control/jobs/SaveJob.cpp
src/control/layer/LayerController.cpp
src/control/tools/EditSelection.cpp
src/control/xojfile/LoadHandler.cpp
src/gui/MainWindow.cpp
src/gui/PageView.cpp
src/gui/dialog/backgroundSelect/PdfPagesDialog.cpp
src/gui/sidebar/indextree/SidebarIndexPage.cpp
src/gui/toolbarMenubar/FontButton.cpp
src/gui/toolbarMenubar/ToolPageLayer.cpp
src/model/Document.cpp
src/undo/GroupUndoAction.cpp
src/undo/InsertDeletePageUndoAction.cpp
src/undo/InsertLayerUndoAction.cpp
src/undo/PageBackgroundChangedUndoAction.cpp
src/undo/RemoveLayerUndoAction.cpp

My first contribute to a c++ project - hopefully quiet some "useful".
Only changed places which seem to be local variables and were using wrong type. 
My IDE (Clion - JetBrains) does no longer complain about incorrect type of these variables, building works and application was tested for some minutes with different tasks including wacom tablet.
If my contribution is ok for you i could also try to do more major stuff like easy issues or fixing some of the other implicit type conversions. 
For me as beginner to this project it is quiet strange why page-related variables (count, current page id etc.) are (signed) integer instead of size_t which should be on all common plattforms at least that big like int and will show any errors/tips in IDEs.

Fix simple implicit type conversions

---

src/control/tools/StrokeHandler.cpp

This follows up on the discussion started in [this post](https://github.com/xournalpp/xournalpp/pull/2729#issuecomment-885898684) about how something in #2729 improves the fluidity of strokes under macOS. 
@rolandlo Could you try out those two commits and tell me if the improvement is still there?
It should work with the second commit, but I also hope it works with the first...
(with the second commit, some features will not work. Some functions are just dummies so that it compiles)

Try to find out what improved macOS behaviour in #2729

---

src/enums/generateConvert.php

* Makes `generateConvert.php`'s output match the current contents of the `*.generated.cpp` files.

generateConvert script: Change «, » to "

---

windows-setup/build-portaudio.sh

Portaudio has been updated to version 19.7 on April 6, 2021, see http://files.portaudio.com/download.html. On MS Windows Portaudio is built from source in the build process and the build script downloads from a hard-coded tar-ball filename. I have updated the filename and the corresponding checksum.

Update Portaudio to version 19.7 on MS Windows

---

src/gui/XournalppCursor.cpp

Also, this function call should be obsolete, since it will be called by gtk after each drawing cycle.

Remove X11 callback to flush the X11 context, which happens way too often

---

src/control/layer/LayerController.h
src/gui/dialog/RenameLayerDialog.cpp
src/undo/LayerRenameUndoAction.cpp
src/undo/LayerRenameUndoAction.h

Fixes #3257. Since nobody touched that issue in a few days, here's a PR with what I suggested there.
1. There was an definite error in the undo/redo logic, simple fix.
2. For the correct change to properly reflect in the UI, I figured calling `fireRebuildLayerMenu()` would be good, so we give the undo action a `LayerController*` as  well and let it reach in there when it need to. (Seems fine?)

Fix undo layer rename

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/control/tools/EditSelection.cpp
src/control/tools/EditSelection.h
src/gui/dialog/SettingsDialog.cpp
src/gui/inputdevices/KeyboardInputHandler.cpp
ui/settings.glade

This PR is a hack for fixing #2889. Currently a proof of concept.
In particular, this replaces the hacky edge panning logic with less terrible (but still bad) timer-based logic: instead of scrolling to "ensure that the selection is visible," the logic has been changed to "scroll up/down at a fixed speed when the selection is slightly out of visible page bounds"
As a workaround for jitter and teleporting, panning will block the next mouse movement from causing the selection to move. The teleportation is fixed entirely, while the jitter is reduced by a significant amount (there is still some present but it is only barely noticeable).

Fix panning speed when selection is on the edge of the screen

---

src/gui/MainWindow.cpp

This should fix #2764 and #3278.
<strike>**Note that, at present, this PR selects the theme that matches the icon theme, even if the user has not checked/unchecked 'dark mode' in settings.** I think this is reasonable behavior -- otherwise, we end up with difficult-to-see icons, but could be seen as a breaking change. </strike> (The dark mode toggle no longer just changes the icon theme and Xournal++ now uses its own icons in place of the system's).
**Potential issues**
* The default GTK theme must also have a dark variant installed.
**Edit:** Xournal++ now uses its own icons by default, making earlier issues mentioned here no longer relevant.

Automatically request dark/light GTK theme based on "use dark theme" settings option

---

src/control/jobs/RenderJob.cpp

Stops the 'PDF background missing' warning text from being shown when a
transparent background image is used. Fixes #3185.

Fixed 'PDF background missing' text showing

---

src/view/StrokeView.cpp

Fix #2904
This is a quick fix. Some refactoring of `StrokeView` would also be beneficial to improve the logic, optimize and reduce the computational cost, but that'd require more work and goes beyond the scope of this simple bugfix PR.

Fix inconsistent display of filled highlighter strokes

---

AUTHORS
src/control/XournalMain.cpp

Following #470 and #530, this PR extends the input method check to cover any input method that is not ibus.
In my case, I'm using `gcin`, an input method for Traditional Chinese. This is not covered in the current check, so xournalpp crashes every time I try to add some text to my pdf documents. My change will make the check more comprehensive than checking only against `xim`.
Edit: checking against `xim` and `gcin` only now.
```
$ echo $GTK_IM_MODULE
gcin
$ ./src/xournalpp
** Message: 18:15:22.754: TEXTDOMAINDIR = (null), PACKAGE_LOCALE_DIR = /usr/local/share/locale, chosen directory = /usr/local/share/locale            
** (xournalpp:18484): WARNING **: 18:15:22.754: Unsupported input method: gcin, changed to: ibus                                                      
ALSA lib …
```

Extend input method check for gcin

---

src/control/jobs/SaveJob.cpp

This PR removes .pdf, .xopp and .xoj extensions (if any) and then appends xopp to the filename, rather than the simple replace_extension that was happening previously (because of which the text after the last dot in the filename was lost, as replace_extension used to replace that text thinking it was the extension).
Old code (in `SaveJob::save`)
```cpp
fs::path const filepath = doc->getFilepath();
auto const target = fs::path{filepath}.replace_extension(".xopp");
```
New code:
```cpp
fs::path filepath = doc->getFilepath();
Util::clearExtensions(filepath, ".pdf");
auto const target = fs::path{filepath}.concat(".xopp");
```

Fixed #3330: Allow characters after final dot in filename

---

src/gui/sidebar/Sidebar.cpp
src/gui/sidebar/Sidebar.h

* Hides, rather than disables, the "contents" tab in the sidebar when the tab would be empty
* This saves space in the tab area at the top of the toolbar

Hide, rather than disable, contents tab when unavailable

---

src/CMakeLists.txt
src/Xournalpp.cpp
src/win32/console.cpp
src/win32/console.h

I have noticed that the Windows build uses `AllocConsole` at Xournal++ startup to prevent `gspawn-win64-helper` from creating its own console popups, for example when rendering LaTeX. However, this makes the console window flash briefly on the screen, which is annoying especially in tablet mode. When you launch Xournal++ (using the start menu or by opening a file associated with it), a console window is opened and then hidden immediately.
In tablet mode, there is no classic desktop, instead a full-screen start menu is displayed when no window is in the foreground. This means that after hiding the console window, the screen drops back to the start menu. Then the actual Xournal++ GUI is opened in the background and you must switch to it by tapping its icon in the task bar.
Unfortunately …

Remove console window flash at startup on Windows

---

src/gui/inputdevices/TouchInputHandler.cpp

The spacing compensation was added to the zoom center in touchInputHandler and in ZoomControl when starting a touch pinch gesture. This caused the pinch to zoom gesture to not be centered on the zoom origin when using vertical/horizontal spacing.
This PR simply removes the duplicated offset compensation from the touchInputHandler since it's already handled by the generic zoom controller.

Fix touchscreen zooming when using vertical/horziontal spacing. Fixes #3298

---

src/undo/SizeUndoAction.cpp

A variable was named orignalWidth, its name is corrected to
originalWidth.

(minor fix) Fix typo from 'orignal' to 'original'

---

src/control/xml/SizeTAttribute.cpp
src/gui/dialog/AboutDialog.cpp
src/model/Document.cpp

The `size_t` format specifier is `%zu` and the
`gtk_get_*_version()` functions return `guint`,
to be printed with `%u`. The changes reflect this.

(Minor) Fix format specifiers to match types

---

src/gui/TextEditor.cpp

Fixes #1997, tested on a fresh Windows build on master.
Without setting the window of the input context at the beginning, the input method callbacks are not invoked.

Fix some IMEs not working in text tool on Windows

---

src/control/xojfile/LoadHandler.cpp
src/util/XojPreviewExtractor.cpp

In certain cases where an error occurs, the
file handlers obtained from `zip_fopen` were left
open. We close them. There is also an instance
of `zip_open` that we `zip_close`.

(Minor) Close dangling file handlers.

---

azure-pipelines/create-installers.yml

This allows collaborators to create installers for all supported OSs in PR's by commenting `\AzurePipelines run create-installers`
This should help with PRs that target Windows or macOS where it is quite the task for somebody to set up a build environment. Hopefully, this will increase testers. I restricted the creation of such installers to collaborators, as not to tax our pipelines too much.

Create pipeline for releases via comments

---

src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h
src/gui/inputdevices/PenInputHandler.cpp

This supposedly fixes #1534:
Some workarounds are needed for pressureless devices as well and pressure inference. I will add them later if this works on all available pressure sensitive devices.
Testing on various devices is necessary. For anyone trying this PR out:
- it's easier to get single-point strokes when zoomed in to maximum.
- if you open `Xournal++` from a terminal, you get a "single dot" message for every such single-point stroke.

Fix a bug that makes single point stroke pressureless

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/MainWindow.cpp
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

* On my Fedora 34 tablet (Wayland/KDE Plasma), GTK's default touchscreen scroll handling causes the view to jump rapidly while attempting to scroll.
* Disabling GTK's inertial scroll behavior works around the issue.

Settings: Allow disabling GTK inertial touch scrolling.

---

plugins/MigrateFontSizes/main.lua

This PR is needed for systems that provide both Gtk 3 and Gtk 4, like the flatpak with Gnome 41 runtime currently does. See https://github.com/flathub/com.github.xournalpp.xournalpp/pull/31

ensure lgi loads Gtk 3

---

src/pdf/base/XojCairoPdfExport.cpp

This PR sets Ciaros `CAIRO_PDF_METADATA_CREATOR` Metadata to the current Xournal++ version string. Exported PDFs will now have the version string in the PDF attributes
See also: https://cairographics.org/manual/cairo-PDF-Surfaces.html#cairo-pdf-metadata-t

Xournal++ version string in PDF metadata

---

AUTHORS
src/control/XournalMain.cpp
src/gui/TextEditor.cpp
src/gui/inputdevices/InputContext.cpp

Didn't have much progress on #3507 so opening this instead for now.
This PR makes `InputContext::handle` to return early if the event device is null, which would cause translateEvent to throw otherwise.
Related issue #3500

Add null check to device in InputEvent's handler

---

src/gui/PageView.cpp
src/gui/PageView.h
src/gui/inputdevices/StylusInputHandler.cpp

Pop up the Floating Toolbox (if configured) by pressing a button on your pen without tapping the screen.
Even though this seems to work fine, I am not sure if this is the right way to do this, and open to suggestions how it could be done better.
Closes #2901

show floating toolbox on button click

---

src/Xournalpp.cpp

This is a quick and dirty try to enable logging for Pango (see https://stackoverflow.com/a/26618242).
I'll rebase this once I got a working fix. For now, I'm too lazy to always fully rebuild the `release-1.1` branch when switching between PRs :wink:

Switch to FontConfig Backend for Cairo-Pango on Windows

---

src/control/XournalMain.cpp

When opening Xournal++ after an update changing where the configuration files are located, users are greeted with a message that contains an error: it says "Due to a recent update, Xournal++ has changed where **it's** configuration files are stored."
With these changes, the message is corrected so that users are not greeted by a typo.

Fixing typo

---

src/gui/toolbarMenubar/AbstractSliderItem.cpp
src/gui/toolbarMenubar/AbstractSliderItem.h
src/gui/toolbarMenubar/ToolMenuHandler.cpp
src/gui/toolbarMenubar/ToolZoomSlider.cpp
src/gui/toolbarMenubar/ToolZoomSlider.h

* Intended to facilitate creation of new slider toolbar tools.
* Applies the refactor from #3269 to `ZoomSlider`.
* This refactor may also be useful to #3288.

Toolbar: `ZoomSlider` refactor

---

src/control/Control.cpp
src/gui/dialog/FillOpacityDialog.cpp
src/gui/dialog/FillOpacityDialog.h
ui/fillOpacity.glade

* Make FillOpacityDialog's preview depend on the tool
* Destroy leaked cairo_surface
* Add minimal value for stroke filling alpha
This relates to #3480 and [this comment](https://github.com/xournalpp/xournalpp/pull/3480#discussion_r736771322).
I made a separate PR as it touches somewhat independent parts of the code.
This is ready for review.

FillOpacity minor changes:

---

src/config-debug.h.in
src/control/tools/BaseStrokeHandler.cpp
src/control/tools/SplineHandler.cpp
src/control/tools/StrokeHandler.cpp
src/control/tools/StrokeHandler.h
src/view/DocumentView.cpp
src/view/DocumentView.h
src/view/StrokeView.cpp
src/view/StrokeView.h

This PR solves various stroke's display issues by refactoring the class `StrokeView`.
The solved issues are:
- Filled highlighter strokes were not filled when being drawn
- Various display issues of the fadeout supposed to happen when a stroke has no audio attached and the `play Audio` tool is selected.
Here is a video with both behaviours (none of the strokes have audio attached here...).
https://user-images.githubusercontent.com/17818041/137598650-8c54c0e1-1fee-4a6d-a0c0-96e7db227721.mp4
Obviously, there is an intersection with #2874 (but only in `StrokeView`). The two PRs could be merged. In particular, this solves the issue raised [in this post](https://github.com/xournalpp/xournalpp/pull/2874#pullrequestreview-751185320)

Improve Stroke's display in StrokeView and StrokeHandler

---

plugins/Example/main.lua
src/plugin/luapi_application.h

New API:
```lua
app.getToolInfo("active")
app.getToolInfo("pen")
app.getToolInfo("highlighter")
app.getToolInfo("eraser")
app.getToolInfo("text")
```
Example output (from the test plugin):
```
active tool: eraser
active size (name): thin
active size (value): 2.83
active color: 0x000000
active fill opacity: -1
active drawing type: default
active line style: plain
pen size (name): medium
pen size (value): 1.41
pen filled: false
pen fill opacity: 127
pen color: 0x00c0ff
pen drawing type: strokeRecognizer
pen line style: dash
highlighter size (name): medium
highlighter size (value): 8.5
highlighter filled: false
highlighter fill opacity: 87
highlighter color: 0x00c0ff
highlighter drawing type: arrow
eraser type: default
eraser size (name): thin
eraser size (value): 2.83
text font (name): Sans …
```

Extend Lua API to get info on tools

---

cmake/README.md
readme/LinuxBuild.md
readme/WindowsBuild.md

This fixes  #3560.
The only places where the string "cppunit" now still exists is in the
migration guide for existing tests and in some legacy testcases.

Remove mentions of CppUnit in all READMEs

---

src/control/settings/Settings.cpp
src/control/settings/SettingsEnums.cpp
src/control/settings/SettingsEnums.h
src/gui/XournalppCursor.cpp
src/gui/dialog/SettingsDialog.cpp
ui/settings.glade

This option is accessible under `Edit > Preferences > View > Cursor > Cursor icon for pen` as a fourth option. Changing the input device type for a pen device from Pen to Mouse in `Edit > Preferences > Input System > Input Devices` gives us the default system cursor on hover, but the cursor reverts to one of the three existing Pen cursor icons (_No icon_, _Small dot icon_, and _Big pen icon_) upon 'pressing down' on the paper.
The original purpose of this minor modification was that I simply preferred using the default mouse pointer as my pen cursor, but since this feature is present in other popular note-taking apps such as OneNote, there may be other users who are used to drawing with their system cursor that may receive benefit from it as well. 
Additionally, educators require clear …

Added system cursor as pen cursor option.

---

src/control/XournalMain.cpp
src/control/jobs/PdfExportJob.cpp
src/pdf/base/XojCairoPdfExport.cpp

Set classic locale for PDF export link attributes

---

CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

Fixes #3561 
- move `FetchContent`, ... to `./test/CMakeLists.txt`
- `add_subdirectory` for tests with `EXCLUDE_FROM_ALL`
- set option `INSTALL_GTEST` to `OFF`

Prevent installation of Google test

---

src/util/serializing/ObjectInputStream.cpp
test/unit_tests/util/ObjectIOStreamTest.cpp

From issues of #2729, it seems that the function `ObjectInputStream::getNextObjectName` is broken on MacOs. It moves the stream's position forward while it should not.
This fixes that by simplifying the function.
It could fix #2246 (@xournalpp/core Could anyone with access to a Mac confirm that?)
~~[ ] Add test for selection serialization (that would then test `ObjectInputStream::getNextObjectName`)~~ Edit: Won't do here. It'd required to refactor:
- Make `ElementContainer` inherit from `Serializable` and move bits from `Control::clipboardPasteXournal` and `EditSelection::serialize` there.
- Add a test `testReadElementContainer` in `unit_tests/util/ObjectIOStreamTest.cpp`.
It goes beyond the scope of this PR.

Fix ObjectInputStream::getNextObjectName on MacOs

---

src/core/control/Control.cpp
src/util/PathUtil.cpp
ui/settings.glade

- updated path used in code
- updated translations
Closes #3348
In the original issue there were two directories for autosaves discussed. `~/.local/share/xournalpp/autosave` and `~/.cache/xournalpp/autosave`. I decided to go with the cache directory since this would be the first one I would search for autosaves.
I'm pretty sure that I did something wrong with the translation files so please explain me quickly what I've should done with those. Should I've just changed xournalpp.pot and then ran make?

Change autosave dir to ~/.cache/xournalpp/autosaves

---

src/control/Control.cpp
src/control/RecentManager.cpp
src/model/Document.cpp
src/util/PathUtil.cpp
src/util/PathUtil.h

Detect .PDF as pdf

---

src/core/control/ClipboardHandler.cpp

#3042 introduced #3637 because `g_list` and `std` do not have the same standard of `Compare` functions.
In a `g_list`, A < B if `Compare(A,B) < 0`. With `std`, A < B if `Compare(A, B) == true`.
Merging in 24 hours if no objections are raised.

Fix 3637 - properly order copied text in clipboard

---

src/core/control/Control.cpp
src/core/control/RecentManager.cpp
src/core/control/tools/InputHandler.cpp
src/core/model/Document.cpp
src/util/PathUtil.cpp
src/util/include/util/PathUtil.h

This premature merging is for including #3652 rapidly into master. The bug this PR fixed creates (slightly) corrupt saved files.

Merge release branch into master

---

src/core/view/background/BackgroundConfig.cpp

Fix BackgroundConfig::loadValue for doubles (used for loading in background configs from pagetemplates.ini) by using stod instead of stoul to preserve the decimal places of the configured value, which would be truncated otherwise (see #3655)
This relies on the locale for LC_NUMERIC to be "C" (e2a1f97327d94818cdecb19795308f8aed3177eb). There's been some discussion about this in #3611. Because of that, I'm not sure if using stod is the best way to fix this (as stod is locale-dependent).
If the locale was a locale which uses a comma as the decimal separator (for example de_DE.UTF-8), there would be two problems:
- Different configs work differently on different locales (lw=1.2 will work on en_US, but if that config is shared with a user with a de_DE locale, it won't work for that user …

Fix #3655: Use stod for loading doubles

---

src/core/plugin/luapi_application.h

I've been playing around with the plugin API and background configs. 
Bizarrely, you can get the format (graph, dotted, ...) of your page/background with getDocumentStructure(), but not the config (line width etc.). This should be included, since a full PageType has both. You can pass both to changeCurrentPageBackground via the plugin API.
I've added it and it seems to work fine, feel free to test it with the changed example plugin in 4a53df667fcc8c8d2cb95813cd99a373f0115161.

Add pageTypeConfig to app.getDocumentStructure()

---

plugins/Export/main.lua
plugins/Export/plugin.ini
src/core/control/ExportHelper.cpp
src/core/control/ExportHelper.h
src/core/control/XournalMain.cpp
src/core/control/jobs/CustomExportJob.cpp
src/core/control/jobs/PdfExportJob.cpp
src/core/pdf/base/XojPdfExportFactory.cpp
src/core/pdf/base/XojPdfExportFactory.h
src/core/plugin/luapi_application.h

This PR (when finished) closes #3565
Export already works. In the plugin you just need to add a line like
```lua 
app.export({["outputFile"] = "/home/USERNAME/Test.pdf", ["range"] = "2-5; 7", ["background"] = "all", ["progressiveMode"] = false})
```
(for pdf) or 
``` lua
app.export({["outputFile"] = "/home/USERNAME/Test.svg", ["range"] = "2-5; 7", ["background"] = "all"})
```
(for svg) or
``` lua
app.export({["outputFile"] = "/home/USERNAME/Test.png", ["range"] = "2-5; 7", ["background"] = "all", ["pngDpi"] = 300})
```
(for png). It's still a hack, since I mostly copied code from `XournalMain.cpp` (`exportPdf` and `exportImg` functions), but probably already usable.
The filename generation will be left to the plugin. I have added a "xoppFilename" field to the `app.getDocumentStructure()` …

add export option for pdf, svg, png to plugin API

---

src/gui/inputdevices/StylusInputHandler.cpp

Fixes #3274.
This is #3658 rebased on release-1.1 (with Clang format fixed), authored by @wtbgagoa.

Fix tool activation for TabletPCButtonEnabled mode

---

src/control/RecentManager.cpp
src/control/RecentManager.h
src/control/XournalMain.cpp

- Add nullptr check to getMostRecent method
- Add nullptr check to on_startup function
- Change method descriptions to make explicit that nullptrs can be returned
Fixes #3734

fix: Crash on startup with no recent files

---

CMakeLists.txt
src/config-git.h.in
src/config.h.in
src/core/control/XournalMain.cpp
src/core/gui/dialog/AboutDialog.cpp

This reduces build tasks after checkout from ~120 to 2 object files and their dependencies.

Move git repo info to separate config header

---

mac-setup/build-libzip.sh
mac-setup/build-poppler.sh
mac-setup/build-portaudio.sh
mac-setup/build-sndfile.sh

Updating the build scripts for poppler (including openjpeg), libzip and portaudio, so they use the latest version.

update macos build scripts

---

azure-pipelines/steps/build_mac.yml
mac-setup/build-app.sh

The release 1.1 branch uses `cppunit` for unit tests, which is not required in the master branch any more due to the migration to `gtest`. The new `gtk` blob for macos does not include `cppunit`, so it must be fetched during the build process. 
Moreover the new `gtk` blob uses a different loader cache location compared to the old one, so this needs update, too.

Fixup using new Gtk blob

---

azure-pipelines/steps/build_mac.yml
mac-setup/build-app.sh

The new Gtk blob updates several libraries, in particular
Gtk `3.24.28 -> 3.24.30` (with patches for MacOS Monterey)
Openjpeg `2.3.0 -> 2.4.0`
Poppler `0.72 -> 22.01`
Portaudio `19.06 -> 19.07`
Added GtkSourceView `4.8.1`
Most significantly it should work on MacOS Monterey. This needs to be tested.

Test out new gtk blob

---

src/gui/sidebar/previews/page/SidebarPreviewPages.cpp

This is a quick fix for #3712. In the long term, we should refactor the sidebar logic so that side effects (e.g., scheduling cleanup jobs) are clearly separated from the basic functionality.

Fix deadlock in SidebarPreviewPages

---

src/core/gui/toolbarMenubar/ToolMenuHandler.cpp

The same typos were fixed in several places before, but it has been still there.

Fix minor typo: Tex to TeX

---

CMakeLists.txt

This PR adds an option to enable linking with gperftools, which can be used to profile the application.
How to profile:
1. Install `gperftools` through your distro package manager (`google-perftools` on Debian/Ubuntu).
2. Enable the profiling flag: `cmake .. -DENABLE_PROFILING=on`.
3. Compile the application. Check that libprofiler is linked: `ldd ./xournalpp | grep libprofiler`
4. Run the application using the appropriate environment variables. E.g., `CPUPROFILE=/tmp/xournalpp.prof ./xournalpp`
5. Use `pprof` to view the profile in text format, or export to callgrind format and view in `kcachegrind`.

Enable linking with gperftools

---

AUTHORS
copyright.txt
ui/about.glade

Here is the output of
```
git shortlog -se   | perl -spe 's/^\s+\d+\s+//' > AUTHORS_raw
diff AUTHORS AUTHORS_raw
```
[diff.txt](https://github.com/xournalpp/xournalpp/files/8009657/diff.txt)
The diff should show that I have only removed authors from the AUTHORS_raw file that are already in the developer team. One exception is @fabian-thomas who has used 2 different email adresses, where I only kept one.
@bhennion @personalizedrefrigerator 
**Edit**: Updated on Feb 6, 2022.

Update Authors lists

---

src/core/control/tools/VerticalToolHandler.cpp
src/core/control/tools/VerticalToolHandler.h
src/core/control/zoom/ZoomControl.cpp
src/core/control/zoom/ZoomControl.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h

Currently, the Vertical Spacing tool works as follows:
* The user clicks and holds to set an "anchor" line.
* By dragging down some distance `y`, all elements on the same page below the anchor line are pushed down by `y` units.
* If the user drags _up_ above the anchor line instead, all elements on the same page below the anchor line are _pulled_ up by `y` units.
**Updated PR description**:
This PR allows users to also select elements above the anchor line using Ctrl. The behavior is the same as when selecting below the line; i.e. if selecting below the line, the elements are translated in the same direction as the mouse movement and by the same amount.
TODO:
---
**Old PR description**:
This PR modifies the behavior of Vertical Spacing so that dragging above the anchor line by `y` units …

Allow Vertical Spacing tool to move elements above line

---

src/core/control/tools/PdfElemSelection.cpp
src/core/pdf/popplerapi/PopplerGlibPage.cpp

Fixes #3790. See commit message for details.

Fix PDF linear text selection on "improper" rectangles

---

CHANGELOG.md
debian/changelog
desktop/com.github.xournalpp.xournalpp.appdata.xml
mac-setup/Info.plist
rpm/fedora/xournalpp.spec
scripts/release_helper.sh

Due to the directory structure change, the release helper script was not correctly applied to all files when bumping the version on master branch.
This PR fixes the helper script and corrects the version bump adjustments.

Fix version bump error when making 1.1.1 release

---

plugins/QuickScreenshot/main.lua

Add the default option to use "maim" and "xclip" to copy selections from the screen into the system clipboard.
This allows for a Linux user who has maim and xclip installed to simply select part of the screen and paste it using ctrl+v or by pasting using the "paste" button in xournal++.
This is better than before because it does not require saving temporary files. The previous option of using scrot and saving in a temp file still exists and is used as a fallback

Add maim&xclip option to screenshot plugin

---

azure-pipelines/continuous-integration.yml
azure-pipelines/create-installers.yml
azure-pipelines/dependencies/msys2-blob.yml
azure-pipelines/release.yml

Partially fixes #3714 (also need to update the deployment steps after this is merged). This PR also updates the Windows CI build to use the `windows-2019` image since the currently used image will be removed next week.

Generate portable install for Windows in release pipeline

---

src/core/control/XournalMain.cpp
src/core/gui/PageView.cpp
src/core/gui/TextEditor.cpp

When using gcin as IM, I usually use arrows key to select candidates, or escape key to leave candidate menu. But in xournal++ text editor if I wanted to do the same, the cursor gets moved instead with arrow keys, and the whole text box gets closed with escpae key. This PR move event handling of IM before the text editor event handling and escap key handling so character selection.
With this PR, gcin now works pretty well with xournal++, so it can probably be removed from here https://github.com/xournalpp/xournalpp/blob/3d8dc4bc8b1cbc1230062937dd9ff19039834b00/src/core/control/XournalMain.cpp#L306-L308
(I don't have xim installed to check, but this might fix its issue as well).
@tattsan tagging you because you were testing with xim on my other PR, maybe you can help me test this one as …

Make TextEditor pass events to IM first

---

xournalpp-ubuntu-ppa.recipe

The previous recipe had the issue, that the +dev versions were considered to be lower than the released versions (without +dev). Leaving out the patch version fixes that problem. The epoch has to be increased (from 1 to 2) so that all newly released versions are higher than the previously released ones.
Sanity checks (using `dpkg --compare-versions`), all of which echo `true`: as you may check by pasting these lines into a console.
```shell
dpkg --compare-versions "2:1.1.1~dev-202201011200" lt "2:1.1.1-202201011200" && echo true
dpkg --compare-versions "2:1.1.1-202201011200" lt "2:1.1.1+dev-202201011200" && echo true
dpkg --compare-versions "2:1.1.1~dev-202201011200" lt "2:1.1.1~dev-202201011201" && echo true
dpkg --compare-versions "2:1.1.1-202201011200" lt "2:1.1.1-202201011201" && echo …
```

fix launchpad build recipe

---

src/core/gui/inputdevices/InputContext.cpp
src/core/gui/inputdevices/InputContext.h
src/core/gui/inputdevices/SetsquareInputHandler.cpp
src/core/gui/inputdevices/SetsquareInputHandler.h

This PR make the setsquare handle blocking of devices properly, which is currently used for the automatic hand recognition (an option that can be turned on in the preferences, Touchscreen panel). It fixes an issue reported by @lxdb in #3082, where using the stylus resulted in input events temporarily not getting processed at all (since everything was blocked by the setsquare input handler). 
@lxdb Please test the PR on your device (with automatic hand recognition turned on).

Properly handle blocking of devices for setsquare

---

src/core/control/tools/SplineHandler.cpp
src/core/gui/MainWindow.cpp
src/core/gui/PageView.cpp
src/core/gui/inputdevices/TouchDrawingInputHandler.cpp

Fixes some compiler warnings related to "suggest parantheses around && within ||"

fix "suggest parantheses around && within ||"

---

azure-pipelines/continuous-integration.yml
azure-pipelines/jobs/release_ubuntu.yml
azure-pipelines/release.yml
azure-pipelines/steps/build_mac.yml
azure-pipelines/steps/install_deps_ubuntu.yml
readme/LinuxBuild.md
test/CMakeLists.txt
test/unit_tests/control/ToolEnumsTest.cpp

This PR changes the test build config so that the system gtest is preferred. Optionally, `-DDOWNLOAD_GTEST=on` may be set to explicitly download gtest from the internet (system gtest is ignored when using this flag). Rationale: sandboxed build environments may not have internet (e.g., Debian CI), but we still want to be able to run tests.
Edit: TODO:

Allow system gtest; add explicit download flag

---

mac-setup/build-poppler.sh

The new version was already used for the new Gtk blob for MacOS.

Update poppler version on MacOS

---

src/core/control/XournalMain.cpp
src/core/gui/TextEditor.cpp
src/core/view/TextView.cpp
ui/xournalpp.css

This is a merge of the bugfixes from the release branch to the master branch, for #3503 could interfere with https://github.com/xournalpp/xournalpp/commit/38258a498f9edfc8cea0e842da745dcaa0fa7505.
Note that two commits from the release branch were dropped:
- e409fb6 : Automated version bump to 1.1.2~dev
- 034deb5 : Fix backtrace linker flags
@Technius, could you confirm that 034deb5 is not needed on the master branch?

merge release 1.1

---

src/core/model/Image.cpp

Fix #3951.
Oops, accidentally swapped height and width when generating the image buffer.

Fix image loading regression

---

src/control/Control.cpp

Bug fix attempt for selecting correct tool when Tools->Default Tools is selected.

Select correct tool when selecting default tool

---

src/core/view/DocumentView.cpp

I introduced a bug with #3503, making strokes not being rendered properly while we use the standard eraser.
This PR fixes that (a flag was set incorrectly).
It's a very simple fix, so I'll be merging this in 24 hours unless an objection is raised.

Fix display of strokes while erasing

---

src/core/control/Control.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Made required enhancement per  **Show the filepath in the titlebar along with the filename #3921** issue.
To avoid breaking default behavior added "Show filepath in titlebar" in **view** tab in settings. 
Default behavior remains same i.e. only filename is shown.
Edited behavior when **Show filepath in titlebar** setting changes and settings are saved, change in titlebar is applied immediately.
Translations to other languages were not added.

3921 show the filepath in the titlebar along with the filename

---

src/core/gui/inputdevices/AbstractInputHandler.cpp
src/core/gui/inputdevices/SetsquareInputHandler.cpp
src/core/gui/widgets/XournalWidget.cpp
src/core/gui/widgets/XournalWidget.h

Those variables `xournal->x` and `xournal->y` have been `0` all the time (for many years) and made the code look more confusing. They are pointless, so I suggest to remove them via this PR.

Remove x and y from GtkXournal struct

---

CMakeLists.txt
src/xoj-preview-extractor/CMakeLists.txt

The CMake dependencies found with pkgconfig will incorrectly set the external
module LINK_OPTIONS to be of the form `-framework A B C`, which is incorrect.
This commit adds some checks to correct this CMake/pkgconfig error.
Furthermore, some redundant linker flags have been removed from
xournalpp-thumbnailer.

MacOS: fix linker flags when using MacPorts

---

CMakeLists.txt
src/core/control/ClipboardHandler.cpp
src/core/control/RecentManager.cpp
src/core/control/pagetype/PageTypeMenu.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
src/core/gui/inputdevices/InputContext.cpp
src/core/gui/inputdevices/KeyboardInputHandler.cpp
src/core/gui/widgets/PopupMenuButton.cpp
src/core/gui/widgets/XournalWidget.cpp
src/core/gui/widgets/gtkmenutooltogglebutton.cpp
src/util/include/util/gtk4_helper.h
src/util/pixbuf-utils.cpp

@reviewers, please review commit by commit.
https://docs.gtk.org/gtk4/migrating-3to4.html
==== HArder to fullfill, since the API is not fully replaced ====

Preparation for GTK4

---

src/core/control/SearchControl.cpp
src/core/control/SearchControl.h
src/core/control/tools/BaseStrokeHandler.cpp
src/core/control/tools/PdfElemSelection.cpp
src/core/control/tools/PdfElemSelection.h
src/core/control/tools/Selection.cpp
src/core/control/tools/Selection.h
src/core/control/tools/SplineHandler.cpp
src/core/control/tools/StrokeHandler.cpp
src/core/control/tools/StrokeHandler.h
src/core/control/tools/VerticalToolHandler.cpp
src/core/control/tools/VerticalToolHandler.h
src/core/gui/PageView.cpp
src/core/gui/TextEditor.cpp
src/core/gui/TextEditor.h

This PR improves performance and mem usage in StrokeHandler for strokes that require a full redraw at each event, by removing an unecessary mask.
It also fixes the display of single-point strokes that require a full redraw, and removes the corresponding warnings.
This is ready for a review.

Remove unecessary mask in StrokeHandler

---

src/core/gui/XournalView.cpp
src/core/gui/inputdevices/InputContext.cpp
src/core/gui/inputdevices/InputContext.h

- since the xournal widget is in disposing state,
the event handlers can still be called
fixes #3997

Added a workaround for a reference issue.

---

src/core/control/ClipboardHandler.cpp
src/core/control/PdfCache.cpp
src/core/control/PrintHandler.cpp
src/core/control/jobs/CustomExportJob.cpp
src/core/control/jobs/SaveJob.cpp
src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/VerticalToolHandler.cpp
src/core/pdf/base/XojCairoPdfExport.cpp
src/core/pdf/base/XojPdfPage.h
src/core/pdf/popplerapi/PopplerGlibPage.cpp
src/core/pdf/popplerapi/PopplerGlibPage.h
src/core/view/DocumentView.cpp
src/core/view/DocumentView.h
src/core/view/PdfView.cpp
src/core/view/PdfView.h
src/core/view/SelectionView.cpp
src/core/view/SelectionView.h
src/core/view/View.h

This PR is a segment of #3969 (for easier review). It does two independent bits:
1. Create a SelectionView class to handle drawing the content of a selection (or any other ElementContainer)
2. Split XojPdfPage::render into two (render and renderForPrinting), simplifying the code.
This is ready for a review.

View refactor 1.5: SelectionView & PdfPage::render

---

src/core/gui/PageView.cpp

Fix #4011
The issue only affects HiPDI settings, because a DPI scale factor was omitted in `XojPageView::elementChanged()`.
This PR fixes that.

Fix HiDPI bug when using stroke tools

---

src/gui/XournalView.cpp

Addresses #3765
This pr stops editing of the textbox once you change pages. Before, it would stay selected but you couldn't type until you went back to the page it was on.

Unfocus text boxes after the selected page changes

---

src/core/control/PdfCache.cpp
src/core/control/PdfCache.h
src/core/control/jobs/ImageExport.cpp
src/core/control/jobs/PreviewJob.cpp
src/core/control/jobs/RenderJob.cpp
src/core/gui/XournalView.cpp
src/core/gui/XournalView.h
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.h
src/core/pdf/base/XojPdfDocument.cpp
src/core/view/PdfView.cpp
src/core/view/PdfView.h

This PR improves the behaviour of PdfCache (and callers).
Before this PR, whenever a pdf background was to be rendered:
- a PopplerPage was extracted from the PDF document (using the page number, through a call to `poppler_document_get_page(document, number)`).
- the PopplerPage was passed on to PdfCache, which tested if the cache contained another page with the same number
The PR removes the unnecessary creation of a new PopplerPage (meaning the extraction from the PDF document), and simply searches the cache for a PopplerPage with the same number.
I am not sure how expensive a call to `poppler_document_get_page(document, number)` is, but this should slightly improve the performance of the process.
I tested the following behaviours:
- Open a file without a pdf background
- Open a file …

Fetch PopplerPage from PdfCache instead of recreating it

---

test/unit_tests/model/ErasableStrokeTest.cpp

Fix #4050 
The issue was due to numerical imprecisions, which, for some reason, only appear with those compile flags.
They are irrelevent for the app (there is a safe-guard that forbids wrongly erasing parts of a stroke, precisely to catch those kind of cases).
This PR simply modifies the test case to remove those imprecision issues.
The borderline cases that trigger such issues: when a stroke point is exactly on the eraser box's boundary. As it seems the compiler options (harmlessly) change the app behaviour in those cases, they simply should not be part of the test unit.

Fix instability in ErasableStroke.testIntersectWithPaddedBox

---

azure-pipelines/continuous-integration.yml
azure-pipelines/create-installers.yml
azure-pipelines/dependencies/msys2-blob.yml
azure-pipelines/release.yml

Switch away from deprecated vs2017-win2016 image on 1.1.x branch. We already
switched to windows-2019 on master branch.

[1.1.x] ci: update Windows VM image to windows-2019

---

src/gui/PageView.cpp
src/gui/TextEditor.cpp
src/gui/TextEditor.h

The PR offers a better fix to #3977, reverting #4000 which had a performance cost.
Indeed, #4000 triggered unecessary rerenderings (i.e. recomputation of the page buffer), while repaint (i.e. reblitting the buffer and the TextEditor) was enough.
The issue #3977 came from the fact that the rectangle in `rect` in 
https://github.com/xournalpp/xournalpp/blob/a394f85395f3c70d43a880a4de4354b2d9378fb1/src/gui/TextEditor.cpp#L909-L912
was computed without the string in `this->text` having been updated. This resulted in a to small repaint operation.
This PR ensures the string is updated before `repaintEditor` is called when adding characters, and after when removing characters.
NB: the reason why #4000 actually fixed the issue was that each rerendering trigger a repaint of the entire widget. …

Optimize TextEditor calls for rerendering

---

mac-setup/build-poppler.sh
readme/MacBuild.md

The current Gtk blob for MacOS already contains the updated versions of open-jpeg and poplar.

Update open-jpeg and poppler version in MacOS build script

---

src/core/control/PdfCache.cpp

Fix #4114.
The issue was that Poppler does not render properly on cairo surfaces that have a device scale applied (by cairo_surface_set_device_scale). It simply ignores this scale, leading to a very pixelized PDF output.

Fix low quality rendering of vector graphics embedded in PDF files

---

src/core/control/jobs/RenderJob.cpp
src/core/control/jobs/RenderJob.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/XournalView.h
src/core/view/background/PdfBackgroundView.cpp
src/util/include/util/raii/CLibrariesSPtr.h
src/util/include/util/raii/CairoWrappers.h
src/util/include/util/raii/GObjectSPtr.h
test/unit_tests/util/RAIIWrappersTest.cpp
test/unit_tests/util/TinySmallVectorTest.cpp

This PR creates RAII wrappers for cairo_t and cairo_surface_t (as well as a template for further applications -- e.g. GObject...).
Those wrappers are then used in gui/PageView and to refactor jobs/RenderJob.
One major change with this PR concerns HiDPI settings: jobs/RenderJob is now able to rerender only a portion of the page (it was only the case for GDK_SCALE=1 before this PR).
This should drastically improve performances on HiDPI displays and fix #3903 and may help with other performance related issues as well.
**Note:** ~~This PR is based on #4081. Only the last 2 commits actually belong to this PR.~~

Add RAII wrappers for cairo classes in gui/PageView and jobs/RenderJob

---

src/core/audio/AudioQueue.h
src/core/control/CrashHandlerWindows.h
src/core/gui/ToolbarDefinitions.h
src/core/gui/widgets/ZoomCallib.h
src/core/gui/widgets/gtkmenutooltogglebutton.h
src/core/model/ElementContainer.h
src/core/model/PageRef.h
src/core/plugin/PluginController.cpp
src/core/plugin/luapi_application.h
src/util/include/util/CircularBuffer.h
test/unit_tests/control/LoadHandlerTest.cpp

This PR is a followup of #4098: it cleans up a couple of includes in a couple of header files that do not have a .cpp counterpart.
As the changes are completely harmless, I'll be merging this in 24 hours unless someone objects.

Forward-declare XojPage in PageRef and protect headers

---

CMakeLists.txt

This adds a CMake option to disable linking with X11, enabling builds on some platforms (e.g., Mac M1 builds using the Nix package manager).

Add option to disable X11 linking

---

src/core/control/XournalMain.cpp
ui/about.glade

Fix #4113 
* change Xournalpp version, git commit id and GTK version in about window as selectable text
* print commit number along with version number as command output for `xournalpp --version`

Make version text selectable and print commit number

---

src/control/ToolHandler.cpp
src/gui/inputdevices/PenInputHandler.cpp

Some Motion events were being transfered twice to the same InputHandler, for tools such that isSinglePageTool == true (e.g. rectangle, ellipse, spline tools). This patch fixes this.
It also fixes ToolHandler::isSinglePageTool, were a boolean operation was obviously wrong.
Merging to the release branch in 48 hours, unless an objection is raised.

Fix: move events being processed twice

---

src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/Redrawable.cpp
src/core/gui/Redrawable.h
src/core/gui/RepaintHandler.cpp
src/core/gui/RepaintHandler.h
src/core/gui/XournalView.cpp
src/core/gui/XournalView.h
src/core/gui/widgets/XournalWidget.cpp
src/core/gui/widgets/XournalWidget.h
src/util/include/util/PairView.h

This is a code cleanup PR coming from #4137, #4158 and #4159, to simplify the reviewing.
Two things in here:
1. Some const-correctness in various classes in gui/
2. Fix util/PairView to work on const qualified containers
Since nothing is really happening in this PR, I'll be merging it in 48 hours unless someone objects.

Code cleanup before handlers splitting

---

src/core/control/Control.cpp

If there is a PDF file with the same name as the missing PDF in the directory where the journal file is saved, the dialog now proposes that file to the user. If not the dialog stays as before.
This is especially useful when moving the journal file and the background to a new location. Or in my case where I switch between Linux and Windows a lot, the background can be automatically found even tho Linux and Windows are using a different path structure

 Added functionality to the missing PDF background dialog to propose a replacement file

---

src/core/gui/inputdevices/SetsquareInputHandler.cpp

This is an obvious bug, since `xdir` and `ydir` get multiplied by `amount` twice.

fix bug for setsquare translation via arrow keys

---

src/core/plugin/Plugin.cpp
src/core/plugin/Plugin.h
src/core/plugin/luapi_application.h

This PR implements an optional `mode` parameter for `app.registerUi`. It allows to have multiple registered entries to share the same callback function executed in a different mode. If the `mode` parameter is specified the callback function should have the form
```lua
def functionname(mode)
-- code
end
```
For example you may want to register a menu entry for each color in the color palette without defining a separate callback function for each color.

add optional mode parameter for plugin callback functions

---

src/core/control/jobs/RenderJob.h
src/core/pdf/base/XojPdfPage.h

Fixes #4220 (and partially  #3949)
The `release-1.1` branch doesn't have includes of the form `#include <cairo/cairo.h>`, so I just apply it on the master branch.
Merging in 24 hours if no objections are raised.

fix cairo includes for macos homebrew install

---

src/core/plugin/luapi_application.h

As discussed on gitter, a small PR to add implicitly needed includes to the `src/core/plugin/luapi_application.h` header.

luapi_application.h: add implicit includes

---

src/core/plugin/PluginController.cpp

While the includes are wrapped in the preprocessor checks, we use the classes in the cases where plugins are not enabled too.
```log
/home/user/projects/xournalpp/src/core/plugin/PluginController.cpp:164:5: error: unknown type name 'GtkWidget'
GtkWidget* menuitemPlugin = control->getWindow()->get("menuitemPlugin");
^
/home/user/projects/xournalpp/src/core/plugin/PluginController.cpp:164:40: error: member access into incomplete type 'Control'
GtkWidget* menuitemPlugin = control->getWindow()->get("menuitemPlugin");
^
/home/user/projects/xournalpp/src/core/plugin/PluginController.h:21:7: note: forward declaration of 'Control'
class Control;
^
```

Fix compilation when plugins are not being build

---

src/core/control/xojfile/LoadHandler.cpp
src/core/control/xojfile/SaveHandler.cpp
src/core/model/Document.cpp

Fixes #3189 and a new bug
**First commit (80e50c53f6801410cd0ad9cd98d6755407c4b629) is quite trivial. It fixes the following issue:**
The attach mode gets lost when loading and copying the Document. 
**Second commit (bf660d496ffec4b4d7212f817fac6a5f53984884) is more controversial:**
When opening a file with attach mode and you save it again then poppler fails to overwrite the pdf file and corrupts it. For this to happen you need the first commit to even be able to save a loaded xournal file in attach mode.
Strangely enough this doesn't happen when you create a new file and annotate a pdf in attach mode. Overwriting the pdf works just fine there. This suggests that something happens with the pdf when loading it.
The way I fixed this is pretty simple. I just don't overwrite the pdf file if …

Fix attach mode issues

---

src/core/control/Control.cpp

This pr fixes a issue in  #4165, where in every file attach mode is enabled.
This issue started to appear after #4228 fixed the attach mode. Now the previous mode is kept as is.

fixed overriding attach mode when using "proposed pdf" in open dialog

---

cmake/include/GitRepo.cmake

CMAKE command to get the git remote url doesn't always work. For example, on my machine:
```sh
$ git config --get remote.origin.url
ghhy:xournalpp
```
The build ends up failing:
```txt
CMake Error at cmake/include/GitRepo.cmake:40 (list):
list index: -1 out of range (-1, 0)
Call Stack (most recent call first):
CMakeLists.txt:52 (include)
```
Because I have custom `url.<base>.{insteadOf,pushInsteadOf}` declarations in my Git config (see `git-config(1)`)
Better is to do `remote get-url origin`, which is available since Git 2.7, release in 2015. ([source](https://stackoverflow.com/a/32991784))

Build: CMake Properly obtain URL of origin

---

readme/LinuxBuild.md

The documentation for building previously specified a minimum version of `3.10`; yet, the `CMakeLists.txt` and `src/CmakeLists.txt` files specified a minimum cmake versions of `3.12` and `3.13`. This fixes the documentation to match the build files

Correct minimum CMake version

---

azure-pipelines/jobs/release_ubuntu.yml
azure-pipelines/util/build_appimage.sh

This modifies the build script such that now a `.zsync` file is written in `./build`, for AppImage Update. Closes #1915
Documentation used (for future reference):
- [Usage of `UPD_INFO`](https://github.com/AppImageCommunity/AppImageUpdate/blob/af298b7aebfab4bcee7490a86f0471cc22db248b/ci/build-appimages.sh#L100)
- [Documentation](https://github.com/AppImage/AppImageSpec/blob/ce1910e6443357e3406a40d458f78ba3f34293b8/draft.md#github-releases) for `gh-releases-zsync`
The original issue states that:
> create a .zsync file, which you, by default, just need to put next to the AppImage (e.g., on GitHub, just upload both together)
I couldn't find the script that uploads the built artifacts to GitHub. Is that script located here or is the publishing step a manual one and this can just be merged?

Support AppImage Update in build script

---

src/gui/dialog/toolbarCustomize/ToolbarDragDropHelper.cpp

As mentioned [here](https://github.com/xournalpp/xournalpp/pull/4285#discussion_r989221493) in #4285, this PR fixes a potential segfault, but against `release-1.1` instead of `master`

Hotfix: Prevent `g_object_get` segfault

---

src/core/audio/AudioRecorder.cpp
src/core/audio/AudioRecorder.h
src/core/audio/VorbisProducer.h
src/core/control/Tool.cpp
src/core/control/XournalMain.cpp
src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelectionContents.cpp
src/core/gui/FloatingToolbox.h
src/core/gui/dialog/LatexSettingsPanel.cpp
src/core/gui/dialog/RenameLayerDialog.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.h
src/core/gui/inputdevices/AbstractInputHandler.cpp
src/core/gui/inputdevices/HandRecognition.cpp
src/core/gui/inputdevices/HandRecognition.h
src/core/gui/inputdevices/PenInputHandler.h
src/core/gui/inputdevices/SetsquareInputHandler.cpp
src/core/gui/inputdevices/TouchDrawingInputHandler.cpp
src/core/gui/inputdevices/TouchInputHandler.cpp
src/core/gui/sidebar/Sidebar.cpp
src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
src/core/gui/toolbarMenubar/ToolPageLayer.cpp
src/core/gui/toolbarMenubar/ToolPageLayer.h
src/core/gui/toolbarMenubar/ToolPageSpinner.cpp
src/core/gui/toolbarMenubar/ToolPageSpinner.h
src/core/model/Snapping.cpp
src/core/model/SplineSegment.cpp
src/core/view/LayerView.h
src/core/view/View.h
src/util/serializing/ObjectOutputStream.cpp

Hopefully, I would like to get to a place where there are no warnings outputted to the console by default (if ya'll maintainers agree?) - either by fixes or by excluding the noise by removing the warning check. That way, any warnings or mistakes are obvious and never missed.
This PR includes changes to get rid of a few tens of warnings that are low hanging fruit, that have a very low probability of changing behavior.
To make it easier for review, I'll add comments in places where the application behavior has _potentially_ changed. In all other cases, things should be proven to have identical behavior, according to clang.
Also, I'll note that when passing in `-Wno-conversion -Wno-overloaded-virtual -Wno-delete-non-abstract-non-virtual-dtor -Wno-deprecated-declarations`, then there will be …

Fix many diagnostic warnings

---

src/undo/GroupUndoAction.cpp

Fixes #4138. The corresponding fix for `master` branch has already been made a while back.

Fix GroupUndoAction crash in release-1.1

---

scripts/release_helper.sh

The first commit runs the file through shellcheck. Mostly this
- Improves argument quoting
- Check errors directly. That is, rather than checking `$?`, simply add an `if ! cmd; then` to check for error. Less error-prone
- Improve `read`. Instead of Executing it in a subshell and printing `REPLY`, just run it directly
- Use `#!/usr/bin/env bash` as shebang. This makes the scripts runnable on more distros, such as Nix
- The `set -o pipefail` ensures that errors can be correctly checked after a pipe (and makes `set -e` work better, but that is still disabled)
Test output
<details>
<summary>Details</summary>
```sh
$ git switch master
$ ./scripts/release_helper.sh prepare 1.8.0
SUCCESS: New release 1.8.0~dev was successfully prepared
You are now on the release branch (release-1.8).
Please …
```

Release script improvements

---

src/core/control/tools/BaseShapeHandler.cpp

I let an UB slip in when refactoring the BaseShapeHandler: strokes without any points were created, leading to SegFaults upon calls to Stroke::calcsize. This PR fixes that.
It may as well solve #4316 (I can't know for sure, I can't reproduce the issue).
@tattsan would you mind trying this out and telling if this fixes your issue?

Fix UB for BaseShapeHandler when clicking without moving

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/control/SearchControl.cpp
src/core/control/SearchControl.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/SearchBar.cpp
src/core/gui/SearchBar.h
src/core/gui/XournalView.cpp
src/core/gui/XournalView.h
src/core/pdf/base/XojPdfPage.h
src/core/pdf/popplerapi/PopplerGlibPage.cpp
src/core/pdf/popplerapi/PopplerGlibPage.h
src/core/view/TextView.cpp
src/core/view/TextView.h
src/core/view/overlays/SearchResultView.cpp
src/core/view/overlays/SearchResultView.h

This PR splits control/SearchControl into a view and a controller.
Some small side-refactoring:
- searched strings are now passed by references (instead of by a succession of copies and moves)
Ready for a review.

Split control/SearchControl into view/controller

---

src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
ui/iconsColor-dark/hicolor/scalable/actions/xopp-pen-fill-opacity.svg
ui/iconsLucide-dark/hicolor/scalable/actions/xopp-pen-fill-opacity.svg
ui/iconsLucide-light/hicolor/scalable/actions/xopp-pen-fill-opacity.svg

Until now, if you wanted to change the **fill opacity**, you had to go to _tools -> pen/textmarker-> fill-opacity_. But this PR adds the functionality to reach the **fill opacity** option more easily by providing a new toolbar item, as requested in #4123. 
I also created a new icon. The color scheme was fitted to the already existing **fill** icon. If you don't like the icon or its colors and have any suggestions on how to improve it, just let me now and I will fix it.

Added the "Fill Opacity" feature to the available toolbar items

---

src/core/control/xml/XmlNode.h

This fixes the issue where Base classes in C++ need to have an explicitly declared virtual destructor (in this case, default destructor), so when instantitated derived classes (with a static type of the base class) are destructured, it's not UB. This shuts up a compiler warning diagnostic and [isn't present in release-1.1](https://github.com/xournalpp/xournalpp/blob/e2f7f0f562645f4c971b43b6e44dd2dc39c61763/src/control/xml/XmlNode.h#L23)

Declare a default virtual destructor in XmlNode

---

src/control/latex/LatexGenerator.cpp

Fixes #4334
Also fixes a warning when freeing a `g_error` that has not occured (is `nullptr`)
The PR (built from source) can be tested via `PATH="" ./src/xournalpp`, which makes the `PATH` environment variable not contain the latex generator path.

Fix crash when tex generator is not found

---

src/core/control/ClipboardHandler.cpp
src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/Selection.cpp
src/core/control/tools/Selection.h
src/core/control/tools/VerticalToolHandler.cpp
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/model/Element.h
src/core/view/ElementContainerView.cpp
src/core/view/ElementContainerView.h
src/core/view/Repaintable.h
src/core/view/overlays/SelectionView.cpp
src/core/view/overlays/SelectionView.h
src/util/Range.cpp
src/util/include/util/Range.h

This PR split the selection tools (rectangle selection or region selection) into view+controller.
It also:
- simplifies and optimizes some of the code in tools/Selection
- optimizes the size of the areas repainted (upon input events)
(Note that tools/Selection only handles the selection process, tools/EditSelection is the tool handling the selection moving, resizing, copying and so on)
This is ready for a review for whoever feels like it.

Split tools/Selection into view/controller

---

src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/shaperecognizer/ShapeRecognizer.cpp
src/core/control/shaperecognizer/ShapeRecognizer.h
src/core/control/tools/StrokeHandler.cpp
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

When "shape recognizer" mode is enabled, and when a "pen stroke happens", the new code does the following:
- take the minimum and maximum values for both the X and Y axis
- if the bigger X value minus the smaller X value is less than the "minimum size" (and if this holds true for the Y values too), then it does not draw the shape
Note that some of the changes in the diff are due to `clang-format`
Closes #2531
Validation:
- Manual testing

Minimum size for shape recognizer now customizable

---

src/core/gui/PageView.cpp
src/core/gui/PdfFloatingToolbox.cpp
src/core/gui/PdfFloatingToolbox.h
src/util/include/util/raii/GObjectSPtr.h

Fixes #4298. See the commit message for details.

Fix PDF toolbox showing at the wrong position on Wayland

---

src/gui/inputdevices/MouseInputHandler.cpp
src/gui/inputdevices/StylusInputHandler.cpp

This is an attempt to fix the bug mentioned in #3983. After testing and debugging I realized that this bug not only appears if you use the middle mouse button, but also if you choose the right mouse button to open a text field.
When this function is used for other tools, releasing the pressed key should return to the previous tool (e.g. the eraser should disappear after releasing the middle/right mouse button). This is not the case with the text tool, since you not only want to create a text box, but also write something down right away.
Therefore, I decided to actually (permanently) select the text tool if you press the middle mouse button. If you think there is a better fix, jut let me know and I can have another look at it.

Fixed bug that closed text fields immediately after creating them with the middle mouse button. 

---

ui/main.glade

Fixes the id of both buttons for the MoveSelectionToLayer to fit the menu "Edit" (moved there from "Journal"), which got introduced in #4352

changes button id for MoveSelectionToLayer to fit menu

---

src/core/control/tools/VerticalToolHandler.cpp
src/core/control/tools/VerticalToolHandler.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/view/Mask.cpp
src/core/view/Mask.h
src/core/view/overlays/VerticalToolView.cpp
src/core/view/overlays/VerticalToolView.h
src/util/Range.cpp
src/util/include/util/Range.h

This PR splits tools/VerticalToolHandler into controller and view.
- reduces the buffer size
- reduces the repainted/rerendered areas
This is not battle ready yet: for performance reasons (also necessary in order to potentially allow for infinite pages at some point), the size of the buffer had to be reduced (it used to be half of the entire page).
The new (and imperfect) buffer is the size of the visible part of the page, but it starts just below (or ends just above, if ctrl is pressed) the event starting the VerticalTool. This works perfectly as long as the user ends their vertical shift whthin the current page.
In particular, in the following two situations, the buffer is to small:
1. If the view is in between pages: starting the vertical tool on the bottom page and dragging it all …

Split VerticalToolHandler into controller and view

---

src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelection.h
src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/EditSelectionContents.h
src/core/plugin/luapi_application.h

Outsourcing of the luaApi stuff of PR https://github.com/xournalpp/xournalpp/pull/2176.
The aim is to have a function `getStrokes` which serves as inverse of the existing `addStrokes`.
TODO:

[Lua API] extend getToolInfo for selection and add getStrokes as inverse of addStrokes

---

CONTRIBUTING.md
README.md
readme/Compile.md
readme/LinuxBuild.md
readme/MacBuild.md
readme/Releases.md
readme/WindowsBuild.md

This implements some of the documentation improvement suggestions proposed in #4295. Namely, it:
- Moves common build commands into a `Compile.md`
- Link to the branching strategy in CONTRIBUTING.md
- Move all documentation related to contributing to one place (CONTRIBUTING.md)
- Previously, links to the Wiki and generating documentation were hidden in the README.md
- Convert some inline paragraph lists to a bullet-point format that's easier to read
- Delegate some documentation to other sites
- For example, the current "Brew installation instructions" were outdated and incorrect. Now, we link to the website directly as to prevent any outdated instructions
- Rename triple backtick "bash" code snippets to "sh" (it is more semantically correct)
- Reestablish title hierarchy (in some files, …

Improve technical documentation

---

CMakeLists.txt
azure-pipelines/continuous-integration.yml
azure-pipelines/create-installers.yml
azure-pipelines/release.yml

Testing to build the MacOS version on a macos-11 vmImage while building for target >= 10.15.

Switch to macos-11 vmImage on dev Azure

---

src/control/settings/Settings.cpp
src/control/settings/Settings.h
src/gui/MainWindow.cpp
src/gui/MainWindow.h
src/gui/dialog/SettingsDialog.cpp
src/gui/inputdevices/TouchInputHandler.cpp
ui/settings.glade

This PR cherry-picks the commits from #3379 and #3497, since they are critical for users where inertial scrolling works badly. See e.g. https://github.com/xournalpp/xournalpp/discussions/4013

Backport inertial scrolling disabling

---

src/util/include/util/serializing/InputStreamException.h
src/util/serializing/InputStreamException.cpp

This fixes lots of warnings about this method declaration hiding a virtual overload.
```log
In file included from /home/user/projects/xournalpp/src/util/serializing/ObjectInputStream.cpp:9:
/home/user/projects/xournalpp/src/util/include/util/serializing/InputStreamException.h:24:25: warning: 'InputStreamException::what' hides overloaded virtual function [-Woverloaded-virtual]
virtual const char* what();
^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/exception.h:76:5: note: hidden overloaded virtual function 'std::exception::what' declared here: different qualifiers ('const' vs unqualified)
what() const _GLIBCXX_TXN_SAFE_DYN _GLIBCXX_NOTHROW;
```

Override std::exception::what rather than hiding virtual overload

---

src/control/zoom/ZoomControl.cpp

`fireZoomChanged` should only be called when the zoom has really changed. This is most notable when you pinch to zoom and have the "Start zoom after a distance ..." setting higher than `0\%`. The VertialSpace tool and the geometry tools from PR #4211 listen to zoom changes and currently need to redraw the mask when `fireZoomChanged` is called, regardless whether the zoom has really changed or not.

Only fireZoomChanged when zoom has changed

---

src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/EditSelectionContents.h

I haven't researched when this method became unused, but it's definitively dead code.

Remove dead copy selection code

---

src/core/control/LatexController.cpp

This PR fixes #4415. The reason for the changing position of the new LaTex element was that the coordinates of the selection were used as the new x and y position. The selection box has however a margin and is bigger than the actual LaTex element which caused an offset on completing editing. The commit in this PR updates the code to use the actual element coordinates of the old LaTex element fixing the bug.

Fix unwanted position change after editing LaTex elements

---

src/core/control/tools/PdfElemSelection.cpp
src/core/control/tools/PdfElemSelection.h
src/core/gui/LegacyRedrawable.cpp
src/core/gui/LegacyRedrawable.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/PdfFloatingToolbox.cpp
src/core/gui/PdfFloatingToolbox.h
src/core/model/PageHandler.cpp
src/core/model/PageHandler.h
src/core/model/PageListener.h
src/core/model/XojPage.h
src/core/pdf/base/XojPdfPage.h
src/core/pdf/popplerapi/PopplerGlibPage.cpp
src/core/view/overlays/PdfElementSelectionView.cpp
src/core/view/overlays/PdfElementSelectionView.h
src/core/view/overlays/SearchResultView.h
src/util/include/util/raii/CairoWrappers.h

This PR splits control/tools/PdfElemSelection into view+controller.
It also fixes a Segfault I encountered when testing, seemingly due to a datarace upon stroke creation in PdfFloatingToolbox.
With this PR, and all the others in this Splitting series, we should be able to start splitting gui/PageView into a view and a controller :-)
This is based on #4304 (only for PageView::deleteOverlayView()).

Split PdfElemSelection into View+Controller

---

src/util/include/util/serializing/Serializable.h
src/util/serializing/InputStreamException.cpp
test/unit_tests/util/ObjectIOStreamTest.cpp

We do not use this value in the InputStreamException.cpp and provide it in the Serializable.h using the `extern` declaration.
Considering that we can be sure the serializing utils are always up-to-date when rebuilding the project, there is no problem with having this value header-only for the few usages.
While at it, the value can be made const (as clang-tidy suggested).

Do not define in `XML_VERSION_STR` variable InputStreamException.cpp file

---

src/core/control/tools/EditSelection.cpp

This is an attempt to fix the bug mentioned in #4367.
The user who created this issue wanted to be able to use the hand tool to delete a selected item by clicking on the delete rectangle next to it. However, the hand tool should not be able to do this in the first place.
Still, I feel that the delete rectangle right next to the element can be a bit misleading. So I decided (as discussed in #4367) to simply not draw the "DeleteRect" when the hand tool is selected.

Removed the "DeleteRect" if the hand tool is selected

---

src/core/control/ClipboardHandler.cpp
src/core/control/Control.cpp

This fixes copying in  `svg` format into the clipboard and copying images from selections that are translated
Check by pasting into a drawing app like Inkscape
or by using `wl-paste --type image/svg > output.svg` on Wayland
I have also tested with gdk scale factor 2 using `GDK_SCALE=2 GDK_BACKEND=x11 ./xournalpp`

Fix copying images into clipboard

---

src/core/gui/XournalView.cpp
src/core/gui/toolbarMenubar/AbstractToolItem.cpp
src/core/gui/toolbarMenubar/AbstractToolItem.h
src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
src/core/gui/toolbarMenubar/ToolMenuHandler.h

Implements #2007, that is, switching colors by using the 0-9 number keys.
I tested it while using various tools and it works. It has no conflicts with the text tool (so, if you are writing inside a textbox the number `1`, the first color won't be selected). 
(Note that I could have used metaprogramming to shorten the code _a lot_ but I decided not to in the name of clarity, so right now there are a lot of `if` statements, as done in other parts of the codebase)

Implemented color switching by number hotkeys

---

src/core/control/ClipboardHandler.cpp

Fixes #3455. Fixes #2831. Fixes #3044, I think.

Fix clipboard pasting when missing owner-change signal

---

src/core/control/latex/LatexGenerator.cpp

This fixes an error introduced into master when merging the 
release-1.1 branch after releasing version 1.1.2.
Compare 5e439f58002058041fd8fa936b747b954a79b096
Test it by running 'PATH="" ./xournalpp' and clicking on the TeX
button
The crash was fixed for version 1.1.3 in #4345, but the fix 
didn't work when merged into master.

Fixup crash when TeX is not found

---

azure-pipelines/steps/build_mac.yml

- The libxml unpacking step was disabled already and there is no `libxml.tar.gz` in the `macos-10.15-jhbuild` branch anyway
- We build on Big Sur (11.7), so no need to get an older Ninja version than 1.11.1.
- Lua 5.4 is included in the MacOS Gtk blob. It should be found since a recent enough version of `cmake` is used on the BigSur image. No need to build it on Azure Pipelines.

Remove deprecated build steps on MacOS

---

src/core/control/ScrollHandler.cpp
src/core/control/ScrollHandler.h
src/core/control/ToolEnums.cpp
src/core/control/ToolEnums.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/sidebar/Sidebar.cpp
src/core/gui/sidebar/Sidebar.h
src/core/gui/sidebar/indextree/SidebarIndexPage.cpp
src/core/gui/sidebar/indextree/SidebarIndexPage.h
src/core/model/Document.cpp
src/core/model/LinkDestination.cpp
src/core/model/LinkDestination.h
src/core/pdf/base/XojPdfAction.h
src/core/pdf/base/XojPdfDocument.h
src/core/pdf/base/XojPdfPage.h
src/core/pdf/popplerapi/PopplerGlibAction.cpp
src/core/pdf/popplerapi/PopplerGlibAction.h
src/core/pdf/popplerapi/PopplerGlibDocument.cpp
src/core/pdf/popplerapi/PopplerGlibPage.cpp
src/core/pdf/popplerapi/PopplerGlibPage.h
src/core/pdf/popplerapi/PopplerGlibPageBookmarkIterator.cpp
src/util/include/util/gtk4_helper.h

This PR adds support for navigating to links contained in a PDF background file. Implements #1027.
* Alt-clicking on a link (both a URI or a link to another page) will open a popup.
* For a URI, the popup will show the URI, which can be clicked to open the default application for that URI (e.g., web browser for http/https, email client for mailto).
* For an internal link, the application will scroll to that page. If the page is missing, the "missing PDF page" dialog will be displayed.
This PR is a rebased version of #3851 which is a rebased version of #2660.

PDF goto link feature

---

src/core/gui/PageView.cpp

Fixes a build regression due to #4412.
We will be dropping support for 18.04 soon, but this failure also happens on 20.04, so we should fix the issue regardless.

Fix build failure on Ubuntu 18.04 and 20.04

---

src/core/view/background/GraphBackgroundView.cpp

Fixes this:
https://user-images.githubusercontent.com/17818041/209571911-38219acd-8f84-4a77-9548-67cb8445d401.mp4
Merging in 24 hours unless an objection is raised.

Fix border artefacts when writing close to the edge of a Graph background

---

src/core/control/jobs/RenderJob.cpp
src/core/control/jobs/RenderJob.h

Previously the entire widget would be repainted, causing a noticeable delay on electrophoretic displays. Solution suggested by @bhennion here: https://github.com/xournalpp/xournalpp/discussions/4494#discussioncomment-4371802

Repaint only areas instead of the entire widget

---

src/core/control/Control.cpp

Fixes #3368. See the commit description for the details.

Fix error handling in "Annotate PDF" menu option

---

src/core/control/tools/BaseShapeHandler.cpp

It's all in the title.
There are many places where the document's mutex is not locked when accessing/modifying the document. This PR simply plugs one of those instances that I forgot to deal with in #4137.
Merging in 24 hours unless an objection is raised.

Lock document's mutex upon adding stroke to layer in BaseShapeHandler

---

CMakeLists.txt

When using `Ninja` as the CMake Generator, diagnostics would fail to colorize. This fixes that. Significantly improves first time experience for new contributors.

fix: Color diagnostics now properly show with Ninja

---

src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
src/core/gui/toolbarMenubar/icon/ColorSelectImage.cpp

Fixes issue #4505
Ensure 'getNewToolIcon' is used when dragging the color select tool.
Ensure 'width' and 'height' fields of 'IconConfig' struct is initialized.

Fix crash when dragging color select to sidebar

---

ui/fillOpacity.glade
ui/main.glade
ui/settings.glade

Stock icons are deprecated since Gtk 3.10. They don't show up on Windows or MacOS any more.
I followed https://lazka.github.io/pgi-docs/Gtk-3.0/constants.html on how to replace the stock icon names.
Tested successfully on Windows 10 and Ubuntu 22.10 (where in my case the go-up and go-down icons look slightly different now). See icons in the sidebar in particular.

Replace deprecated stock icons by named icons

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/control/PageBackgroundChangeController.cpp
src/core/control/PageBackgroundChangeController.h
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/settings/SettingsEnums.cpp
src/core/control/settings/SettingsEnums.h
src/core/control/tools/StrokeHandler.cpp
src/core/gui/Layout.cpp
src/core/gui/Layout.h
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Closes #1343
I used `doc->isAttachPdf()` to determine if editing a "pdf" file (so empty last pages aren't created in PDF files), but I'm not sure if that is valid in all cases?
I also added the setting in the third section - is there a better place to put it or a better name?

Automatically create empty last page if last page is drawn on

---

windows-setup/xournalpp.nsi

*Only line 270 is related to this PR. It seems that there is a line ending issue with this file.* 🤔
This PR allows the Windows installer to write the program version to the uninstall registry entry, so [WinGet](https://github.com/microsoft/winget-cli) will be able to recognize the installed version of Xournal++.

Write program version to uninstall entry on Windows

---

src/core/gui/toolbarMenubar/ColorToolItem.cpp

I have been looking into issue #4519. I have not be able to reproduce. But by looking at how other dialogs are configured elsewhere, I guess 'gtk_window_set_trasient_for' and perhaps also 'gtk_window_set_position' was missing for the dialog.
As I understand it's up to the windows manager of a given system to place the window accordingly to these hints.
Hopefully somebody with a window build and a dual screen setup can try this out.

Hint placement of color select dialog

---

src/core/control/GeometryToolController.cpp
src/core/control/layer/LayerController.cpp
src/core/control/layer/LayerController.h
src/core/control/tools/BaseShapeHandler.cpp
src/core/control/tools/SplineHandler.cpp
src/core/control/tools/StrokeHandler.cpp
src/core/control/xojfile/LoadHandler.cpp
src/core/model/XojPage.cpp
src/core/model/XojPage.h

This PR solves #4032 
`getSelectedLayer()` created a layer if none was existent before.
This PR changes the XojPage, so that there is always minimum one valid layer.
I think this should be mostly finished, but I still have to check if there are any exception cases.

Ensure layers are always in a valid state

---

src/core/audio/PortAudioConsumer.cpp
src/core/audio/PortAudioProducer.cpp
src/core/control/Control.cpp
src/core/control/XournalMain.cpp
src/core/control/jobs/BaseExportJob.cpp
src/core/control/jobs/SaveJob.cpp
src/core/control/latex/LatexGenerator.cpp
src/core/control/settings/MetadataManager.cpp
src/core/gui/dialog/ExportDialog.cpp
src/core/gui/dialog/LanguageConfigGui.cpp
src/core/plugin/PluginController.cpp
src/util/PathUtil.cpp
src/util/serializing/ObjectInputStream.cpp
test/unit_tests/model/ColorPaletteTest.cpp
test/unit_tests/util/ElementRangeTest.cpp
test/unit_tests/util/ObjectIOStreamTest.cpp
test/unit_tests/util/TinySmallVectorTest.cpp

This slightly improves the exception handling code by catching by const reference, as per [E.15](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference).
Two other inconsistently named exceptions `except` and `err` were also renamed to `e`. Some east-consts were converted to west-consts, as this codebase seems to do.

Catch by const reference

---

src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/Selection.cpp
src/core/control/tools/StrokeHandler.cpp
src/core/control/tools/StrokeStabilizer.cpp
src/core/model/Stroke.cpp
src/core/plugin/Plugin.cpp
src/core/plugin/Plugin.h
src/core/plugin/luapi_application.h

This improves consistency with the rest of the codebase. I think this also improves compatability, since it's in #4092 as well

Use `std::numeric_limits` instead of macros

---

src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp

Keep Toolbar alive until ToolbarAdapter is destroyed

Fix SEGV if app closed while toolbar customization was open

---

src/core/control/jobs/RenderJob.cpp
src/core/gui/LegacyRedrawable.cpp
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/model/Compass.cpp
src/core/model/Setsquare.cpp

As discussed with @bhennion (https://github.com/xournalpp/xournalpp/discussions/4071). Evolution of https://github.com/xournalpp/xournalpp/pull/4492.
Padding can be removed without introducing rendering artifacts. Removing padding completely causes artifacts when drawing ellipses.
Keeping the area to be redrawn small speeds up xournal++ when used with electrophoretic displays.
Tested with most tools on three zoom levels and three line widths. More extensive testing is welcome.

Remove rerender padding

---

src/core/control/PageBackgroundChangeController.cpp
src/core/control/pagetype/PageTypeMenu.cpp
src/core/control/pagetype/PageTypeMenu.h

This is an attempt to fix #4142 by adding a check that straight-up avoids the crash by checking if the background on the current document is the Copy type, and refusing to set the background if that's the case.

Do nothing if the page background is 'Copy'

---

src/core/control/CompassController.h
src/core/control/GeometryToolController.h
src/core/control/SetsquareController.h

This PR makes the destructor of GeometryToolController virtual, thus fixing a plausible memory leak.

Fix non-virtual destructor of GeometryToolController and derived class

---

src/core/gui/dialog/AboutDialog.cpp

Removes another instance of using raw C arrays

chore: Replace `sprintf` with `PlaceholderString` in `AboutDialog.cpp`

---

.gitignore

- `.*DS_Store` can be `.DS_STORE` and isn't autotools specific
- `*~` isn't autotools specific
- `*/.vscode/` is redundant
- `.idea` can have a trailing slash
- `src/**/.DS_Store` entries are redundant
cc @Febbe wanted to get your OK since you authored e16faa7bcdbceb49d8a4d15e07df3fd963552c85 - in theory both VSCode entries should behave the same, but maybe there was a Git bug or troubles with cached untracked files? Maybe it's fixed by now

chore: Improvements to `.gitignore`

---

src/core/gui/sidebar/previews/base/SidebarLayout.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.h
src/core/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp
src/core/gui/sidebar/previews/page/SidebarPreviewPages.cpp

SidebarPreviewBase attribute preiews (vector of SidebarPreviewBaseEntry pointers) has been refactored to a vector of unique_ptr of SidebarPreviewBaseEntry

Refactor SidebarPreviewBase to use std::unique_ptr

---

src/core/gui/XournalView.cpp

Until now there was no way to scroll an entire page using vim keybindings, SHIFT + DOWN_ARROW did work, but SHIFT + j didn't do anything. With this pr it is now possible to use SHIFT + j to scroll a page down and SHIFT + k to scroll a page up.

Make it possible to scroll an entire page with vim keybindings

---

src/core/gui/toolbarMenubar/ColorToolItem.cpp

Fix 'Quality of life changes for Color PIcker #4569'
The dialog now opens up with the current selected color. By right clicking on the color button - you can choose 'customize' which open up the color palette at the hex values of the selected color. The dialogs used for this is the GTK default dialogs for picking colors - they don't behave excatly as google docs picker.

Color tool opens with current color selected

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/control/FullscreenHandler.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/settings/SettingsEnums.h
src/core/control/settings/ViewModes.cpp
src/core/control/settings/ViewModes.h
src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/dialog/SettingsDialog.h
ui/settings.glade

This PR solves the `automatically hide the sidebar, menubar, etc` TODO in #4456 (as well as #2773)
This PR introduces better view-modes. This means the default-, fullscreen- and presentation mode are now refactored to being `view modes` in the settings, with customizable attributes (hide/show widgets & go into fullscreen).
According attributes can be changed in the settings under `View` (where previously similar attributes were shown, but had no effect).
This implementation not only fixes the  `automatically hide the sidebar, menubar, etc` TODO in #4456, but also allows for easy future changes with these modes. Also custom additional modes might be implemented in future.

Preset view modes

---

src/core/control/Control.cpp
src/core/gui/XournalView.cpp
ui/main.glade

Solves one task from #4456
The accelerator `F5` previously used to enter the presentation mode now also leaves it. Using `esc` to leave the presentation mode (if there is no selection to cancel) only seems confusing.
Also I removed some further code for leaving fullscreen in `XournalView::onKeyPressEvent`, which doesn't seem to do anything. Again using esc only seems confusing here (e.g. editing stuff in fullscreen and accidentally leaving it while cancelling a selection).
*sry for this PR looking kinda messy with all the force-pushing etc...*

Leave Fullscreen / Presentation mode

---

src/core/control/Control.cpp
src/core/control/layer/LayerController.cpp
src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelection.h
src/core/gui/XournalView.cpp

This requires #4158 that requires fewer explicit redraws when layers are deleted or their visibility is modified. Addresses #4580 in combination with #4158. This reduces the number of page repaints required. Full repaints are still used upon
- finalisation of text edits
- layer changes
- initialisation
TODO:

Remove or shrink unnecessary page rerender calls

---

src/core/control/jobs/RenderJob.cpp
src/core/control/jobs/RenderJob.h

Fixes #4555 
The issue came from the use of `cairo_surface_set_device_scale` on the rendering masks. Replacing it with calls to `cairo_scale` fixed poppler's behaviour. Let me try to explain why.
`cairo_surface_set_device_scale` is supposed to tell a cairo surface that it'll be used in a window with a certain GDK_SCALE value (so HiDPI kinda stuff). In practice, this device scale is very handy, as most operations can then be made without ever caring about the DPI scaling.
Now, I (unknowingly) perverted this function and used it for mask via `cairo_surface_set_device_scale(surf, zoom * dpiScaling, zoom * dpiScaling)`. This works well, except when Poppler is involved... The reason lies in Poppler's screen rendering optimizations (see [the …

Fix latex' thin lines

---

src/core/control/tools/BaseShapeHandler.cpp
src/core/control/tools/BaseShapeHandler.h
src/core/control/tools/InputHandler.h
src/core/control/tools/SplineHandler.h
src/core/control/tools/StrokeHandler.cpp
src/core/control/tools/StrokeHandler.h
src/core/gui/PageView.cpp
src/core/gui/inputdevices/PenInputHandler.cpp
src/core/model/LineStyle.cpp
src/core/model/LineStyle.h
src/core/model/Stroke.cpp
src/core/model/Stroke.h
src/core/view/Mask.cpp
src/core/view/Mask.h
src/core/view/overlays/BaseStrokeToolView.cpp
src/core/view/overlays/BaseStrokeToolView.h
src/core/view/overlays/StrokeToolFilledHighlighterView.cpp
src/core/view/overlays/StrokeToolFilledHighlighterView.h
src/core/view/overlays/StrokeToolFilledView.cpp
src/core/view/overlays/StrokeToolFilledView.h
src/core/view/overlays/StrokeToolView.cpp
src/core/view/overlays/StrokeToolView.h
src/util/Range.cpp
src/util/include/util/Range.h

Follows #4137.
This PR splits tools/StrokeHandler into a View and a Controller. It also optimizes the rendering costs ~~and protects the data with a mutex (see #3579)~~.
~~**Edit:** the CI failing is due to GCC 8 not handling `std::transform_reduce`. Will be fixed with #4160~~   done

Split tools/StrokeHandler into View-Controller

---

src/core/control/tools/EraseHandler.cpp
src/core/model/PathParameter.h
src/core/model/Stroke.cpp
src/core/model/eraser/ErasableStroke.cpp
src/core/model/eraser/ErasableStroke.h
src/core/view/ErasableStrokeView.cpp
src/core/view/ErasableStrokeView.h
test/unit_tests/model/ErasableStrokeTest.cpp

This PR replaces #4612, with a more precise computation of the rerendered boxes.

Fix rendering artefacts in standard eraser - 2nd try

---

src/core/control/xojfile/LoadHandler.cpp

Ensure char arrays are null terminated before they are used to build a std::string. Help fix one of the issues valgrind complained about.

Ensure char arrays are null terminated

---

src/core/gui/MainWindow.cpp

gtk_container_get_children returns a GList which was newer deallocated In this context the return value is used as a boolean - which always is true and therefore redundant.

Fix GList memory leak

---

src/core/control/XournalMain.cpp
src/core/control/xojfile/LoadHandler.cpp
src/core/control/xojfile/LoadHandler.h

Fix #4584
Now we give error message on the console stderr, and exit the process with -2.
Note if we return -2 instead of exiting - the gui startup and try to do the exporting ???
This fix ensure we dont segfault. But what should the correct behavior be?

Fix #4584 segfault when exporting from cli with missing bg

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/gui/sidebar/previews/base/SidebarPreviewBase.cpp

Continuation of  #4611. I'm splitting this one off as suggested by @bhennion to keep the discussion focused and get some feedback.
As before, I would like to avoid rerendering the entire page after most changes for performance reasons. Instead of using the general-purpose implementation `DocumentHandler` I introduce a similar mechanism in `Control`, which is only used for notifying a subset of `DocumentListener` instances (at the moment all instances of subclasses of `AbstractSidebarPage`).
This approach does not interfere with the existing observer pattern or the general rerendering logic.

Control::checkChangedDocument: notify page changes to subset of listeners

---

src/core/control/ToolHandler.cpp
src/core/control/ToolHandler.h
src/core/control/tools/BaseShapeHandler.cpp
src/core/control/tools/BaseShapeHandler.h
src/core/control/tools/InputHandler.h
src/core/control/tools/SplineHandler.cpp
src/core/control/tools/SplineHandler.h
src/core/control/tools/StrokeHandler.cpp
src/core/control/tools/StrokeHandler.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/inputdevices/PenInputHandler.cpp
src/core/gui/inputdevices/PenInputHandler.h

Various tools are filtering tap events (e.g. to show the floating toolbox).
This PR removes code duplication and makes tap events fully supported by PenInputHandler (which handles every pointing devices -- mouse, stylus, touch).
~~This PR is base on #4159.~~ merged since

Unify tap filtering across tools

---

src/core/control/jobs/BaseExportJob.cpp
src/core/control/jobs/BaseExportJob.h
src/core/control/jobs/CustomExportJob.cpp
src/core/control/jobs/CustomExportJob.h
src/core/control/jobs/PdfExportJob.cpp
src/core/control/jobs/PdfExportJob.h

My first idea was to remove the use of new/delete for ExportType object. Why do we use dynamic allocation for this? I search the git history for the PR where it went in, and stubbled over the following comment:
https://github.com/xournalpp/xournalpp/pull/594#discussion_r243860463
And therefore changed it to not use dynamic allocation for the ExportType.

Simplify custom export job

---

src/core/control/jobs/BaseExportJob.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/model/Document.cpp
src/core/model/Document.h
src/util/SaveNameUtils.cpp
src/util/include/util/SaveNameUtils.h
test/unit_tests/util/SaveNameUtilsTest.cpp

This PR implements the requested enhancement in #2897 
This PR introduces the possibility to set a default name for exporting pdfs. Among others, this solves the issue of overwriting the background-pdf. Wildcards are used for allowing some file-related naming and use the `%{...}` syntax.
Wildcards | Description
---|---
name | original pdf name
date | current date
time | current time
The default pdf-name will be `%{name}_annotated.pdf`.

Default pdf-export name with wildcards

---

src/core/model/Document.cpp

The current implementation of `createSaveFilename`(#4599) causes the suggested filename in the save dialog to be ".pdf" whenever a PDF is opened. This fixes the problem and also removes the pdf extension as the file will be saved as "*.xopp" instead of "*.pdf.xopp".

Fix the filename suggestions when annotating PDFs

---

src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/settings/SettingsEnums.cpp
src/core/control/settings/SettingsEnums.h
src/core/gui/XournalppCursor.cpp
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

This only applies when used with a stylus. Generalisation of #3940.
I've added a setting to the "view" pane. This one might make more sense in the "stylus" pane.

Make visibility of eraser cursor configurable

---

src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHandler.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHandler.h

Also changed to RAII in ToolbarDragDropHandler as it was using the toolbarWidgets of MainWindow.

Use RAII MainWindow toolbarWidgets

---

src/core/control/tools/ArrowHandler.cpp

So far, the size of arrow heads is determined purely by the line width,
which is good for medium sized and long arrows. For very small arrows,
this leads to "interesting effects", especially for double headed
arrows.
To avoid these effects, scale the arrow head by the line length for
short arrows, i.e.: make the heads no larger than 0.4 * line length.
This suites double arrows as well, and besides, 0.4 is roughly
1 - (sqrt(5) - 1) / 2 which is the golden choice.

scale small arrow heads by line length

---

src/core/gui/ToolitemDragDrop.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.h
src/core/gui/toolbarMenubar/icon/ToolbarSeparatorImage.cpp
src/core/gui/toolbarMenubar/icon/ToolbarSeparatorImage.h
ui/toolbarCustomizeDialog.glade

Fixes #4644 
This PR adds an icon for the spacer to the toolbar customization dialog (painted in `ToolbarSeparatorImage.cpp` as a variant of the separator icon) and allows for drag&drop for the spacer.

Add spacer for drag&drop in toolbar customization

---

src/core/plugin/Plugin.cpp
src/core/plugin/luapi_application.h

At some places the API currently prints a `g_warning` and returns for error handling. At other places `luaL_error` is being used. This is supposed to unify error handling.
Still open:
Currently this is inconsistent, so we should discuss this and unify the style in this aspect as well.
And I think we should document somewhere how errors in lua should be thrown so that this is specified somewhere. (Error handling should be consistent throughout the API)
**Note:** Please check if all of the `g_warning`s I replaced should really throw an error. The reasoning on my side was, if we throw a lua error, we can handle the error on the lua side (`pcall` -> `if`) if we just do `g_warning` the lua side won't even notice there as an error (if we not return some special value which is not always the …

[luaAPI] refactor error handling

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/gui/MainWindow.cpp
src/core/gui/toolbarMenubar/PluginToolButon.cpp
src/core/gui/toolbarMenubar/PluginToolButton.h
src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
src/core/gui/toolbarMenubar/ToolMenuHandler.h
src/core/plugin/Plugin.cpp
src/core/plugin/Plugin.h
src/core/plugin/PluginController.cpp
src/core/plugin/PluginController.h
src/core/plugin/luapi_application.h

Fixes #4669. Fixes #2936. Fixes #2431. Also addresses #3669.
This PR allows registering toolbar buttons (with any ID and any icon in the icon theme) that can be added to any toolbar.
These custom tools (executing plugin callback functions) can be added to the toolbar either by customizing the toolbar in the GUI or by editing `toolbar.ini`. 
The plugin adds the toolbar via e.g. 
```lua
app.registerUi({callback ="blueDashedPen", toolbarId="CUSTOM_PEN_1", iconName="bluePenIcon"})
```
It's also possible to combine adding a toolbar button with adding a menu entry:
```lua
app.registerUi({["menu"] = "Mirror strokes horizontally", ["callback"] = "cb", ["accelerator"] = "<Control>t", ["toolbarId"] = "MIRROR", ["iconName"] = "view-mirror-symbolic"})
```
Here `view-mirror-symbolic` is an icon that …

feature: add toolbar buttons via plugins

---

src/core/control/jobs/SaveJob.cpp

During save we try to make a backup of the current file. This fails if there is no write permission to the file, and before this PR we returned without notifiy the user.

Fix #4675 No error on save if we don't have write permission

---

azure-pipelines/clang-format-applied.yml

- Added a check, if the calculated BaseCommitHash is empty.

Fix up git clang-format in the pipeline

---

src/util/Color.cpp
src/util/include/util/Color.h

Fixes a regression introduced in 727730512cd2ad85d93184816166f25201095da8 by setting the alpha channel of `Colors::black` (used as a background color for the TeX dialog when the text color is light) to `0xff`. This was incompatible with `rgb_to_hex_string`, that turned it into `#ff0000` instead of `#000000`. 
Bad: 
Good:

Fix dark background color of tex dialog

---

src/config-debug.h.in
src/core/control/PdfCache.cpp
src/core/control/PdfCache.h
src/core/control/jobs/RenderJob.cpp
src/core/control/jobs/RenderJob.h
src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/XournalView.cpp
src/core/gui/XournalView.h
src/core/model/eraser/ErasableStroke.cpp
src/core/model/eraser/ErasableStroke.h
src/core/view/ErasableStrokeView.cpp
src/core/view/ErasableStrokeView.h
src/core/view/GeometryToolView.cpp
src/core/view/Mask.cpp
src/core/view/Mask.h
src/core/view/StrokeView.cpp
src/core/view/overlays/BaseStrokeToolView.cpp
src/core/view/overlays/StrokeToolFilledHighlighterView.cpp
src/core/view/overlays/StrokeToolView.cpp
src/core/view/overlays/VerticalToolView.cpp

This PR makes use of view::Mask for the PageView::buffer, as well as for the mask in StrokeView and ErasableStrokeView and the cache in PdfCache.
It also uses `cairo_surface_create_similar()` instead of `cairo_image_surface_create()` for those surface, thus using the most suitable Cairo backend available. This should improve performances (closes #4179).
The emoji part of #3692 is also fixed, and the issue underlying #4555 (ugly-fixed with #4566) is cleaned up: no more unsuitable use of `cairo_surface_set_device_scale()`.
The 3 commits are self contained and can be reviewed separately.

Use view::Mask for buffers

---

CMakeLists.txt
src/core/gui/menus/menubar/Menubar.cpp
src/core/gui/menus/menubar/Menubar.h

also fixes the cmake flags so that configuring with -DENABLE_PLUGINS=off actually compiles without plugins (whether Lua is present or not)

Hide plugin menu when compiling with -DENABLE_PLUGINS=off

---

src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/PageView.cpp
src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHandler.cpp

Now all objects allocated with `new` has been changed to use `std::unique_ptr` to ensure their resources are deallocated with MainWindow goes out of scope.

Use RAII for resource allocation in MainWindow

---

src/core/control/Control.cpp
src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelection.h
src/core/control/tools/EditSelectionContents.cpp
src/core/control/tools/EditSelectionContents.h
src/core/undo/UndoRedoHandler.cpp
src/core/undo/UndoRedoHandler.h

More clean up. Also `UndoRedoHandler::removeUndoAction` never called so now removed.

Use UndoActionPtr instead of UndoAction* for EditSelection methods

---

src/core/control/Control.cpp
src/core/control/PageBackgroundChangeController.cpp
src/core/gui/dialog/PageTemplateDialog.cpp

Some dialogs was allocated on heap other on stack. I have now align them to be allocated on stack. The benefit is that we then don't need to explict deallocate them.

Don't allocate dialogs on heap

---

azure-pipelines/util/build_appimage.sh

This PR should fix AppImage updates (which never worked properly). Merging in 24 hours if no objections are raised.

Fix filename pattern for AppImage update info

---

azure-pipelines/jobs/release_ubuntu.yml
azure-pipelines/util/build_appimage.sh

According to the [appimage.org docs](https://docs.appimage.org/packaging-guide/optional/updates.html),
releases should always update to releases,
nightlies always to nightlies, etc. (“channels”)
Until now it was only possible to update to the latest (stable) release, regardless if it was a nightly or a stable build.

Make AppImage update respect channels

---

src/core/control/ExportHelper.cpp
src/core/control/latex/LatexGenerator.cpp
src/core/control/tools/ImageHandler.cpp
src/core/control/xojfile/LoadHandler.cpp
src/core/gui/MainWindow.cpp
src/core/gui/XournalppCursor.cpp
src/core/model/Document.cpp
src/core/model/Document.h
src/core/model/Image.cpp
src/core/model/TexImage.cpp
src/core/model/TexImage.h
src/core/plugin/luapi_application.h
src/core/view/TextView.cpp

Use RAII - to get rid of many `g_object_unref`

More RAII cleanup

---

src/core/gui/MainWindow.cpp
src/core/gui/PdfFloatingToolbox.h

#4436: PDF text could not be copied with a shortcut.
A Ctrl-C routine has been added to dive into the PDF Floating Tool Box and make it copy (if applicable) without needing to click the corresponding button.
(Function copyTextToClipboard() was changed from private to public in order to do this.)

Enhancement #4436: Made Ctrl-C Shortcut to PDF Text Copy Functionality

---

src/core/control/LatexController.cpp
src/core/control/LatexController.h

I have removed some `double` to `int` conversion compiler warnigns. Use constexpr and anonymous namespace for some const parameters.

Cleanup latexcontroller

---

src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/PageView.cpp
src/core/gui/SearchBar.cpp
src/core/gui/XournalView.cpp
src/core/gui/inputdevices/KeyboardInputHandler.cpp

Fixes #977 (comments in the discussion). Supersedes #4784 
- Let the key-press-event and key-release-event for the main window propogate the event to the focus widget and up the focus container chain until a widget handles the event
- Make the keyboard input handler only direct the GdkKeyEvents to the XournalView's handler
- Make the XournalView's handler first let the current page handle the key event for tools owned by the page
(textEditor, inputHandler, verticalSpace) and then
handle selection, scrolling, page operations and color switching on its own
The main improvement relates to the fact that now keyboard accelerators can be used (for plugins and menus) that would otherwise make the text editor unfunctional.

Refactor key event handling

---

src/core/control/XournalMain.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/sidebar/Sidebar.cpp

This PR fixes the "File bug report" dialog: it seems a dialog is supposed to pop-up on startup, when an errorlog is found.
This was broken (the errorlog files never matched the applied name filter, so the dialog never appeared).
This fixes that, as well as a couple of papercuts (encountered while working on #4796, but whose fix should be merged before that)
1. Failing assert when closing the Insert Pdf Page dialog via Escape, Alt+F4 or window-close icon.
2. Fix conversion warnings in Settings.cpp

Fix "File bug report" dialog and more

---

src/core/plugin/luapi_application.h

the type parameter of `applib_getStrokes` was documented as `layer` or `selection` but the implementation used `*L*ayer` and `selection` (see [#4528 (Comment)](https://github.com/xournalpp/xournalpp/pull/4528#issuecomment-1519088312)).
This PR fixes this inconsistency.

fix the casing of the parameters of getStrokes 

---

src/core/control/tools/SplineHandler.cpp

superseeds #4824 
fixes #4822
Already discussed in #4824.
Merging in 24 hours.

Fix Spline handler crash after hitting Escape and starting a new spline

---

azure-pipelines/steps/build_mac.yml

The new Gtk blob uses Gtk 3.24.37 and is split into only two files.

Update for new MacOS Gtk blob

---

src/core/gui/XournalppCursor.cpp

Don't know why it's needed to check if mouse button is pressed to change the cursor icon.
Fixes #4851

Fix cursor not immediately changing issue for vertical space tool

---

src/core/gui/XournalView.cpp

In the case that you insert a page and then scroll further down and click undo, you will no longer be scrolled down an additional page. 
This occurred because the index of the current page decreased, since a page was deleted before it.
- have more then one page
- insert a page somewhere (not at the end)
- scroll to a page below the inserted page, that is not the end
- undo insert page
-> you are scrolled one page down / the page below the current page is selected
- whatever page you scrolled to before undoing the inserted page is re-selected / scrolled to
- this means you are pulled to the top of whatever page you where viewing, since it is re-selected
- which was the previously intended behavior
- when undoing insert page while on another page your view doesn't change - no automatic …

Fix for scroll bug when undoing insert page

---

desktop/com.github.xournalpp.xournalpp.desktop

This allows creating a new window from Gnome dash
by middle-click or Ctrl+click or right-click -> "New Window". 
Compare [relevant Gnome shell code](https://github.com/GNOME/gnome-shell/blob/4b79eec45aba4755b4fb1be1b530552ac6e245cd/src/shell-app.c#L640-L714) and [desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)
Fixes #4759 
Supersedes #4764 which was not the correct solution.

Add desktop file entry SingleMainWindow=false

---

README.md

The Arch Linux [community] repository recently [merged](https://archlinux.org/news/git-migration-announcement/) to [extra]. Update README.md to reflect this change.

Update Arch Linux package info

---

src/core/control/ToolHandler.cpp
src/core/control/jobs/Scheduler.cpp
src/core/control/settings/PageTemplateSettings.cpp
src/core/control/tools/PdfElemSelection.h
src/core/control/xojfile/LoadHandlerHelper.cpp
src/core/control/xojfile/SaveHandler.cpp
src/core/gui/PageView.cpp
src/core/gui/PdfFloatingToolbox.h
src/core/gui/dialog/SelectBackgroundColorDialog.cpp
src/core/gui/sidebar/Sidebar.cpp
src/core/gui/widgets/SpinPageAdapter.cpp
src/core/model/BackgroundConfig.h
src/core/model/Element.cpp
src/core/model/Stroke.cpp
src/core/pdf/base/XojPdfPage.h
src/core/undo/UndoRedoHandler.cpp
src/core/view/background/OneColorBackgroundView.cpp
src/util/include/util/PlaceholderString.h
src/util/serializing/HexObjectEncoding.cpp
src/util/serializing/ObjectInputStream.cpp

GCC 13 is much more strict about avoiding accidental inheritance of other headers
It's now necessary to include \<cstdint\> for uint*_t types, rather than \<cinttypes\>

Fix header includes for GCC 13

---

src/core/control/tools/ImageHandler.cpp
src/core/control/tools/ImageHandler.h
src/core/plugin/luapi_application.h

Adds the Lua function `app.addImagesFromFilepath`. The function allows to add images to the document by specifying a path in the filesystem (required) and the desired position on the current page (optional).
This is the first step discussed in https://github.com/xournalpp/xournalpp/issues/4529
TODOs/discussion:
Of course the file might get deleted after our check but that should be no problem as we don't rely on this check, it's only to be able to return a more specific error.
The reason why I didn't add this in the first place is that with the current implementation re-using `imgHandler.insertImage`, I don't know how to get/identify the image after inserting it to be able to work with it.

Lua api add images from filepaths

---

CMakeLists.txt
src/core/control/CrashHandler.cpp
src/core/control/CrashHandlerUnix.h

This PR adds useful information to the CrashLog, to help with bug reports.
The added pieces of information are:
1. Xournal++ and Gtk versions
2. Every log message issued via g_message, g_critical, g_debug and so on
Implementing 1. was pretty straghtforward. Implementing 2. meant using g_log_set_default_handler() to record every such message.

Improve CrashLog

---

src/util/Stacktrace.cpp

Define PATH_MAX if undefined, to address Hurd build failure.
Gbp-Pq: Name 0001-Hurd-PATH_MAX.patch

Hurd PATH_MAX

---

AUTHORS
copyright.txt

Updated the list of authors obtained in raw form via 
```
git shortlog -se   | perl -spe 's/^\s+\d+\s+//' > AUTHORS_raw
```
I have removed every member of the developer team (listed on the top) from the list of contributors (listed below) and removed duplicates and bots. 
Here is the diff between AUTHORS_raw and AUTHORS:
[diff.txt](https://github.com/xournalpp/xournalpp/files/10315780/diff.txt)

Update authors list

---

src/core/control/XournalMain.cpp
src/util/PathUtil.cpp
src/util/include/util/PathUtil.h

This PR fixes the following problems that occur when an errorlog is present:
- The errorlogs directory doesn't open for the flatpak and snap package (since `nautilus`, `dolphin` and `konqueror` cannot be opened directly; rather `xdg-open` should be used)
- The errorlogs directory and errorlogs don't open on Windows (since the `start` command must use a title when there are quotes around the filename)

Fix errorlog opening

---

src/core/control/Control.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

This feature can be enabled from `Edit>Preferences>View>Show page number in title bar`. It allows the user to see the current page number in the titlebar. This comes in handy when the user has toggled off `View>Show Toolbars`, but wish to see the current page number they are in, without having to go through the trouble of toggling toolbars back on.
MuPDF has it by default, and I thought it would be a nice little feature to incorporate into Xournal++ as well.

Optionally Display Current Page Number on the Titlebar

---

azure-pipelines/release.yml
azure-pipelines/steps/install_deps_ubuntu.yml

The release builds on Ubuntu and Debian were compiled without gtksourceview. This PR fixes this problem for future releases.

Install libgtksourceview-4-dev on Azure pipelines

---

plugins/FitToContent/main.lua
plugins/FitToContent/plugin.ini

The idea behind this, is to be able to prototype small images for e.g. LaTeX documents (quick and dirty drawing before probably time consuming tikzing the drawing).
Caveat: Only works with strokes, no images and no text boxes are taken into account. Might change in the future, but for this we need get/add api-functions for these types.
Note: Created this as draft since I came up with this just right now. I want to avoid this being merged without thinking about this again. So for me most interesting right now is, what you think about this idea in general. And if you've got ideas regarding the decisions usin
1.  `getStrokes` instead of `toolInfo` and
2. how to handle the padding (reason behind this is we need something to get the whole stroke, as without padding thick strokes are being cut …

Add plugin to fit the page size to the content/selection

---

src/core/control/PageBackgroundChangeController.cpp
src/core/control/PageBackgroundChangeController.h
src/core/control/pagetype/PageTypeHandler.cpp
src/core/control/pagetype/PageTypeHandler.h
src/core/control/pagetype/PageTypeMenu.cpp
src/core/control/pagetype/PageTypeMenu.h
src/core/control/settings/PageTemplateSettings.cpp
src/core/control/settings/PageTemplateSettings.h
src/core/control/xojfile/LoadHandler.cpp
src/core/control/xojfile/SaveHandler.cpp
src/core/gui/dialog/PageTemplateDialog.cpp
src/core/gui/dialog/PageTemplateDialog.h
src/core/model/PageType.cpp
src/core/model/PageType.h
src/core/view/background/BackgroundView.cpp

This placeholder value was really just that. This PR replaces all
occurences of a PageType instance with format ::Copy by an std::nullopt.
In every place where a PageType could have format ::Copy, the PageType
is replaced by an std::optional<PageType> (this only happens in
dialogs and menus).
This was formerly part of #4508. It has been split of to ease the reviewing process.
This is ready for review.

Remove PageTypeFormat::Copy

---

src/CMakeLists.txt
src/util/Util.cpp
src/util/include/util/raii/CairoWrappers.h

- `execInUiThread` was UB in case of MT (explicitly Windows+MSVC)
- `CairoWrappers` specialisations were incompatible to c++17 (function pointers are not constexpr.)

used deletion function in execInUiThread + c++17 comp. in CairoWrappers

---

cmake/include/GitRepo.cmake

The bug reports we received didn't use the bug report template, so we had to ask a lot of follow up questions that would be answered when filling out the template. This PR fixes that problem.

Make bugreports use bug report template

---

src/core/plugin/luapi_application.h

Fix https://github.com/xournalpp/xournalpp/pull/4832 once again. Spelling mistake got reintroduced in https://github.com/xournalpp/xournalpp/pull/4837.
Especially for the PRs which branch of the master before this fixup got included, we need to be careful not to reintroduce this spelling mistake again. Namely these are (as far as I found some):
- https://github.com/xournalpp/xournalpp/pull/5029
- https://github.com/xournalpp/xournalpp/pull/4884

fix the casing of the parameters of getStrokes (2)

---

src/core/control/ToolEnums.cpp
src/core/control/ToolEnums.h
src/core/control/ToolHandler.cpp
src/core/control/ToolHandler.h
src/core/control/settings/ButtonConfig.cpp
src/core/control/settings/ButtonConfig.h
src/core/control/settings/Settings.cpp
src/core/gui/dialog/ButtonConfigGui.cpp
src/core/gui/dialog/ButtonConfigGui.h
ui/settingsButtonConfig.glade

I've been sitting on this change for while. I saw that someone else requested this feature in #4815, so I decided to finally complete it.
Here's the preferences dialog with the new combobox. It will only show when "Pen" is selected as the default tool, since this is the only tool that supports different line styles AFAIK:
Suggestions/improvements welcome as this is my first PR on this project and I have limited C++ experience :smile:

Add stroke type/line style to default tool settings

---

azure-pipelines/steps/build_linux.yml

I don't know if this was the issue. `RelWithDebInfo` defines NDEBUG and I could not find code, which overrides this behavior.

Add space between variable and "}}" for pipeline variables

---

src/core/gui/sidebar/Sidebar.cpp
src/core/gui/sidebar/Sidebar.h

The advantage over the former approach of using a std::list is the random access and the fast calculation of indices. And using an iterator over a pointer is the more modern way of cpp for this case. We also can rapidly calculate the index of the current page via std::distance.
The downside of using a std::vector is that insertion might be slow (if the vector needs to be copied), but as there are only a few pages and we can preallocate space for the vector this should be no huge disadvantage.
The big downside of using an iterator over a pointer is iterator invalidation. But as pages isn't exposed to the outside, we can ensude in Sidebar.cpp that on each possible iterator invalidation, the iterator is refreshed.
Also when using a pointer we would need to refresh the pointer on e.g. …

Refactor sidebar to use vector+iterator instead of list+pointer

---

plugins/LayerActions/main.lua
src/core/gui/sidebar/Sidebar.cpp
src/core/gui/sidebar/Sidebar.h
src/core/plugin/luapi_application.h

Adds two lua api functions to set and get the index of the currently active page of the sidebar.  This now is possible due to #5030 and will fix #4394 since now we can
- obtain the currently active page
- set the sidebar into the state needed for the sidebar action
- reset the sidebar to the state it was before calling this function
Maybe it would be nice to be able to work with strings instead of just the indices, but I'm not sure about this (and it would make things much harder)
TODOs:

Feature lua add getSidebarPageNo/setSidebarPageNo

---

src/core/control/Control.cpp
src/core/control/pagetype/PageTypeMenu.h
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/gui/Layout.cpp
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/dialog/SettingsDialog.h
ui/settings.glade

additional space left, right, above or below the pages can be added separately 
you can find this under 'Preferences -> Drawing Area -> Scrolling outside the page'
- users who used the previous setting won't notice the change
- visually pleasing setting :)
- it works really nice combined with automatically adding pages when scrolling past the last page, since you can have a lot of space there, without having to have the same space on top of all pages :D
[you don't have to try it yourself, you can watch this video!](https://github.com/xournalpp/xournalpp/assets/125290879/dcc1da68-0cbb-4bdd-a6e4-8b086bc89431)

Enhances Scrolling outside the page

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/control/XournalMain.cpp
src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/tools/InputHandler.cpp
src/core/gui/MainWindow.cpp
src/core/gui/PageViewFindObjectHelper.h
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
src/core/gui/toolbarMenubar/ToolMenuHandler.h
src/core/gui/toolbarMenubar/ToolSelectCombocontrol.cpp
src/core/gui/toolbarMenubar/ToolSelectCombocontrol.h
ui/settings.glade

For one session the audio system can be disabled from the command line using the --disable-audio flag This option is particularly useful for troubleshooting crashes on startup. For future sessions the audio system can be disabled from the preferences by enabling the "Disable audio" checkbox.

Add options to disable the audio system for audio recordings

---

CHANGELOG.md
CMakeLists.txt
debian/changelog
desktop/com.github.xournalpp.xournalpp.appdata.xml
mac-setup/Info.plist
rpm/fedora/xournalpp.spec

This is the release PR for version 1.2.1. The HEAD commit of the PR will be pushed directly to the `xournalpp` repo, not via Github's web interface.
@xournalpp/core Please check!

Release of version 1.2.1

---

src/core/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp
src/core/gui/sidebar/previews/layer/SidebarPreviewLayerEntry.cpp

Fixes #5074 
The issue was the following: by not sinking the widget's floating ref, the SidebarPreviewLayerEntry did not own a ref to the widget. The floating ref was then sunk by the parent container GtkLayout. So the widget has a ref-count of 1.
When calling `gtk_widget_destroy()` in `~SidebarPreviewLayerEntry()`, two things happen `gtk_container_remove()` is called on the GtkLayout and our widget **and** `g_object_unref()` is called.
As `gtk_container_remove()` also drops the ref-count by one (as the container releases its ref), we call `g_object_unref()` on an already destroyed object.

Sink floating refs in PreviewEntry

---

plugins/ImageActions/main.lua
plugins/ImageActions/plugin.ini
src/core/plugin/luapi_application.h

This PR adds new API:
- app.getImages (for getting all info for the images contained either in the current layer or the current selection)
- app.addImages (for adding images to the current layer), extending upon functionality introduced in #4858
Combining these two functions it is possible to manipulate images contained in the document. In the test plugin for this PR it is currently possible to 
- invert
- downscale resolution
- flip horizontally/vertically
- rotate by 90 degrees clockwise/counterclockwise
all the images in the current selection.
- make white pixels transparent
In order to try it out, you should compile the PR (or use one of the [installers](https://github.com/xournalpp/xournalpp/pull/4884#issuecomment-1666423981) from this PR) and install the right versions of luaffifb …

Add Lua API app.getImages and app.addImages

---

src/core/control/pagetype/PageTypeMenu.cpp
src/core/control/pagetype/PageTypeMenu.h
src/core/gui/CreatePreviewImage.cpp
src/core/gui/CreatePreviewImage.h
src/core/gui/dialog/SettingsDialog.cpp
src/core/gui/toolbarMenubar/AbstractToolItem.cpp
src/core/gui/toolbarMenubar/AbstractToolItem.h
src/core/gui/toolbarMenubar/ToolButton.cpp
src/core/gui/toolbarMenubar/ToolDrawCombocontrol.cpp
src/core/gui/toolbarMenubar/ToolPdfCombocontrol.cpp
src/core/gui/toolbarMenubar/ToolSelectCombocontrol.cpp
src/util/gtk4_helper.cpp
src/util/include/util/GListView.h
src/util/include/util/gtk4_helper.h

This was part of #4508, to ease the reviewing process.
This PR only contains cleanups and extension of classes in util/ needed for #4508.

Preliminary cleanup before porting PageType-related menus and dialogs to gtk4

---

src/core/gui/menus/menubar/AbstractSubmenu.h
src/core/gui/menus/menubar/PageTypeSubmenu.h
src/core/gui/menus/menubar/PluginsSubmenu.cpp
src/core/gui/menus/menubar/PluginsSubmenu.h
src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
src/core/gui/menus/menubar/RecentDocumentsSubmenu.h
src/core/gui/menus/menubar/ToolbarSelectionSubmenu.cpp
src/core/gui/menus/menubar/ToolbarSelectionSubmenu.h
src/core/gui/menus/popoverMenus/PageTypeSelectionPopover.h
src/core/gui/menus/popoverMenus/PageTypeSelectionPopoverGridOnly.h

Simple inocuous cleanup in GMenu-based dynamically generated submenus.
Merging as soon as the CI clears

Clean up inheritance and constant declarations in menus

---

src/core/control/Control.cpp

In #3587 the location for autosave files was moved from the .config folder to the .cache folder

Fix shouldFileOpen

---

src/core/control/Control.cpp
src/core/gui/dialog/PageTemplateDialog.cpp
src/core/gui/dialog/PageTemplateDialog.h
src/core/gui/menus/popoverMenus/PageTypeSelectionPopoverGridOnly.cpp
src/core/gui/menus/popoverMenus/PageTypeSelectionPopoverGridOnly.h
ui/pageTemplate.glade

This concludes the series of PR's about PageType-related widgetry. Based on #4508

Make PageTemplateDialog gtk4-compatible

---

src/core/gui/PageView.cpp
src/core/gui/PageView.h
src/core/gui/inputdevices/AbstractInputHandler.cpp
src/core/gui/inputdevices/AbstractInputHandler.h
src/core/gui/inputdevices/DeviceId.h
src/core/gui/inputdevices/InputEvents.cpp
src/core/gui/inputdevices/InputEvents.h
src/core/gui/inputdevices/PenInputHandler.cpp
src/core/gui/inputdevices/PositionInputData.h
src/core/gui/inputdevices/TouchDrawingInputHandler.cpp

This PR adds a device hash and rejects input events that have not been issued by the pointing device that started a sequence.
Fixes #5116, possibly #5087 if this was the only source of negative pressure values.
This deserves some testing on various devices.

Check device hash for input sequences

---

src/core/control/xml/XmlNode.cpp
src/core/control/xml/XmlNode.h
src/core/control/xml/XmlPointNode.cpp
src/core/control/xml/XmlPointNode.h
src/core/control/xojfile/LoadHandler.cpp
src/core/control/xojfile/SaveHandler.cpp
src/core/gui/sidebar/Sidebar.cpp
src/core/gui/sidebar/previews/base/SidebarLayout.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.cpp
src/core/gui/sidebar/previews/base/SidebarPreviewBase.h
src/core/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp
src/core/gui/sidebar/previews/page/SidebarPreviewPages.cpp
src/core/model/Image.cpp
src/core/model/Stroke.cpp
src/core/model/TexImage.cpp
src/util/include/util/glib_casts.h
src/util/include/util/serializing/ObjectInputStream.h
src/util/include/util/serializing/ObjectOutputStream.h
src/util/serializing/ObjectInputStream.cpp
src/util/serializing/ObjectOutputStream.cpp
test/unit_tests/control/LoadHandlerTest.cpp
test/unit_tests/util/ObjectIOStreamTest.cpp

Fixes some memory leaks.
Some of the fixes are taken from #4613 (and flagged as coauthored with @jhilmer).
I also tried enabling `fsanitize=leak,address,undefined` to the tests' build env to implicitely add the test "no leaks in whatever the tests call". It detected some dataleaks in SaveHandler but I have not found the source of the leaks (yet).
I'll investigate and make a second PR once I found the issue.

Fix some memory leaks

---

src/core/control/LatexController.cpp
src/util/PathUtil.cpp
src/util/include/util/PathUtil.h

Fix issue with reading files by setting `std::ios::binary` flag when opening file stream. This corrects the file contents being read incorrectly.
For example, in the `LaTeX` preview dialog, `Util::readString` is used to read the generated PDF file. Without setting `std::ios::binary`, the PDF content was loaded incorrectly.
https://github.com/xournalpp/xournalpp/blob/718e57bd9c723723ddf0afdab486201248183125/src/core/control/LatexController.cpp#L318
Should fixes #4740

Fix file open mode in readString

---

src/core/control/Control.cpp
src/core/control/XournalMain.cpp
src/core/control/jobs/RenderJob.cpp
src/core/gui/dialog/LanguageConfigGui.cpp
src/core/model/Document.cpp
ui/settings.glade

- fixes #5123 partially
- fixes #5126

Fix-some-crashes

---

src/core/gui/dialog/SettingsDialog.cpp

Fixes a regression from #4808.
The audio input setting worked, the audio output setting didn't get saved correctly.

Fix audio output setting

---

mac-setup/build-app.sh
src/core/control/actions/ActionProperties.h

Fixes a regression from #4372 regarding accelerator modifiers, that are not defined in `main.glade` anymore, but in `mainmenubar.xml`.

Make Mac version use Meta instead of Ctrl again

---

src/core/gui/inputdevices/MouseInputHandler.cpp
src/core/gui/inputdevices/MouseInputHandler.h

Make MouseInputEvent only consider one pressed button - discard any BUTTON_PRESS while the first button is not released.
Fix #5149

Fix crash when right clicking while left pressing

---

src/core/control/Control.cpp
src/core/control/XournalMain.cpp

Applies default locale "", will be overriden later with userlang.UTF_8.
Fallback order: userlang.UTF_8 -> "" -> C

Fix locale issue

---

src/core/control/settings/Settings.cpp
src/core/control/settings/Settings.h
src/core/control/tools/TextEditor.cpp
src/core/gui/dialog/SettingsDialog.cpp
ui/settings.glade

Hi, 
I added a new preference for the tab size.
Instead of using a tabular char, the user can select to insert spaces instead.
Also, the amount of spaces to be inserted can be configured, in the range of 1 - 8. 
For efficiency reasons, I wouldn't allow inserting any more characters with a single stroke. 
I have currently located this preference under "Preferences > Input System > Tab". 
I'm not very happy about that location, but couldn't find something more intuitive.
In the future, a preference page "Controls" (or something like this) would be good.
Solves #4642.

Issue #4642 configure tab size

---

src/core/control/tools/ArrowHandler.cpp

Filled arrows and double arrows currently look asymmetrical. This commit fixes that by adding an additional point. Instead of
`tail -> head -> side 1 of head -> head -> side 2 of head`
it's now
`tail -> head -> side 1 of head -> head -> side 2 of head -> head`
As a consequence filled and unfilled arrows looks pretty much the same (although they behave differently when something from the head is erased).

Improve arrow shape with respect to fill

---

mac-setup/Info.plist
src/core/control/XournalMain.cpp

Finder uses Launch Services to identify Xournal++ as the preferred app for xopp-files as declared in the Info.plist, to launch it and send it an "Open Documents" event. Gtk receives the event and uses g_application_open to make the handler for the "open" signal react to it. See gtkapplication-quartz.c.
Fixes #5229.

Make MacOS Finder open xopp-files

---

src/core/control/zoom/ZoomControl.cpp
src/core/control/zoom/ZoomControl.h
src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/XournalView.cpp
src/core/gui/inputdevices/TouchDrawingInputHandler.cpp
src/core/gui/inputdevices/TouchInputHandler.cpp
src/core/gui/inputdevices/TouchInputHandler.h
src/util/Util.cpp
src/util/include/util/Util.h

This PR rebases the stale PR #2837 onto the latest master in a hope to speed up fixing #4678.
When rebasing, I solved some emerging conflicts. I also applied the suggestions by @personalizedrefrigerator and @LittleHuba given in the original PR.
This is a splitup part of https://github.com/xournalpp/xournalpp/pull/2743 .
see https://github.com/xournalpp/xournalpp/pull/2743 for older comments.
This patch fixes the issues with zoom jumping to previous/different pages. It also changes zoom steps to be relative for a much better zooming experience.
Internally this is a change from local to global coordinates, because the local coordinates had weird position spikes in them. This is honestly mostly due to my missing understanding of where the local coordinates come from. I am sure that part of …

Rebased: Fix zoom jumping and zoom steps (Partial Zoom Refactor)

---

src/core/control/latex/LatexGenerator.cpp
src/core/control/settings/PageTemplateSettings.cpp
src/core/gui/toolbarMenubar/ColorToolItem.cpp
src/util/Color.cpp

Fixes an issue with the background color of the latex editor remaining black discovered during the Gnome 45 upgrade for the [flatpak](https://github.com/flathub/com.github.xournalpp.xournalpp/pull/87#issuecomment-1731633491) and observed independently by a user in the [Matrix channel](https://matrix.to/#/!mIWOZbAzBNmtxiyIii:gitter.im/$K6ZyTBHRolhutu55TW3RB25-mHTLD--j6SHyBxL33YU?via=gitter.im&via=matrix.org&via=msrd0.de)
In the flatpak `Util::rgb_to_hex_string` returned unusable strings like `\xc5ס\xe1U`. The same issue would probably have appeared with page templates.

Fix Util::rgb_to_hex_string, thereby fixing the background color in the LaTeX editor

---

src/core/control/settings/Settings.cpp
src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h

Fixes #5245
Includes a change to `MainWindow::windowStateEventCallback()` as `gtk_window_is_maximized()` isn't up-to-date yet when the callback is called, plus an additional `Control::save()` in `Settings::setMainWndMaximized()`. 
In general, I noticed there can be 3-5 calls to `Settings::save()` when closing Xournal++. Shouldn't we be able to optimize that somewhat? Right now it is being called once from `Control::quit()` (which is being called from `MainWindow::deleteEventCallback()`), and up to 4 times through `Control::saveSettings()`. 
Wouldn't a call to `Settings::save()`, in `Settings::transactionEnd()` and `Control::saveSettings()` be enough, and then remove them everywhere else?

Fix window maximized setting save

---

src/config.h.in
src/core/control/xojfile/SaveHandler.cpp
src/core/control/xojfile/XojExportHandler.cpp

Instead of
`<title>Xournal++ document - see https://xournalpp.github.io/</title>` we had
`<title>Xournal++ document - see </title>`
written into all xopp-files since 
#2570 (cmake scripts overhaul)

Fix PROJECT_HOMEPAGE_URL

---

src/core/control/CrashHandlerUnix.h
src/util/CMakeLists.txt
src/util/Stacktrace.cpp
src/util/include/util/safe_casts.h

I noticed that the "better stacktrace" in the error logs was just the same as the original one. I found out that the argument passed to `addr2line` wasn't correct (it expects the section offset, not the runtime function address). 
I used a regex to extract the section offset. 
I set `addr2line` to output demangled function names (`-fC` + `p` to write in on one line).
Even found a memory leak in the function, which I couldn't just let slide.
This will now print source files and line numbers for calls that are from within the xournalpp executable. I haven't found out how to add information for external libraries, should debug information be provided (or at least how to demangle the function names). 
I'm open to formatting changes. I didn't want to make too many changes, but if we have the …

Improve backtrace

---

debian/rules

From the PPA buildlog it is visible that by default the `None` build type is used, which means that it is determined by the `CMAKE_CXX_FLAGS`. This PR overrides it with the `RelWithDebInfo` build type.
```term
dh_auto_configure
cd obj-x86_64-linux-gnu && DEB_PYTHON_INSTALL_LAYOUT=deb cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON 
```

Make .deb package build in RelWithDebInfo

---

src/core/control/tools/PdfElemSelection.cpp

Fix #5343 
This is a quick fix. Adding asserts in Range's member functions will come in a separate PR.

Ensure repainted region is non-empty in PdfElemeSelection

---

src/core/control/shaperecognizer/ShapeRecognizer.cpp
src/core/control/shaperecognizer/ShapeRecognizerConfig.h

Triggering shape recognition for rectangles is quite difficult currently. In fact, I didn't know it existed until I looked at the code, despite trying. 
This PR fixes this by initially allowing less precise lines to be considered as polygon segments. If we have only a single line, these are then excluded again. 
I acknowledge the risk of triggering false positives. At a first glance, it seems to be doing alright (haven't seen any yet). Anyhow, I will keep this as a draft PR for a few days and test it out. If I do not find any false positive until Wednesday evening, I will convert it to a normal PR.

Relax shape recognizer for rectangles

---

src/core/view/overlays/SearchResultView.cpp
src/core/view/overlays/VerticalToolView.cpp

When the search result is on a not currently visible page, we get an empty repaint range.
As in #5348 the repaint range must be non-empty, otherwise we get an assertion error (and hence a crash in Debug mode).
The repaint range in the vertical tool view was invalid when shifting below or above the visible part of the page. This could easily be reproduced (start with any document, switch to the vertical tool and move the mouse cursor below the visible part of the page). This lead to a `g-fatal-warning`, which is fixed now.

Ensure non-empty repaint ranges in SearchResultView and VerticalToolView

---

src/core/gui/PageView.cpp

The default "Loading..." pages that are displayed when pages aren't ready (rendered) at the time of painting are not sized correctly. The zoom was compensated for twice. This also led to some background regions not being redrawn properly afterwards.
To see the issue, zoom in or out quickly, especially with "Preferences -> View -> Clear cached pages while scrolling" checked.
Question to maintainers: should I always open an issue first, or is this fine?

Fix wrongly sized loading pages

---

src/core/gui/dialog/backgroundSelect/PdfPagesDialog.cpp
src/core/gui/dialog/backgroundSelect/PdfPagesDialog.h

Fixes issue reported here: https://github.com/xournalpp/xournalpp/issues/5436#issuecomment-1883815058
Second commit is some cleanup: `setSelected(0);` is already called by `BackgroundSelectDialogBase::show()`, which will now also set the button as sensitive if the PDF is not empty. But I'm not too sure about how pretty it really is though, since it requires setting the sensitivity to false at first. It's not a problem at all if you want to drop it.

Fix PDF page selection dialog OK button sensitivity

---

debian/rules

Currently the Launchpad build (for the PPA) fails due to a separator issue:
```term
dpkg-source -i -I.bzr -I.git --before-build .
fakeroot debian/rules clean
debian/rules:15: *** missing separator.  Stop.
```
This is a regression from 1cbc67fe9531fca871b347c99d48b9b0bad6f7e0
It can be checked by running
```term
fakeroot debian/rules build
```
in the root directory that replacing the 4 spaces by tab makes all the difference.
See also https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#customrules
> 4.4.1. Targets of the rules file
> Every rules file, like any other Makefile, consists of several rules, each of which defines a target and how it is carried out. [[37]](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#ftn.idm1517) A new rule begins with its target declaration …

Fix debian/rules indentation

---

src/core/control/Control.cpp
src/core/control/Control.h
src/core/control/PageBackgroundChangeController.cpp
src/core/control/PageBackgroundChangeController.h
src/core/control/xojfile/LoadHandler.cpp
src/core/control/xojfile/LoadHandler.h
src/core/gui/XournalView.cpp
src/core/gui/XournalView.h
src/core/model/Document.cpp
src/core/model/Document.h
src/core/pdf/base/XojPdfDocument.cpp
src/core/pdf/base/XojPdfDocument.h
src/core/pdf/base/XojPdfDocumentInterface.h
src/core/pdf/popplerapi/PopplerGlibDocument.cpp
src/core/pdf/popplerapi/PopplerGlibDocument.h
src/core/undo/MissingPdfUndoAction.cpp
src/core/undo/MissingPdfUndoAction.h

Fixes #5435
~~Undoing simply reopens the whole file.~~
Now involves a slight refactoring of how the page background is replaced.

Add undo handler for missing PDF replacement

---

src/core/control/Control.cpp

Fixes two issues
- Filesystem error on MacOS when a document is autosaved the first time after startup
- Typo in error message displaying `{2}` instead of error message
The first issue was described in https://github.com/xournalpp/xournalpp/issues/5474#issue-2103370589

Avoid using fs::equivalent on empty path

---

plugins/MigrateFontSizes/main.lua

Now that `lgi` is shown to work on Windows (see installation instructions [here](https://github.com/xournalpp/xournalpp/discussions/4522#discussioncomment-4490657)) plugins must care about OS specific stuff like path separators.

Fix path separator for Windows

---

.clang-format

Automatic handling of attributes may decrease readability: No good default, therefore using 'Leave'

clang-format improvement,

---

src/core/control/CompassController.cpp
src/core/control/CompassController.h
src/core/control/SetsquareController.cpp
src/core/control/SetsquareController.h
src/core/control/tools/Selection.h
src/core/control/tools/StrokeHandler.cpp
src/core/control/zoom/ZoomControl.cpp
src/core/control/zoom/ZoomControl.h
src/core/gui/MainWindow.cpp
src/core/gui/MainWindow.h
src/core/gui/inputdevices/GeometryToolInputHandler.cpp
src/core/gui/inputdevices/GeometryToolInputHandler.h
src/core/gui/inputdevices/PenInputHandler.cpp
src/core/gui/inputdevices/PenInputHandler.h
src/core/gui/inputdevices/TouchInputHandler.cpp
src/core/gui/inputdevices/TouchInputHandler.h
src/core/view/overlays/StrokeToolFilledView.cpp
src/core/view/overlays/StrokeToolFilledView.h
src/util/Util.cpp
src/util/include/util/Point.h
src/util/include/util/Rectangle.h
src/util/include/util/Util.h
src/util/include/util/raii/CairoWrappers.h

- added some constexpr to Rectangle and Point
- made CairoWrapper `[[nodiscard]]`, its a guard and must not be discarded

Move Point from `::utl::` to `xoj::util::`

---

plugins/ImageActions/main.lua

This PR adds image trimming and image splitting (vertically or horizontally) according to the largest block of white rows (or columns) to the ImageActions plugin.

Add image trimming and splitting

---

src/core/control/XournalMain.cpp
src/core/gui/dialog/LanguageConfigGui.cpp
src/util/PathUtil.cpp
src/util/include/util/PathUtil.h

Users of [auto Util::getGettextFilepath(fs::path const& localeDir) -> fs::path {](https://github.com/Febbe/xournalpp/blame/8dbb0cf81a0aecf2e5c1c47537f2654f62b72e94/src/util/PathUtil.cpp#L179C45-L179C45) used a utf8 encoded path, while `Util::getGettextFilepath` used system encoded paths. 
I changed the function, to use consistently `fs::path` and doing the encoding related parsing in this function.

Fix_chinese_locale

---

src/core/control/Control.cpp
src/core/gui/MainWindow.cpp

The menubar should be visible on startup iff the according checkbox in the View tab of the settings is enabled. Hitting F10 or using menu View > Show Menubar
should not change this setting.
This fixes a regression from #4372 and is only on master.

Fix menubar visibility on startup

---

azure-pipelines/gen-lua-def-run.yml
plugins/luapi_application.def.lua
scripts/lua_def_file.py
src/core/plugin/luapi_application.h

The resulting declaration file can be used with
[luaLS](https://github.com/LuaLS/lua-language-server)
Note: The term definition might not be completely correct as the file only declares the functions, it doesn't really define it. Nevertheless, LuaLS uses the term 'definition files' so I stick to it when referring to LuaLS.
Replaces #5563 (hardcode definition file), now automatically generate it to make keeping in sync easier.
TODOs:
See #5563 for example how to configure LuaLS.
See #5555 for references on LuaLS.
<details><summary>Smaller example</summary>
<details><summary>smaller luapi_application.h:</summary>
```cpp
/**
* Renames file 'from' to file 'to' in the file system.
* Overwrites 'to' if it already exists.
*
* @param from string
* @param to string
* @return number|nil Returns 1 …
```

Python script to generate LuaLS definition file from luapi header file

---

src/core/control/PageBackgroundChangeController.cpp

This fixes a regression from #5630
The crash happens when using menu Journal > Page Background (e.g. changing from graph to lined). In that case `pageTypeForNewPages` may not hold a value.

Fix crash when changing page type

---

src/core/plugin/PluginController.cpp

Currently the file plugins/luapi_application.def.lua raises a warning.
The warning only appears on master (since #5572), so I think it's enough to target it to the master branch.

Load plugins only from subfolders of plugin folder

---

src/core/control/tools/PdfElemSelection.h
src/core/gui/PageView.cpp

fixes #5659
This introduces a SharedMask, which protects itself, holding a shared state to a Mask and a Mutex, protecting the Mask.
The solution might be a bit overkill, but it seems to be the easiest solution:
Mask in [PageView.h](https://github.com/xournalpp/xournalpp/pull/5662/files#diff-6379e23dd0c4d7ca42877da6ff49822c47025c346d45c2c27c4b3d97f1afb060) can be manipulated in 2 ways:
The Mask, holding its data and the cairo_mask can be replaced completely.
The data of the mask can be manipulated.
Both operations must be protected by a mutex, or they must be immutable.
The state may be shared and the removal / replacement must not happen in between.

Fix-drawing-crash

---

plugins/QuickScreenshot/main.lua
plugins/luapi_application.def.lua
src/core/gui/dialog/XojOpenDlg.cpp
src/core/gui/dialog/XojOpenDlg.h
src/core/plugin/Plugin.cpp
src/core/plugin/Plugin.h
src/core/plugin/luapi_application.h

This PR deprecates the Lua plugin API app.saveAs app.getFilePath and replaces it by Gtk4 compatible versions. We wanted to do it before the Gtk4 switch, see https://github.com/xournalpp/xournalpp/pull/5615#issuecomment-2081171924
Maybe more customization should be introduced:
- custom file filter for save dialogs (currently all files are in the filter)
- custom window title for save dialogs
The QuickScreenshot plugin was adapted to use the new API.

Replace file dialog plugin api

---

plugins/ImageActions/main.lua

The inner and outer loop used the same name for the loop variable, which raised a well justified warning.

Fix warning in image actions plugin

---

src/core/gui/toolbarMenubar/model/ColorPalette.cpp
src/core/gui/toolbarMenubar/model/ColorPalette.h

Fixes #5724 
In line with [the specification](https://developer.gimp.org/core/standards/gpl/), this will accept only actually empty lines. Allowing blank lines (with any kind of whitespaces) would be easily feasible with the following, if you think it's prefferable:
```c++
auto Palette::parseBlankLine(const std::string& line) const -> bool {
return line.find_first_not_of(" \t\r\f\v") == std::string::npos;
}
```
PS: Hi it's me again. Haven't had much time lately... I'll try to work on my other open PRs, but I figured this small issue would be perfect to jump back in.

Allow missing terminating newlines and empty lines in .gpl files

---

azure-pipelines/continuous-integration.yml
azure-pipelines/create-installers.yml
azure-pipelines/release.yml

- macOS-11 has been deprecated and removed
- new versio macOS-12

Bump MacOS pipeline image

---

src/core/control/RecentManager.h
src/core/gui/menus/menubar/RecentDocumentsSubmenu.cpp
src/core/gui/menus/menubar/RecentDocumentsSubmenu.h

Added submenu "Remove Recent Documents" under menu file -> recent documents. Clicking on files in this submenu remove individual recent files without the need of clearing the whole list.

Add feature to remove individual entries from list of recent documents

---

plugins/luapi_application.def.lua
src/core/plugin/luapi_application.h

I noticed that while you could zoom in and out using the actions, you couldn't set the zoom to a specific level or get the current zoom level using the plugin api.
In this pull request I added the methods `app.getZoom` and `app.setZoom` to the `luapi_application.h` file.
The `app.getZoom` method calls `ZoomControl::getZoomReal` and returns it as a number, the `app.setZoom` calls the same methods to set the zoom level that are also used in [ActionProperties.h](https://github.com/xournalpp/xournalpp/blob/2e9c84a88271d18e64ca64e293a6521f13bb2c3c/src/core/control/actions/ActionProperties.h#L430) (this also means first multiplying the supplied zoom level by the `zoom100Value` which means that you set the real zoom value using the api, which corresponds to getting the real zoom value with …

Add methods app.getZoom and app.setZoom to plugin api.

---

.cirrus.yml
CMakeLists.txt
mac-setup/cirrus_jhbuild.sh
mac-setup/jhbuild-version.lock
mac-setup/upload-release.sh

This PR is based on work of @Technius and adds a Cirrus configuration file and build task in order to create a MacOS ARM build. The task is executed on https://cirrus-ci.com/ and on a MacOS Ventura runner.
The lock file (and possibly GITHUB token) still need to be updated to the latest versions and tested.

Cirrus pipeline task

---

plugins/SpaceForNotes/main.lua
plugins/SpaceForNotes/plugin.ini

Adds a plugin which adds empty pages after each page showing a page from the pdf if the page is the last page of the document or the following page also shows a page from the pdf.
This rather complicated conditional makes the function idempotent, so executing it more than once won't do more changes.
To provide full flexibility to the user, there is also a `force` mode which simply skips the check and unconditionally adds an empty page after every page in the document.
Implements #5285.
After applying this, one can e.g. set the view to two-column mode so that one has always the pdf page on the left and have space on the right for notes.
---
Note: Initially I thought about naming the plugin `BatchChanges` as it allows us to apply one operation on the complete document. Also in the beginning …

Plugin: Add pages for notes automatically

---

ui/plugin.glade
ui/pluginEntry.glade

The description of a plugin can be quite long. The whole dialog gets messed up when there is no wrapping. The line `Plugin changes are only applied after Xournal++ is restarted` is quite long as well.
The wrapping is already done on the GTK4 branch (.glade -> .ui conversion)

Add wrapping for long labels in plugin manager

---

windows-setup/package.sh
windows-setup/xournalpp.nsi

Remark: The MultiUser.nsi is preinstalled and suits our prupose:
- In the GUI a admin can choose between installation for all users or current user
- Silent mode installation works
It has some limitations though, in particular
- Privilige elevation is asked even if a user with admin priviliges wants to install
for current user
- To work around this issues the NsisMultiUser plugin on
https://github.com/Drizin/NsisMultiUser could be used.
It is not preinstalled though and would complicate the build process.
Some remarks about the changes:
- The custom page for choosing the install mode was replaced by the page MULTIUSER_PAGE_INSTALLMODE from the MultiUser plugin
- SetShellVarContext is handled by the MultiUser plugin.
- The RefreshShellIcons macro is already defined in the `FileFunc.nsh` …

Use MultiUser.nsi for choosing between all users or current user install

---

plugins/FitToContent/main.lua
plugins/HighlightPosition/main.lua
plugins/ImageActions/main.lua
plugins/luapi_application.def.lua
src/core/plugin/luapi_application.h

Closes #6028, #6002.
**Edit:** Removed add `app.removeFromSelection`, since it can be achieved by a combination of the other API functions.

Allow adding plugin strokes to selection

---

src/core/control/settings/MetadataManager.cpp

Fixes #6068 (regression from #5855)

Don't migrate metadata if legacy directory is the same as the new one

---

.github/actions/install_deps_windows/action.yml
windows-setup/package.sh

Packaging `lua-lgi` and dependencies on Windows takes (only) roughly 4 MB when extracted.
- The .typelib files take 3.3 MB
- The libraries (libgirepository-1.0-1.dll, libgirepository-1.0.dll.a, corelgilua51.dll) take 0.5 MB
- The .lua files take 0.26 MB
It seems to work all fine (even without changing the lua package path or package cpath).

Package lua-lgi and dependencies on Windows

---

plugins/luapi_application.def.lua
src/core/plugin/luapi_application.h

Fixes #6060 
To keep it simple I didn't add an option to omit forcing existence of these folders. It could be added later if needed (with an optional argument).
Here's a sample callback in a plugin with name "Test" and sample output (on Linux):
```lua
function folder()
print(app.getFolder("config"))
print(app.getFolder("data"))
print(app.getFolder("state"))
end
```
output:
```
/home/roland/.config/xournalpp/plugin-settings/Test
/home/roland/.local/share/xournalpp/plugin-data/Test
/home/roland/.local/state/xournalpp/plugin-state/Test
```
This still needs testing on various platforms.

Add Lua API for getting config, state and data folders of plugin

---

mac-setup/Info.plist
mac-setup/jhbuild-version.lock
mac-setup/xournalpp.bundle
mac-setup/xournalpp.modules
src/exe/osx/setup-env.cpp

This PR most notably packages `lua-lgi` on MacOS in the same spirit as #6158. That means `lua-lgi` will come bundled on all platforms where we provide bundled installations (Windows, MacOS, snap, flatpak), which makes it much easier for plugin authors that want to create some graphical user interface elements.
~While we already built Lua on MacOS as specified in `xournalpp.modules` and thus enabled plugins on MacOS, we somehow didn't package Lua on MacOS. This is fixed with this PR.~
I have also updated the Lua version from 5.4.6 to 5.4.7 (released in June 2024). 
There was a typo in `libpoppler-glib*.dylib`, which suggests that these lines could be omitted as well. I have just fixed the typo.
The assets will still need to be tested.
**Edit:** `liblua.a` is a static library and baked into …

Package lua-lgi for MacOS

---

plugins/QuickScreenshot/main.lua

The way it is written, the UI freezes every time a screenshot is taken using the plugin (on systems where `maim` is used). This makes the plugin unusable in Xorg systems. Once the screenshot border is drawn to the screen Xorg sends an Expose event to the window, but it is not handled since the thread is too busy waiting for `maim`, so the screenshot is just a bunch of frozen borders. Here is a screenshot taken with the plugin, the frozen menu can be seen behind the bars, hinting at the fact that the UI is taking a nap.
To be clear, the effect in the image happens when clicking on the plugin and then spanning a rectangle with the mouse. Just as I would do to take a screenshot of a region of the screen. It also only happens when taking a screenshot of `xournalpp` itself. And, yes, this is …

QuickScreenshot: Do not block main thread while taking a screenshot with `maim`

---

mac-setup/CI_jhbuild.sh
mac-setup/jhbuild-version.lock

The two fixes have been merged into gtk-osx. So I'm removing them here.

Update gtk-osx and remove obsolete fixes

---

src/core/control/XournalMain.cpp
src/core/gui/FloatingToolbox.cpp
src/core/gui/FloatingToolbox.h
src/core/gui/PageView.cpp
src/core/gui/SearchBar.cpp
src/core/gui/dialog/backgroundSelect/BackgroundSelectDialogBase.cpp
src/core/gui/dialog/backgroundSelect/BackgroundSelectDialogBase.h
src/core/gui/sidebar/indextree/SidebarIndexPage.cpp
src/core/gui/sidebar/indextree/SidebarIndexPage.h
src/core/gui/sidebar/previews/base/SidebarPreviewBaseEntry.cpp
src/core/gui/sidebar/previews/base/SidebarToolbar.cpp
src/core/gui/sidebar/previews/base/SidebarToolbar.h
src/core/gui/sidebar/previews/page/SidebarPreviewPages.cpp
src/core/gui/toolbarMenubar/FontButton.cpp
src/core/gui/toolbarMenubar/PluginToolButton.cpp

This fixes some UB around various signal handlers 
1. some had a return value and shouldn't have (probably inocuous)
2. some had no return value but should have had one
3. The FontButton callback was really messed up
- some gpointer was cast to an unrelated type (GtkToolItem* vs GtkFontButton*)
- The callback was set up twice (hence called twice)
4. some callbacks were dangerous, potentially causing SegFaults

Fix some undefined behaviour (and possible SegFaults) with GTK signals

---

plugins/BeamerPresentation/main.lua
plugins/FitToContent/main.lua
plugins/HighlightPosition/main.lua
plugins/ImageActions/main.lua
plugins/LayerActions/main.lua
plugins/SpaceForNotes/main.lua
plugins/ToggleGrid/togglegrid.lua
plugins/luapi_application.def.lua
scripts/lua_def_file.py
src/core/control/Control.cpp
src/core/control/ToolEnums.cpp
src/core/control/ToolEnums.h
src/core/control/ToolHandler.cpp
src/core/control/actions/ActionProperties.h
src/core/control/settings/Settings.cpp
src/core/control/tools/EditSelection.cpp
src/core/control/tools/EditSelection.h
src/core/gui/dialog/SelectOpacityDialog.cpp
src/core/plugin/luapi_application.h
src/util/include/util/GVariantTemplate.h
test/unit_tests/control/ToolEnumsTest.cpp

The basic functionality works already. E.g. one can write
```lua
app.activateAction("setsquare")
```
to toggle the setsquare or
```lua
app.changeActionState("set-layout-vertical", false)
```
to change to horizontal layout.
The action states are not always self-explanatory and this still needs to be addressed (brainstorming below). One can write e.g.
```lua
app.changeActionState("select-tool", 4)
```
but how would you know that 4 corresponds to the Text tool?
One idea would be to automatically generate a .lua file that defines all these enum values. The .lua file would have to put somewhere where it can be found.
Another idea would be to add runtime info (something like `app.getAllActionNames()` and `app.getActionStates(action))`
but that would leave the readability problem to the plugin …

Expose new action system in Lua API and deprecate old one
