xournalpp/xournalpp

.travis.yml, src/control/ToolHandler.cpp, src/gui/TextEditor.cpp, src/gui/toolbarMenubar/model/ToolbarModel.cpp, src/gui/toolbarMenubar/model/ToolbarModel.h, src/model/LinkDestination.cpp, src/pdf/popplerdirect/PdfExport.cpp
Fixes some issues from Coverity report, fixed Travis Coverity support.
=> Coverity Scan based fixes

src/model/Point.h
After changing this I was able to compile from the gtk3 branch locally.
=> changes const to constexpr in Point.h

README.md
Specific notes for Fedora/etc users on how to install dependencies for building - i.e. in lieu of creating a packages as part of #143 or myself adding a srpm to copr.fedora... (when I get round to it).
=> Specific build instructions (deps install) for Fedora/CentOS/RHEL in lieu of #143

src/gui/Layout.cpp
Included the len check in the twoPages flag, else it would fail when it was used later in the function.
=> fix for xournalpp/xournalpp/issues/203

src/control/Control.cpp
Default background settings will be saved after being changed via Journal->'Paper Background' 
Relates to #205
=> fixed page background persistence

README.md, src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/gui/widgets/XournalWidget.cpp
=> Add support for BTN_STYLUS and BTN_STYLUS2

CMakeLists.txt, src/pdf/popplerdirect/PdfExport.cpp, src/pdf/popplerdirect/PdfObjectWriter.cpp, src/pdf/popplerdirect/PdfRefList.cpp, src/pdf/popplerdirect/poppler/XojPopplerDocument.cpp
Hey,
I had a look at the changes in poppler and adapted the code these.
/Peetcreative
=> Adaption to poppler>0.58

src/control/tools/StrokeHandler.cpp
Fixes pressure sensitivity on Wayland, possible fix for https://github.com/xournalpp/xournalpp/issues/209
=> fixed pressure sensitivity

README.md
As title.
Also clarified that MATHTEX is already enabled by default.
=> Updated readme with Ubuntu dependencies

po/de.po
Added some translation and corrected some errors in spelling and grammar. (native speaker)
=> Update of de.po

src/control/RecentManager.cpp, src/gui/dialog/ExportDialog.cpp
Closes #263, #219, #190 and potentially #229
=> Fix two GUI bugs with uncaught exceptions

src/gui/LayoutData.cpp, src/gui/LayoutData.h, src/gui/dialog/ExportDialog.cpp, src/gui/dialog/ImagesDialog.cpp, src/gui/dialog/PdfPagesDialog.cpp, src/gui/dialog/SelectBackgroundColorDialog.cpp, src/gui/dialog/toolbarCustomize/CustomizeableColorList.cpp, src/gui/pageposition/PageViewIndex.cpp, src/model/Layer.cpp, src/model/XojPage.cpp, src/pdf/popplerdirect/PdfExport.cpp, src/undo/FontUndoAction.cpp, src/undo/RecognizerUndoAction.cpp, src/undo/SizeUndoAction.cpp
Merged stuff from GTK3 branch, fixed Memory leak, clear list in destructor (for safety)
=> Small fixes

README.md, src/control/Control.cpp, src/gui/toolbarMenubar/model/ToolbarEntry.cpp
=> fixed #278

src/gui/Cursor.cpp, src/gui/Cursor.h, src/gui/GladeGui.cpp, src/gui/dialog/SettingsDialog.cpp
And also cleaned up some dead code in the settings dialog
=> fixed #293

src/control/tools/ArrowHandler.cpp, src/control/tools/CircleHandler.cpp, src/control/tools/RulerHandler.cpp, src/gui/Cursor.cpp
=> Fix the compilation of math function.

src/control/Control.cpp
=> Drag of images fit the page now

CMakeLists.txt, cmake/cmake_uninstall.cmake.in
=> Install poppler fix (workaround for the workaround...)

src/Xournalpp.cpp, src/gui/sidebar/previews/base/SidebarPreviewBase.cpp, src/gui/toolbarMenubar/ToolMenuHandler.cpp, src/util/Stacktrace.cpp, src/util/Stacktrace.h, test/TestMain.cpp
=> Fixed sidebar loop

CMakeLists.txt
=> RPATH Fixed, Poppler workaround now loads correct libs

src/control/Control.cpp, src/control/LastSelectedTool.cpp, src/control/LastSelectedTool.h, src/control/Tool.cpp, src/control/Tool.h, src/control/ToolHandler.cpp, src/control/ToolHandler.h, src/control/settings/ButtonConfig.cpp, src/control/settings/ButtonConfig.h, src/control/settings/Settings.cpp, src/control/tools/StrokeHandler.cpp, src/gui/PageView.cpp
=> Restore tool on button release

po/cs.po, po/de.po, po/pl.po, po/zh.po, po/zh_HK.po, po/zh_TW.po, src/control/Control.cpp, src/control/LatexController.cpp, src/control/XournalMain.cpp, src/control/jobs/AutosaveJob.cpp, src/control/jobs/BaseExportJob.cpp, src/control/jobs/CustomExportJob.cpp, src/control/jobs/PdfExportJob.cpp, src/control/jobs/SaveJob.cpp, src/gui/GladeGui.cpp, src/gui/MainWindow.cpp, src/gui/sidebar/indextree/SidebarIndexPage.cpp, src/undo/UndoRedoHandler.cpp, src/util/Util.cpp
fixed #268
All error messages ar now cleaned up and one in an unitility function
=> Check for PDF Background overwrite

src/gui/PageView.cpp
* playback automatically resumes on vlc when clicking on a segment.
=> improved autoplay

src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/gui/Layout.cpp, src/gui/Layout.h, src/gui/XournalView.cpp, src/gui/dialog/SettingsDialog.cpp, src/gui/widgets/XournalWidget.cpp, ui/settings.glade
Background is now also customizeable in the settings
Background is painted by Xournal++, not by GTK
=> fixes #335

src/gui/dialog/SettingsDialog.cpp
=> Forgot a nullcheck in Settings

README.md, desktop/desktop_install.sh.in, utility/usr/local/bin/xopp-recording.sh
- improved the recording script
- updated README
=> updated desktop-install to install the audio recording script

src/control/AudioController.cpp, src/control/LatexController.cpp, src/control/LatexController.h, src/gui/PageView.cpp, src/gui/PageView.h
- select a textbox
- hit CTRL+x or "insert latex"
- the current text will become latex
=> text --> latex inplace substitution

src/gui/PageView.cpp, src/gui/PageView.h
=> Loading page is now HighDPI

CMakeLists.txt
Due to the disscusion of issue #283 I add possibility to build poppler from tarball and limited the versions from which xournalpp can be build.
This might be updated from time to time.
=> refacctor build possibilities for poppler

.travis.yml
modify .travis.yml so the xournalpp/xournalpp cover scan project checks for static scans
=> modify coverity scan  to xournalpp/xournalpp

.gitignore, CMakeLists.txt, src/control/XournalMain.cpp, src/xoj-preview-extractor/xournal-thumbnailer.cpp
Now it is building on Mac OS if all dependencies are met.
I am not sure about the ENABLE_NLS and if it is useful on other systems. Some feedback on that would be great.
=> modified cmakelists for building on Mac OS

src/control/Control.cpp
=> Fixed save name proposal

src/control/LatexController.cpp, src/gui/dialog/LatexDialog.cpp, src/gui/dialog/LatexDialog.h
Hi!
I added the macro calls you suggested to add and fixed an error in the one called from the handler!
=> Fixed macro calls in LatexController methods

src/control/XournalMain.cpp, src/control/XournalMain.h, src/control/jobs/CustomExportJob.cpp, src/gui/GladeSearchpath.cpp
=> Resource loading / finding

src/gui/XournalView.cpp
=> Scrolling key shortcuts

src/control/XournalMain.cpp, src/gui/XournalView.cpp, src/gui/XournalView.h
=> Fixed scrolling issue at start

CMakeLists.txt
=> Debain packaging working

src/control/tools/StrokeHandler.cpp
=> Fixed crash on Touch / Pen input

src/gui/toolbarMenubar/ColorToolItem.cpp
=> fix color chooser lacked

src/control/jobs/RenderJob.cpp, src/control/tools/InputHandler.cpp, src/gui/XournalView.cpp
Reverts xournalpp/xournalpp#442
=> Revert "Partial merge highdpi"

src/control/LatexController.cpp, src/control/LatexController.h, src/gui/dialog/LatexDialog.cpp, src/gui/dialog/LatexDialog.h
=> Crash fixed if tex image is not created

src/control/tools/EditSelection.cpp, src/control/tools/EditSelection.h
This will allow to have the rotation snapping to a grid every 45 degrees. 
Maybe we could use a checkbox by the dropdown menu to enable/disable this feature in the future.
=> rotation snapping every 45 degrees

src/control/tools/ArrowHandler.cpp
* Snap the arrow to a grid for rotation, just like the normal "segment" does
* ATM only each 90 degrees since I haven't figured out yet how to rotate the arrow head by 45 (any help on this would be nice)
=> Arrow rotation

src/control/tools/ArrowHandler.cpp
* adding snap toggle to arrow rotation
* fixing arrow free rotation aspect ratio
=> Arrow rotation with toggle

src/control/AudioController.cpp, src/control/AudioController.h, src/pdf/popplerapi/PopplerGlibAction.cpp, src/pdf/popplerapi/PopplerGlibAction.h, src/pdf/popplerapi/PopplerGlibDocument.cpp, src/pdf/popplerapi/PopplerGlibPageBookmarkIterator.cpp, src/pdf/popplerapi/PopplerGlibPageBookmarkIterator.h, src/util/XournalTypeList.h
PDF GLib API, Bookmarks are partial working (jump to the right page, but not to the right position)
=> Pdf api try2

src/control/tools/EditSelection.cpp, src/model/Stroke.cpp
* Improved rotation precision by offset
* Improved rotation handle zone 
* Disabled debug printing of the rotation center
=> rotation improvements

src/control/XournalMain.cpp
Hi! Sorry I forgot to check that the env variable GTK_IM_MODULE exists!
Fixes #531
=> Fix environment GTK_IM_MODULE check

src/gui/PageView.cpp
=> Stop search on text input

src/control/ZoomControl.cpp, src/control/ZoomControl.h, src/gui/XournalView.cpp, src/gui/toolbarMenubar/ToolZoomSlider.cpp
When trying to fix issue #416. I started to change other things in the zooming. Does not fix #416
=> Change some Zoom

README.md, src/CMakeLists.txt, windows-setup/build-launcher.sh, windows-setup/build-setup.sh, windows-setup/xournalpp.nsi
Fixed Translation loading
Fixed .exe size
Require Admin Rights
=> Windows Build

readme/LinuxBuild.md
I just installed it on my system and it works like a charm!
Only difference for me: `sudo make install` was necessary instead of the proposed `make install`
=> Add OpenSuse library instructions

.settings/language.settings.xml, src/control/Control.cpp, src/control/Control.h, src/control/ToolHandler.cpp, src/control/ToolHandler.h, src/control/settings/ButtonConfig.cpp, src/gui/toolbarMenubar/ColorToolItem.cpp
=> Should fix unexpected color change

src/view/DocumentView.cpp
just a random thing i found in the code
=> small code clean up

src/control/zoom/ZoomControl.cpp
=> fix the page is scrolling to the wrong position

src/control/zoom/ZoomControl.cpp
Reverts xournalpp/xournalpp#576
=> Revert "fix the page is scrolling to the wrong position"

po/cs.po, po/de.po, po/pl.po, po/zh.po, po/zh_HK.po, po/zh_TW.po, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/SaveHandler.cpp, src/control/xojfile/SaveHandler.h, src/control/xojfile/XojExportHandler.cpp, src/control/xojfile/XojExportHandler.h, src/model/Stroke.cpp, src/model/Stroke.h, src/util/serializing/ObjectOutputStream.cpp, src/view/DocumentView.cpp, src/view/DocumentView.h
=> Load / Save and draw fill. UI not yet there.

po/cs.po, po/de.po, po/it.po, po/pl.po, po/zh.po, po/zh_HK.po, po/zh_TW.po, src/gui/MainWindow.cpp, src/gui/MainWindow.h, ui/main.glade
=> Allow to hide menu

src/CMakeLists.txt, src/control/RecentManager.cpp, src/util/Path.cpp, src/util/Path.h, src/util/Range.cpp, src/util/StringUtils.cpp, src/util/StringUtils.h, src/util/XournalTypeList.h, test/CMakeLists.txt, test/TestMain.cpp, test/util/PathTest.cpp, test/util/StringUtilTest.cpp
=> UnitTest build and initial Path class

src/gui/widgets/XournalWidget.cpp, src/gui/widgets/XournalWidget.h
=> Center on visible part of the page

src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/gui/toolbarMenubar/ToolZoomSlider.cpp
Minor changes to make the zoomrange adaptable
=> make Zoomrange adjustable

src/control/Control.cpp, src/control/Control.h, src/control/XournalMain.cpp, src/control/XournalMain.h, src/util/Path.cpp, src/util/Path.h, src/xoj-preview-extractor/CMakeLists.txt
=> Open emergency saved document on restart

src/control/Control.cpp, src/control/Control.h, src/control/ToolHandler.cpp, src/control/ToolHandler.h, src/control/tools/EditSelection.cpp, src/control/tools/EditSelection.h, src/control/tools/EditSelectionContents.cpp, src/control/tools/EditSelectionContents.h, src/gui/XournalView.cpp, src/gui/toolbarMenubar/ColorToolItem.cpp, src/gui/toolbarMenubar/ColorToolItem.h, src/undo/FillUndoAction.cpp, src/undo/FillUndoAction.h, src/util/XournalType.cpp, src/util/XournalTypeList.h
=> Stroke tool item

src/control/Control.cpp, src/control/Tool.cpp, src/control/Tool.h, src/control/ToolHandler.cpp, src/control/ToolHandler.h, src/control/settings/Settings.cpp
=> Store fill config

src/gui/toolbarMenubar/ToolMenuHandler.cpp
=> Add delete toolbar button

src/control/XournalMain.cpp, src/undo/EmergencySaveRestore.cpp, src/undo/EmergencySaveRestore.h, src/util/XournalTypeList.h
=> Mark emergency restored document as changed

src/control/tools/BaseStrokeHandler.cpp
=> If a stroke is invalid, delete it

src/control/Control.cpp
=> Filename in header

src/control/stockdlg/XojOpenDlg.cpp, src/control/tools/EditSelectionContents.cpp, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/LoadHandler.h, src/model/Stroke.cpp, src/model/Stroke.h, src/pdf/popplerapi/PopplerGlibAction.cpp, src/undo/SizeUndoAction.cpp, src/undo/SizeUndoAction.h, src/util/XournalTypeList.h
=> Support to open MrWriter files

src/control/tools/StrokeHandler.cpp, src/model/Stroke.cpp, src/model/Stroke.h, src/view/StrokeView.cpp, src/view/StrokeView.h
Drawing dashed lines does now work #704
=> Dash drawing working

src/control/tools/StrokeHandler.cpp
@luco5826 
This is the correct position.
But your code was all correct.
=> Stroke recognizer size

src/control/xojfile/LoadHandler.cpp, src/model/Stroke.cpp, src/model/Stroke.h, src/model/StrokeStyle.cpp, src/model/StrokeStyle.h
=> Load dotted lines

src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/gui/MainWindow.cpp, src/gui/dialog/SettingsDialog.cpp, ui/settings.glade
=> Added 'Disable Zoom Gestures' option

src/control/xml/DoubleArrayAttribute.cpp, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/SaveHandler.cpp, src/control/xojfile/XojExportHandler.cpp, src/model/StrokeStyle.cpp, src/model/StrokeStyle.h
=> Saving stroke

src/gui/inputdevices/InputSequence.cpp
=> Mouse up => no button pressed

src/control/tools/StrokeHandler.cpp
* preserving incremental stroke rendering for "normal" strokes
* realtime rendering of stroke style and fill (better usability)
=> stroke style and fill rendered immediately while drawing

src/config-features.h.in, src/control/jobs/PreviewJob.h, src/control/jobs/RenderJob.cpp, src/control/tools/StrokeHandler.cpp, src/gui/PageView.cpp
cmake .. -DUNSTABLE_HIGHDPI_FIXES=ON
#172
=> High DPI Basically working

src/gui/PageView.cpp, src/undo/RecognizerUndoAction.cpp
=> High DPI Fixes

src/gui/sidebar/previews/base/SidebarPreviewBase.cpp
=> Fixed sidebar bug

README.md, check-source.sh, src/control/xml/XmlImageNode.h, src/control/xml/XmlTexNode.h, src/view/background/BaseBackgroundPainter.h
=> Added cppcheck script, removed coverity (which is offline)

debian/control
Xournal should show how to install pdflatex...
=> Removed mathtex dependency

CMakeLists.txt, src/config-features.h.in, src/control/jobs/RenderJob.cpp, src/control/tools/StrokeHandler.cpp, src/gui/PageView.cpp
=> High DPI enabled by default

ui/main.glade
use CTRL+1 ... CTRL+6 for the drawing tools
fixes #779
=> Keyboard shortcut

src/control/zoom/ZoomControl.cpp, src/gui/toolbarMenubar/ToolZoomSlider.cpp, src/gui/toolbarMenubar/ToolZoomSlider.h
- Add logarithmic scale function
- The changes are only every 5th time updated
- One sliding is one sequence
=> modify Zoomslider behaviour

src/gui/toolbarMenubar/ToolZoomSlider.cpp, src/gui/toolbarMenubar/ToolZoomSlider.h
Use Button events should work more consistent, than Focus events.
Clean up
=> Feature logarithmic slider

src/control/Control.cpp
I have not extensivly tested the impact of this change, but it seems to solve problem as you intended in #705.
=> fix #705 switch load of zoom and scroll

src/util/Path.cpp, src/util/Path.h, test/util/PathTest.cpp
=> fixes #816

src/gui/Cursor.cpp
Hi!
As requested in PR #801 I added the "Highlight cursor position" not only in BigCursor mode but in small one too
=> Highlight position in small cursor mode too

src/control/AudioController.cpp, src/gui/dialog/SettingsDialog.cpp, src/gui/dialog/SettingsDialog.h, src/util/audio/AudioPlayer.cpp, src/util/audio/AudioPlayer.h, src/util/audio/AudioQueue.cpp, src/util/audio/AudioQueue.h, src/util/audio/AudioRecorder.cpp, src/util/audio/AudioRecorder.h, src/util/audio/DeviceInfo.cpp, src/util/audio/DeviceInfo.h, src/util/audio/PortAudioConsumer.cpp, src/util/audio/PortAudioConsumer.h, src/util/audio/PortAudioProducer.cpp, src/util/audio/PortAudioProducer.h, src/util/audio/SoxConsumer.cpp, src/util/audio/SoxConsumer.h, src/util/audio/SoxProducer.cpp, src/util/audio/SoxProducer.h
Fixes requested in PR #838.
Additionally fixed one memory leak
Increased conformity with coding conventions (tabs instead of 4 spaces)
=> Minor audio fixes

CMakeLists.txt
=> Fix cmake instructions for FreeBSD

src/gui/inputdevices/NewGtkInputDevice.cpp, src/gui/inputdevices/NewGtkInputDevice.h
=> Hopefully fixes random dots

src/control/AudioController.cpp, src/control/AudioController.h, src/control/Control.cpp, src/control/tools/InputHandler.cpp, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/LoadHandlerHelper.cpp, src/control/xojfile/LoadHandlerHelper.h, src/control/xojfile/SaveHandler.cpp, src/gui/PageViewFindObjectHelper.h, src/model/Stroke.cpp, src/model/Stroke.h, src/util/audio/AudioPlayer.cpp, src/util/audio/AudioQueue.h, src/util/audio/PortAudioConsumer.cpp, src/util/audio/VorbisConsumer.cpp, src/util/audio/VorbisProducer.cpp, src/util/audio/VorbisProducer.h, src/util/serializing/ObjectInputStream.cpp, src/util/serializing/ObjectInputStream.h, src/util/serializing/ObjectOutputStream.cpp, src/util/serializing/ObjectOutputStream.h
Adds the correct timestamp handling to the strokes associated to a recording.
Warn user when start of recording was not successful.
=> Add audio seeking capability

src/control/xml/XmlAudioNode.cpp, src/control/xml/XmlAudioNode.h, src/control/xml/XmlPointNode.cpp, src/control/xml/XmlPointNode.h, src/control/xml/XmlTextNode.cpp, src/control/xml/XmlTextNode.h, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/SaveHandler.cpp, src/control/xojfile/SaveHandler.h, src/control/xojfile/XojExportHandler.cpp, src/control/xojfile/XojExportHandler.h, src/gui/PageView.cpp, src/gui/PageViewFindObjectHelper.h, src/model/AudioElement.cpp, src/model/AudioElement.h, src/model/Stroke.cpp, src/model/Stroke.h, src/model/Text.cpp, src/model/Text.h, src/util/XournalTypeList.h
Implements enhancement #784 (enables linking of audio recordings to typed text)
=> Add capability to link recorded audio to text nodes

src/control/PageBackgroundChangeController.cpp
=> Fix background apply leading to segfault

src/control/Control.cpp, src/gui/XournalView.cpp, src/gui/widgets/XournalWidget.cpp
=> Fix pasted objects are not centered in view.

cmake/README.md, readme/LinuxBuild.md
Here's a few things I figured out while trying to get tex equations working.
=> a few minor documentation fixes

src/control/tools/StrokeHandler.cpp
=> Rerender a point stroke by force

src/control/Control.cpp, src/gui/dialog/SettingsDialog.cpp, src/plugin/Plugin.cpp, src/plugin/Plugin.h, src/plugin/PluginController.cpp, src/plugin/PluginController.h, src/plugin/luapi_application.h, src/util/XournalTypeList.h, ui/main.glade
The regeistered menu items are call the plugin
=> Plugin callback working

plugins/ToggleGrid/plugin.ini, plugins/ToggleGrid/togglegrid.lua, src/control/PageBackgroundChangeController.cpp, src/control/PageBackgroundChangeController.h, src/enums/ActionGroup.enum.h, src/gui/toolbarMenubar/ToolButton.cpp, src/plugin/Plugin.cpp, src/plugin/Plugin.h, src/plugin/PluginController.cpp, src/plugin/luapi_application.h
#785 Allow to change background and grid snapping at the same time
Plugins not yet enabled.
=> Plugin interface. First usable plugin

src/control/Control.cpp, src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/control/zoom/ZoomGesture.cpp, src/gui/XournalView.cpp, src/gui/dialog/SettingsDialog.cpp, src/gui/toolbarMenubar/ToolZoomSlider.cpp, ui/settings.glade
=> WIP: Fix zoom speed

CMakeLists.txt, src/plugin/Plugin.cpp, src/plugin/Plugin.h
@andreasb242 Please check if these changes are transparent to your system. I require them for building on Arch.
This does not solve the build issues if lua is not present.
=> Fix lua build

src/gui/Cursor.cpp, src/gui/toolbarMenubar/ColorToolItem.cpp, src/gui/toolbarMenubar/ColorToolItem.h, src/gui/toolbarMenubar/icon/ColorSelectImage.cpp, src/gui/toolbarMenubar/icon/ColorSelectImage.h
=> If the eraser is active switch to pen on color change

src/control/jobs/CustomExportJob.cpp, src/control/jobs/CustomExportJob.h
=> SVG Export working

src/control/zoom/ZoomControl.cpp
fix #965 
But only the zoom direction. Zoom speed can be modified in settings
=> fix Zoom direction with Ctrl+Scroll

src/gui/Layout.cpp
=> Center pages on screen when zoomed out to show all.

src/gui/PageView.cpp
=> Fix offset of new text nodes

src/control/xojfile/LoadHandler.cpp
Fix reading fileversion attribute when loading file
=> Fixes #990

README.md, po/cs.po, po/de.po, po/it.po, po/pl.po, po/xournalpp.pot, po/zh.po, po/zh_HK.po, po/zh_TW.po, src/gui/dialog/SettingsDialog.cpp, src/gui/dialog/SettingsDialog.h, ui/settings.glade
This PR includes a revised layout of the settings dialogue that reorderes some settings and makes it overall more beautiful and easier to understand.
@andreasb242 or @luco5826:  Please take a look at the italian translation and update accordingly. All other translations need to be updated as well but I'm not fluent enough in any of them to help. English and German should be up to scratch.
=> WIP: Redesign settings

src/gui/toolbarMenubar/ToolZoomSlider.cpp, src/gui/toolbarMenubar/ToolZoomSlider.h
prob I have to merge this with #1022
=> fix issue #1046

README.md
see https://github.com/xournalpp/xournalpp/pull/956#issuecomment-469467589
=> README.md: remove audio record and playback feature instructions for <= 1.0.7

src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/control/tools/ArrowHandler.cpp, src/control/tools/ArrowHandler.h, src/control/tools/BaseStrokeHandler.cpp, src/control/tools/BaseStrokeHandler.h, src/control/tools/CircleHandler.cpp, src/control/tools/CircleHandler.h, src/control/tools/CoordinateSystemHandler.cpp, src/control/tools/CoordinateSystemHandler.h, src/control/tools/InputHandler.h, src/control/tools/RectangleHandler.cpp, src/control/tools/RectangleHandler.h, src/control/tools/RulerHandler.cpp, src/control/tools/RulerHandler.h, src/control/tools/StrokeHandler.cpp, src/control/tools/StrokeHandler.h, src/gui/Cursor.cpp, src/gui/Cursor.h, src/gui/LayoutMapper.h, src/gui/PageView.cpp, src/gui/dialog/SettingsDialog.cpp, src/gui/inputdevices/PositionInputData.cpp, src/gui/inputdevices/PositionInputData.h, ui/settings.glade
Thought it would be a quick modification but turned out to be a tiny bit more work.
A few rough edges:
If you have the control key down it never gets to the code to start drawing. You have to press control after starting the circle.
Also - doesn't redraw the circle unless the mouse is moved..
=> WIP  fixes #742 - Circles from center - use Control Key

po/de.po
Some minor fixes/changes for the german translation.
=> spelling on german translation corrected

src/control/xml/DoubleArrayAttribute.cpp, src/control/xml/XmlStrokeNode.cpp
=> Missing delimiting spaces in xml array writes.

src/control/Control.cpp
Fixes #1122
This PR will be merged after three (3) days unless there's a problem.
=> Use g_file_copy instead of g_rename when moving autosaves

po/de.po, po/xournalpp.pot, ui/settings.glade
Updates german translation and fixes #1134
=> Fixes #1134

build-flatpack.sh
Just fixed the filename in build-flatpak.sh so it really matches the flatpak yml filename.
=> fixed typo in build-flatpack.sh

src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/gui/XournalView.cpp, src/gui/inputdevices/InputContext.cpp, src/gui/inputdevices/InputContext.h, src/gui/inputdevices/TouchInputHandler.cpp, src/gui/inputdevices/TouchInputHandler.h
=> Enable scrolling while using the zoom gesture

src/util/DeviceListHelper.cpp
=> Update device listing in settings dialog for newer gdk versions

src/gui/inputdevices/PenInputHandler.cpp
Fixes #1163. This PR will be merged in three (3) days unless there are any problems.
=> Fix cursor not reappearing after editing text in new input system

appimagecraft.yml
Just download [appimagecraft](https://github.com/TheAssassin/appimagecraft) (either install via `pip` or use the provided AppImage) and run it like `appimagecraft build`. An AppImage should be produced and end up in the root of your local clone.
**Note:** appimagecraft is a very very new tool I wrote to eliminate the need for writing some bash scripts etc., it's all handled by appimagecraft, all you need to do is provide some information in the form of a small YAML file.
It's unlike but if it should not work for you, your feedback is appreciated, please feel free to open issues in the tracker.
Fixes #944.
Contributes to #1176.
=> Add appimagecraft YML

src/control/tools/ImageHandler.cpp
Fixes #1158
Ability of editing for newly added image
=> Adding of ability for editing for newly added image

src/control/settings/ButtonConfig.cpp, src/control/settings/Settings.cpp
=> Fix eraser thickness not stored in settings and not reset on tool change

CMakeLists.txt
Patch thanks to @moghiseh, closes #1180
=> Fix libzip dependency issue 

po/cs.po, po/de.po, po/it.po, po/pl.po, po/zh.po, po/zh_HK.po, po/zh_TW.po, src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/gui/dialog/SettingsDialog.cpp, src/gui/inputdevices/AbstractInputHandler.cpp, src/gui/inputdevices/AbstractInputHandler.h, src/gui/inputdevices/old/InputSequence.cpp
=> Enable on the fly resolving of pressure sensitivity

windows-setup/build-portaudio.sh
This should be selfexplanatory...
=> Add integrity check for download of portaudio library

src/gui/XournalppCursor.cpp, src/gui/XournalppCursor.h
Fix some bugs preventing windows builds
=> Quickfix build

com.github.xournalpp.xournalpp.yaml
=> Add --persist=.xournalpp to flatpak manifest

src/control/XournalMain.cpp, ui/about.glade, ui/goto.glade, ui/main.glade, ui/pdfpages.glade, ui/plugin.glade, ui/pluginEntry.glade, ui/settings.glade
Fixes a lot of the text strings
Removes translation attributes from untranslatable strings
=> Fix translations

src/control/Control.cpp, src/control/Control.h, src/control/jobs/SaveJob.cpp
Fixes #1233. Please test the PR and let me know if there is any regression!
=> Fix document close handling logic

src/gui/MainWindow.cpp, src/gui/dialog/ButtonConfigGui.cpp, src/gui/dialog/ButtonConfigGui.h, src/gui/dialog/SettingsDialog.cpp, src/gui/dialog/SettingsDialog.h, src/util/DeviceListHelper.cpp, src/util/DeviceListHelper.h
removed leak in MainWindow.cpp
removed leak in SettingsDialog.cpp
Refactored DeviceListHelper to a static factory,
because this was a factory object which owned self created data.
updated const corectness of InputDevice
=>  Removed memory leaks:

src/util/Range.cpp, src/util/Range.h, src/util/Rectangle.cpp, src/util/Rectangle.h
Another refactoring part of refactor_layout_resize, which has nothing to do with it, but which is needed by the changes there.
=> Range const correctness

po/nl_NL.po
=> Added Dutch (Netherlands) translation

ui/exportSettings.glade
As per suggestion of @Technius, I have removed the seemingly incriminated line of code leading to this bug
https://github.com/xournalpp/xournalpp/issues/1285
As a layman in terms of programming, I do not have the skills to build and test this on my machine in a proper way
=> Update exportSetting.glade to fix crash

src/gui/PageViewFindObjectHelper.h
=>  Fix select object only checking first object containing select point

src/control/Control.cpp, src/control/PageBackgroundChangeController.cpp, src/control/ScrollHandler.cpp, src/control/layer/LayerController.cpp, src/gui/MainWindow.cpp, src/gui/XournalView.cpp, src/gui/dialog/ButtonConfigGui.cpp, src/gui/dialog/PageTemplateDialog.cpp, src/gui/dialog/SelectBackgroundColorDialog.cpp, src/gui/dialog/SettingsDialog.cpp, src/gui/sidebar/Sidebar.cpp, src/gui/sidebar/indextree/SidebarIndexPage.cpp, src/gui/sidebar/previews/base/SidebarPreviewBase.cpp, src/gui/sidebar/previews/layer/SidebarPreviewLayers.cpp, src/gui/sidebar/previews/page/SidebarPreviewPages.cpp, src/model/Document.cpp, src/model/LinkDestination.cpp, src/model/XojPage.cpp, src/model/XojPage.h, src/util/Path.cpp, src/util/Path.h, src/util/Util.cpp, src/util/Util.h, src/util/XournalType.h
Again some refactoring commits previously done in refactor_layout_resize, which do not belong there.
=> Refactoring

src/control/settings/Settings.cpp, src/control/xml/DoubleArrayAttribute.cpp, src/control/xml/DoubleAttribute.cpp, src/control/xml/XmlPointNode.cpp, src/control/xml/XmlStrokeNode.cpp, src/util/Util.cpp, src/util/Util.h
Fixes #1277.
If you decide to close this PR because you decide not to have fixed coordinate precision, that is OK with me. I'm just opening this pull request since the code is complete, and it's ready for review.
=> Fix coordinate precision to 8 decimal places to reduce file size

ui/main.glade
Fixes #1419. Regression introduced by #1414. The glade file was not updated in the PR.
=> Fix application icon not showing

src/control/tools/EditSelectionContents.cpp, src/gui/FloatingToolbox.cpp
=> remove unused vars

src/gui/dialog/toolbarCustomize/CustomizeableColorList.cpp, src/gui/toolbarMenubar/model/ToolbarColorNames.cpp
=> Fix a typo in a translatable string

src/gui/inputdevices/InputEvents.h
=> default pressure should be NO_PRESSURE

src/gui/Layout.cpp, src/gui/Layout.h
The fast algorithm was too difficult to understand/debug and prone to error on future code refactoring... so uncomment the concise stl-based binary search which was already there for testing and use it instead.
=> Simplify layout get view at

src/gui/Layout.cpp
=> fix background flash

readme/LinuxBuild.md
I needed to install it before building Xournalpp
=> Add `make` to list of Fedora dependencies

readme/LinuxBuild.md
Based on #1482 this PR includes some changes to the layout and marks the discouraged installation directly from source more explicitly.
=> Improve build instructions for Linux

src/control/settings/Settings.cpp, src/control/settings/Settings.h
=> improved const correctness in Settings, probably fixes some segfaults.

CHANGELOG.md, ui/about.glade
This is the tentative changelog for Xournal++ 1.0.14. Please let me know if I missed anything.
In the future, this changelog file should be updated at regular intervals during development so it will become easier to track changes.
=> Add changelog file

src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/control/zoom/ZoomGesture.cpp, src/gui/inputdevices/TouchInputHandler.cpp, src/gui/inputdevices/TouchInputHandler.h, src/gui/toolbarMenubar/ToolZoomSlider.cpp
Calculate the zoom value by hand and not use gtk_gesture for zooming.
Currently always zooms to center of screen.
This fixes #404, but the algorithm probably only works for my screen and I would be glad if someone could give some input there.
=> WIP: Add a custom pinch to zoom algorithm

src/model/Point.h, src/model/Stroke.cpp, src/model/Stroke.h
Replaced a plain old dynamic allocated C-array with a std::vector
=> Fix undefined behaviour

src/util/audio/AudioQueue.h, src/util/audio/PortAudioConsumer.cpp, src/util/audio/PortAudioProducer.cpp, src/util/audio/VorbisConsumer.cpp, src/util/audio/VorbisProducer.cpp
@morrolinux Please test this on your machine
Fixes #1458
=> Add internal locking to AudioQueue

CHANGELOG.md, src/control/settings/Settings.cpp, src/control/settings/Settings.h
Switches to new input system as default
Updates the changelog with the changes since the last release
=> Switch to new inputsystem as default

src/control/xml/DoubleArrayAttribute.cpp, src/control/xml/DoubleArrayAttribute.h, src/control/xml/XmlNode.cpp
Fixes #1401. Merging in 3 days if there are no objections.
=> Refactor DoubleArrayAttribute to use std::vector

.clang-tidy, src/gui/dialog/AboutDialog.cpp, src/gui/dialog/AboutDialog.h
@JJones780 can you look over this?
=> Add a clang-tidy conf file

src/gui/PageView.cpp, src/gui/PageViewFindObjectHelper.h
Fixes #1573. Merging in 3 days if there are no objections.
=> Fix audio playback failure not showing message to user

src/gui/Layout.cpp
=> Reintroduce algorithm to select current page when scroll changes

src/gui/TextEditor.cpp
More proper way to test for modifier keys, according to [https://developer.gnome.org/gtk3/stable/checklist-modifiers.html](url)
=> Fixed test for modifier keys

.clang-tidy, CMakeLists.txt, src/control/Control.cpp, src/control/ToolEnums.cpp, src/control/pagetype/PageTypeHandler.cpp, src/control/settings/MetadataManager.h, src/undo/InsertUndoAction.cpp, src/util/DeviceListHelper.cpp
=> fixup clang-tidy file to not report on GTK macros definitions

src/gui/sidebar/previews/page/SidebarPreviewPages.cpp, src/gui/sidebar/previews/page/SidebarPreviewPages.h
Fixes #1637. Merging in 3 days if there are no objections.
=> Fix sidebar preview menu Move Up/Down not disabled on first/last page

CMakeLists.txt, azure-pipelines/steps/build_mac.yml, cmake/find/FindCXX17.cmake, cmake/find/FindFilesystem.cmake, src/filesystem.h.in, src/util/CMakeLists.txt
Please check if the licensing is ok.
=> Initial Commit: Use std::filesystem or fallback to boost::filesystem

desktop/com.github.xournalpp.xournalpp.appdata.xml, desktop/com.github.xournalpp.xournalpp.desktop, desktop/x-xojpp.desktop, desktop/x-xopp.desktop, desktop/x-xopt.desktop
As I was updating the Debian packaging info in preparation for (I hope) an actual upload to Debian, the build tooling noticed some minor issues. These are addressed here.
=> Tiny changes demanded by lintian during Debian packaging

src/gui/sidebar/indextree/SidebarIndexPage.cpp, src/gui/sidebar/indextree/SidebarIndexPage.h
Fixes #1582. Merging in 24h if there are no objections.
=> Fix deadlock when another PDF with an outline is opened

src/control/settings/Settings.cpp
Fixes xournalpp/xournalpp#1074
=> Avoid overwriting settings file during its parsing

src/control/jobs/RenderJob.cpp, src/control/jobs/RenderJob.h, src/control/tools/BaseStrokeHandler.cpp, src/control/tools/SplineHandler.cpp, src/control/tools/SplineHandler.h, src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/gui/Layout.cpp, src/gui/Layout.h, src/gui/PageView.cpp, src/gui/PageView.h, src/gui/Redrawable.h, src/gui/XournalView.cpp, src/gui/XournalView.h, src/gui/widgets/XournalWidget.cpp, src/gui/widgets/XournalWidget.h, src/model/Element.cpp, src/model/Element.h, src/model/PageHandler.cpp, src/model/PageHandler.h, src/model/PageListener.h, src/undo/FontUndoAction.cpp, src/undo/TextBoxUndoAction.cpp, src/undo/TextUndoAction.cpp, src/util/Rectangle.cpp, src/util/Rectangle.h
=> Make Rectangle a template class

src/control/jobs/RenderJob.cpp, src/control/jobs/RenderJob.h, src/gui/PageView.cpp, src/gui/PageView.h
A small optimization of the renderer, by removing a double indirection and unnecessary heap allocation (small objects).
=> Small optimization in renderer

src/gui/inputdevices/AbstractInputHandler.cpp, src/gui/inputdevices/AbstractInputHandler.h, src/gui/inputdevices/InputContext.cpp, src/gui/inputdevices/InputEvents.cpp, src/gui/inputdevices/InputEvents.h, src/gui/inputdevices/KeyboardInputHandler.cpp, src/gui/inputdevices/KeyboardInputHandler.h, src/gui/inputdevices/MouseInputHandler.cpp, src/gui/inputdevices/MouseInputHandler.h, src/gui/inputdevices/PenInputHandler.cpp, src/gui/inputdevices/PenInputHandler.h, src/gui/inputdevices/StylusInputHandler.cpp, src/gui/inputdevices/StylusInputHandler.h, src/gui/inputdevices/TouchDrawingInputHandler.cpp, src/gui/inputdevices/TouchDrawingInputHandler.h, src/gui/inputdevices/TouchInputHandler.cpp, src/gui/inputdevices/TouchInputHandler.h
=> Fixed memory leak in InputContext and PenInputHandler.

src/control/settings/Settings.cpp, src/control/settings/Settings.h
Replaced custom ref count by a std::shared_ptr
=> Fixed possible self assigning bug in SElement.

src/Xournalpp.cpp, src/control/LatexController.cpp, windows-setup/build-setup.sh
=> Fix latex tool not working on Windows

src/control/XournalMain.cpp
=> Set application name in binary to desktop id

src/control/settings/Settings.cpp, src/control/settings/Settings.h, src/control/tools/SnapToGridInputHandler.cpp, src/control/tools/SnapToGridInputHandler.h, src/gui/dialog/SettingsDialog.cpp, src/model/Snapping.h, ui/settings.glade
=> Added option to change grid size.

src/gui/toolbarMenubar/ToolMenuHandler.cpp, src/gui/toolbarMenubar/model/ToolbarModel.cpp
This PR fixes https://github.com/xournalpp/xournalpp/issues/1784 
It simply adds an print button.
=> Print button

ui/pageTemplate.glade
Fixes #1524. Merging in 24h if there are no objections.
=> Fix wording of new page template dialog

README.md
=> Added info on installation via snap

src/control/Control.cpp, src/util/XojMsgBox.cpp
Fix #1983. Merge pending testing on Windows.
=> Fix replace file dialog overwriting files erroneously

src/gui/dialog/ExportDialog.cpp, ui/exportSettings.glade
Fixes #1977. Also includes some minor code cleanup and modernization of the glade file.
=> Fix Enter in export dialog not working when page radio btn has focus

.github/ISSUE_TEMPLATE/bug_report.md, src/control/XournalMain.cpp, src/gui/dialog/AboutDialog.cpp, ui/about.glade
This is taken from the stack overflow answer: https://stackoverflow.com/a/126193
=> Add command for libgtk version to bug template

src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h, src/gui/XournalView.cpp, src/gui/inputdevices/TouchInputHandler.cpp, src/gui/inputdevices/TouchInputHandler.h, src/gui/toolbarMenubar/ToolZoomSlider.cpp, src/util/Point.h
=> Cleanup of ZoomControl and fix of Zoom and Scroll

src/gui/XournalppCursor.cpp
This commit should fix bug #2056 (and possibly bug #2003) while still updating the cursor after the eraser (or pen/highlighter) size changes. Check it out!
=> fix bug #2056

CMakeLists.txt, src/config.h.in, src/control/Control.cpp, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/LoadHandler.h, src/control/xojfile/SaveHandler.cpp
Fixes #1990. This should be backported to the `1.0.x` series before the `1.1.0` release.
=> Check file format version on load

plugins/QuickScreenshot/main.lua, plugins/QuickScreenshot/plugin.ini, src/plugin/luapi_application.h
This is the plugin promised in #2037
=> QuickSnapshot plugin added to xournal++.

src/control/Control.cpp
=> update page count after deleting page

src/pdf/base/XojCairoPdfExport.cpp
This fixes #2119
The text spacing problem #1390 remains unaffected by this PR, though.
=> fix pdf export problem with dashes

cmake/find/FindFilesystem.cmake
=> fixup gcc7 can't find std::filesystem::relative

plugins/ColorCycle/main.lua, plugins/ColorCycle/plugin.ini, src/plugin/luapi_application.h
This has been on the wish list for quite a while, see #919 and #1835.
Closes #1835.
=> Plugin for cycling through a color list

src/undo/ColorUndoAction.cpp
=> fix color change undo crash

src/gui/TextEditor.cpp, src/util/Color.h
=> Fixed black TextEditor selection color

src/control/xojfile/LoadHandler.cpp
=> fix doubled loaded pdf pages bug

src/control/Control.cpp, src/control/jobs/BaseExportJob.cpp, src/control/stockdlg/ImageOpenDlg.cpp, src/control/stockdlg/XojOpenDlg.cpp, src/gui/dialog/LatexSettingsPanel.cpp, src/gui/dialog/PageTemplateDialog.cpp, src/plugin/luapi_application.h
- Fixes #2266
- gtk_file_chooser_set_x got utf8 encoded paths, but only supports local encoded paths
- replaced gtk_file_chooser_set_x_uri with gtk_file_chooser_set_x on several places
=> Fixed some file_chooser issues including a wrong recent path for image import.

src/model/Element.cpp
=> Fixup #2254

src/control/tools/EditSelection.cpp, src/control/tools/EditSelectionContents.cpp
=> fix resizing bug after pasting object

src/control/Control.cpp, src/control/LatexController.cpp, src/control/XournalMain.cpp, src/control/jobs/AutosaveJob.cpp, src/control/jobs/BaseExportJob.cpp, src/control/settings/Settings.cpp, src/control/stockdlg/ImageOpenDlg.cpp, src/control/stockdlg/XojOpenDlg.cpp, src/control/xojfile/LoadHandler.cpp, src/control/xojfile/SaveHandler.cpp, src/gui/GladeGui.cpp, src/gui/MainWindow.cpp, src/gui/dialog/LatexSettingsPanel.cpp, src/gui/dialog/PageTemplateDialog.cpp, src/gui/dialog/SettingsDialog.cpp, src/pdf/popplerapi/PopplerGlibDocument.cpp, src/plugin/PluginController.cpp, src/util/PathUtil.cpp, src/util/PathUtil.h
=> fix utf8 problems on windows, loading files with special characters

src/control/Control.cpp, src/control/xojfile/LoadHandler.cpp, src/model/Document.cpp, src/plugin/Plugin.cpp, src/plugin/Plugin.h, src/plugin/PluginController.cpp, src/util/OutputStream.cpp
Replaced string based filenames in Plugin API with `fs::path`
Fixed a bug, that prevented plugins to load
=> Fixed some encoding issues with paths

src/control/jobs/BaseExportJob.cpp, src/control/jobs/BaseExportJob.h, src/control/jobs/CustomExportJob.cpp, src/control/jobs/CustomExportJob.h, src/control/jobs/PdfExportJob.cpp, src/control/jobs/PdfExportJob.h
=> Fixed a regression, that "export as" ran into a segmentation fault

src/gui/dialog/PluginDialog.cpp, src/gui/dialog/PluginDialog.h, src/gui/dialog/PluginDialogEntry.cpp, src/gui/dialog/PluginDialogEntry.h, src/plugin/Plugin.cpp, src/plugin/Plugin.h, src/plugin/PluginController.cpp, src/plugin/PluginController.h
- use std::unique_ptr
- removed XournalType.h
- fixed many clang-tidy warnings.
- consistently use fs::path
- mark functions override instead of virtual
=> Refactored Plugin related code

src/control/jobs/BlockingJob.cpp
=> Fix scrolling after save bug

readme/LinuxBuild.md
Probably missing `C` in `-DPACK_GENERATOR="TGZ"`.
=> Linux build fix var name

windows-setup/build-setup.sh
=> Derive supported locales in windows setup creator from available translations

src/gui/XournalppCursor.cpp
=> fix selection cursor update for vertical scaling

ui/main.glade
=> Fix missing menu name

src/control/tools/EditSelection.cpp
=> Fix resizing for bottom left anchor

src/gui/XournalView.cpp
=> Rerender page after page size has changed

src/control/XournalMain.cpp, src/control/settings/MetadataManager.cpp
Fixes #2445 
Without this fix the metadata manager simply does not work.
=> Fix and simplify metadata manager read

src/control/XournalMain.cpp, src/control/jobs/BlockingJob.cpp, src/control/zoom/ZoomControl.cpp, src/gui/XournalView.cpp, src/gui/XournalView.h
I have tested that everything works as expected.
=> [1.0.x] Backports of recent bugfixes

azure-pipelines/clang-format-applied.yml
=> Update pipeline to use both clang-format-12 and clang-format-10

src/control/tools/EditSelection.cpp, src/control/tools/EditSelection.h, src/control/tools/EditSelectionContents.cpp, src/control/tools/EditSelectionContents.h
=> fix copy selection when rotated and scaled

PreLoad.cmake, azure-pipelines/continuous-integration.yml, azure-pipelines/release.yml
A dirty hotfix to fix, that MinSizeRel breaks our code
For further information see #2523
=> Removes the force to use Ninja.

src/gui/dialog/ButtonConfigGui.cpp, src/gui/dialog/ButtonConfigGui.h
Btw: why is the mapping of Thickness enum and dropdown index implemented like that?
Should we refactor it by using a map or something?
Fixes #1657
=> Added very thick/thin to default tool preferences

src/control/XournalMain.cpp, src/control/jobs/CustomExportJob.cpp, src/control/jobs/CustomExportJob.h, src/gui/dialog/ExportDialog.cpp, src/gui/dialog/ExportDialog.h, src/pdf/base/XojCairoPdfExport.cpp, src/pdf/base/XojCairoPdfExport.h, src/pdf/base/XojPdfExport.h, ui/exportSettings.glade
due to conflict with other presentation mode.
see https://github.com/xournalpp/xournalpp/pull/2589#issuecomment-751785476
=> rename PDF Presentation Mode to Progressive Mode

src/control/Control.cpp
Page and layer previews will be updated every 5 seconds (like it was in version 1.0.x). Fixes #2378. Fixes #2455.
=> Fix page and layer preview updates

ui/settings.glade
This is consistent with
https://github.com/xournalpp/xournalpp/pull/2592
(and should have been done there, but somewhat I forgot to)
=> don't impose label width

src/Xournalpp.cpp, src/enums/generated/ActionGroup.generated.cpp, src/enums/generated/ActionType.generated.cpp, src/gui/inputdevices/touchdisable/TouchDisableX11.cpp, src/gui/toolbarMenubar/ToolMenuHandler.cpp, src/gui/toolbarMenubar/model/ToolbarColorNames.cpp, src/model/TexImage.cpp, src/plugin/Plugin.cpp, src/plugin/PluginController.cpp, src/util/PlaceholderString.cpp
- This only works for windows v. >= 1804
Fixes #2395
=> Changing the console encoding to utf-8 on windows

src/gui/inputdevices/InputEvents.cpp
Fixes #2123.
Thanks to @bhennion for finding the cause of the problem.
=> fix touch drawing with pen

src/view/DocumentView.cpp
=> fix text position when using background image

azure-pipelines/clang-format-applied.yml
=> Fix clang-format CI check

README.md
=> Fix typo in README.md (Ubuntu versions)

src/gui/TextEditor.cpp
=> Fix preedit cursor position

azure-pipelines/steps/install_deps_ubuntu.yml
=> add gettext dependency

src/control/tools/EditSelectionContents.cpp, src/undo/ScaleUndoAction.cpp
Fixes #2464. 
See #2464 for details.
=> Fix invalid stroke width and image dimensions

plugins/QuickScreenshot/main.lua, src/plugin/luapi_application.h
These are the changes suggested by @createyourpersonalaccount in #2787
=> Make screenshot renaming work across partitions

src/control/PdfCache.h, src/pdf/base/XojCairoPdfExport.cpp, src/pdf/base/XojPdfPage.h, src/view/PdfView.h
=> Remove /cairo from include paths

azure-pipelines/jobs/release_ubuntu.yml, azure-pipelines/release.yml
Fixes #2945 
Not sure if it works, but we will see it from testing the Azure pipelines.
=> fix localizations for Azure pipelines builds

src/gui/sidebar/previews/page/SidebarPreviewPages.cpp
=> Fix crash for moving sidebar pages via plugin

src/gui/toolbarMenubar/ToolMenuHandler.cpp
=> Rename tool button from "Ruler" to "Draw Line"

plugins/MigrateFontSizes/main.lua, src/plugin/Plugin.cpp
=> allow using the system Lua package path

src/gui/inputdevices/StylusInputHandler.cpp
Fixes https://github.com/xournalpp/xournalpp/issues/2088
My pen device is weird and my driver is probably also weird (see issue for detail), so I had lots of problems with the new input system, that were not there with the old/removed input system. The problems include:
- disappearing last strokes when a new stroke is started
- touchpad input was drawing without pressed button after some strokes
- strokes sometimes become very jaggy and handwriting becomes unreadable
- when starting a new stroke a little spike to the last segment is drawn
These problems are all fixed for me by this patch. The problem was my driver sending some weird events. Here is a collection of things I recorded:
- Press event was sent, motion events were sent starting with positive pressure and ending with zero …
=> Handle buggy driver events better to avoid vanishing lines

src/view/background/IsometricBackgroundPainter.cpp, src/view/background/LineBackgroundPainter.cpp, test/files/preview-test-no-preview.unzipped.xoj, test/files/preview-test.unzipped.xoj, test/files/test1.unzipped.xoj, ui/pagetemplates.ini
=> Isometric grid fix

src/control/PrintHandler.cpp
=> PrintHandler: remove old config on failure

src/gui/MainWindow.cpp, src/gui/toolbarMenubar/ToolMenuHandler.cpp, src/gui/toolbarMenubar/ToolMenuHandler.h, src/gui/toolbarMenubar/ToolPageSpinner.cpp, src/gui/toolbarMenubar/ToolPageSpinner.h, src/gui/widgets/SpinPageAdapter.cpp, src/gui/widgets/SpinPageAdapter.h
=> Added vertical mode for the pagespinner tool

src/control/latex/LatexGenerator.cpp, src/util/PathUtil.cpp, src/util/PathUtil.h
=> Convert temp path from 8.3 to long form on Windows.

ui/iconsColor-light/hicolor/scalable/actions/xopp-thickness-thicker.svg
=> Port thickness-thicker to light theme

src/control/Control.cpp, src/control/Control.h, src/pdf/popplerapi/PopplerGlibDocument.cpp
- Reordered some calls, to prevent segfaults on export.   
- Added explicit wait.
- Fixed some minor casting issues
=>  Fixes #1916

src/control/xojfile/LoadHandler.cpp
Fixes #3165 
~I have found two problems, one must have been there for a long time, the other is a regression only in 1.1.0+dev. They are both related to this line:~
https://github.com/xournalpp/xournalpp/blob/28faadd6352aa77b5596fb3e698a5ce8a79693aa/src/control/xojfile/LoadHandler.cpp#L381
~The regression comes from the fact, that `filepath` is of type `fs::path` and not the filename string (which, for a cloned background image, is a string representation of a number).~
The ~other~ problem was that the pages are added too late to the document. So `getPage()` will return a `nullpointer`.
The pages are only added to the document once the whole `xopp`-file has been parsed. 
https://github.com/xournalpp/xournalpp/blob/28faadd6352aa77b5596fb3e698a5ce8a79693aa/src/control/xojfile/LoadHandler.cpp …
=> Quick fix for making cloned background images load

copyright.txt, scripts/compare_license.py, src/control/xojfile/LoadHandler.h, src/control/xojfile/LoadHandlerHelper.cpp, src/control/xojfile/LoadHandlerHelper.h, src/gui/GladeSearchpath.cpp, src/gui/dialog/LatexDialog.cpp, src/gui/widgets/ZoomCallib.cpp
- add copyright.txt to repo using the debian copyright format
- add script to easily check if something needs to be updated
in the copyright.txt
=> Add copyright.txt and test script

scripts/compare_license.py
This is a follow up on #3120, updating the latest git commit hash.
=> update latest git commit hash

AUTHORS, copyright.txt, src/gui/dialog/AboutDialog.cpp, ui/about.glade
See AUTHORS file and old and new (current) image of the about dialog:
old:
new:
=> Update authors list and about dialog

ui/README.md
- add README to ui folder to ensure the knowledge of where to find the
original icon svgs does not get lost
=> Add README to ui folder

src/model/Stroke.cpp
=> Optimized the calculation of stroke sizes

README.md
=> Add Xournal++ pronunciation

src/gui/inputdevices/InputEvents.cpp, src/gui/inputdevices/InputEvents.h
The previous PR'S are still in this PR, so I had better profiling information.
=> Performance gdkeventguard

src/gui/PageView.cpp
=> Fix text snapping issue

src/control/zoom/ZoomControl.cpp, src/control/zoom/ZoomControl.h
* Ctrl+scroll and step part of @redweasel's #2837
=> More natural ctrl+scroll zooming

src/view/StrokeView.cpp
Fix #3578.
The fix is really simple and is ready.
I'll merge this in 72 hours, leaving you time to give it a glance and object.
=> Fix failing assert #3578

src/gui/sidebar/previews/page/SidebarPreviewPages.cpp
- fixed a bug where the sidebar page preview was stuck and not responding (closes #3585)
=> Fix sidebar page preview stuck and not responding

src/core/model/eraser/ErasableStroke.cpp, src/core/model/eraser/ErasableStroke.h
=> Fix #3640 - Change ErasableStroke::PartList from std::vector to std::list

src/core/control/shaperecognizer/ShapeRecognizer.cpp, src/core/control/tools/StrokeHandler.cpp
=> Fix negative pressure values of strokes

src/control/tools/InputHandler.cpp
Merging in `release-1.1` in 24h unless someone objects.
This will also need to be added to master ASAP: the bug corrupts files (with little harm, but still). How should I do that? Another merge, cherry-picking?
=> Fix #3651 - remove pressure value on Highlighter strokes first point

rpm/fedora/xournalpp.spec
This pull request brings some fixes.
=> Update spec file

azure-pipelines/steps/build_mac.yml
This should make the pipeline run again.
=> fix indentation in build mac script

src/core/control/jobs/Job.cpp, src/core/control/jobs/Job.h
Code cleanup to provide simpler atomic ref counting in Job with better performance.
Reviewers: since this affects a vital part of the application, please review this PR carefully.
=> Replace Job ref count mutex with atomic integer

src/core/view/StrokeView.cpp
Fixes #3795.
See https://github.com/xournalpp/xournalpp/issues/3795#issuecomment-1034554545
=> Fixup ffa681e8ad17ef242c427c0b1f48a18d602ac5bd

src/core/plugin/luapi_application.h
Adds additional functionality to the Lua API to make [inkpath](https://github.com/willnilges/inkpath) work. The plugin uses [autotrace](https://github.com/yy502/autotrace) to vectorize whiteboard strokes and insert them in the working document. See discussion of the feature [here](https://github.com/xournalpp/xournalpp/issues/2850). And [here](https://github.com/WillNilges/inkpath/issues/10) is the current roadmap for the project.
- `getFilePath`: Opens a GTK File Chooser dialogue used to prompt user to pick an image to transcribe. Allows filtering based on file type to make it useful for other file-choosing purposes.
- `addStrokes`: Places a batch of strokes on the canvas when given a list of lists of X, Y, and optionally pressure coordinates. Also takes in pen tool options per-stroke. …
=> Inkpath api extensions

src/core/gui/PageView.cpp
`enum constant in boolean context [-Wint-in-bool-context]`
=> Bugfix obvious enum comparison

src/control/tools/EditSelection.cpp
=> Fix possible bug in edge pan timer destruction

src/gui/TextEditor.cpp, src/view/TextView.cpp
This PR fixes a performance issue with the text tool.
=> Fix TextEditor repaint bounds

src/core/gui/inputdevices/SetsquareInputHandler.cpp
=> make setsquare handle mouse-keyboard combo

ui/xournalpp.css
=> make toolbars and menubar not react to dragging

CMakeLists.txt, src/util/CMakeLists.txt
=> Fix backtrace linker flags

src/core/control/ClipboardHandler.cpp, src/core/control/Control.cpp, src/core/control/PdfCache.cpp, src/core/control/PdfCache.h, src/core/control/UndoRedoController.cpp, src/core/control/jobs/PreviewJob.cpp, src/core/control/tools/EditSelection.cpp, src/core/control/tools/EditSelection.h, src/core/control/tools/EditSelectionContents.cpp, src/core/control/tools/EditSelectionContents.h, src/core/control/tools/VerticalToolHandler.cpp, src/core/control/tools/VerticalToolHandler.h, src/core/gui/PageView.cpp, src/core/gui/XournalView.cpp, src/core/gui/widgets/XournalWidget.cpp, src/core/model/Document.cpp, src/core/model/Document.h, src/core/model/ElementContainer.h, src/core/pdf/base/XojPdfDocument.cpp, src/core/pdf/base/XojPdfDocument.h, src/core/pdf/base/XojPdfDocumentInterface.h, src/core/pdf/base/XojPdfPage.h, src/core/pdf/popplerapi/PopplerGlibDocument.cpp, src/core/pdf/popplerapi/PopplerGlibDocument.h, src/core/pdf/popplerapi/PopplerGlibPage.cpp, src/core/pdf/popplerapi/PopplerGlibPage.h, src/core/view/DocumentView.cpp, src/core/view/DocumentView.h
This PR contains minor code cleanups from #3969, to simplify the reviewing.
It contains:
* Fix warnings in PdfCache
* Tiny cleanup in XournalWidget
* Move ElementContainer from view to model
* Const qualify getters
This can be reviewed.
=> Code cleanup

src/core/control/DeviceListHelper.cpp, src/core/control/RecentManager.cpp, src/core/control/RecentManager.h, src/core/control/jobs/RenderJob.cpp, src/core/gui/MainWindow.cpp, src/core/gui/dialog/FormatDialog.cpp, src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp, src/core/pdf/popplerapi/PopplerGlibPage.cpp, src/util/include/util/GListView.h
Added a Wrapper to GLists similar to c++20 views,
to iterate over GList structures by c++11 for loops.
=> GListView - A sane Wrapper to iterate over GLists

src/core/gui/PageView.cpp
=> Fix crash when button pressed while vertical space tool active

src/core/control/RecentManager.cpp, src/core/control/RecentManager.h, src/core/gui/dialog/backgroundSelect/ImagesDialog.h, src/util/include/util/GListView.h
Also fixes the equality operator of GListView
Fixes #3987
=> Fixes the ordering of recent files

src/gui/TextEditor.cpp
Fixes #3977.
@tattsan can you test to see if this fixes the issue for you?
=> Fix TextEditor render delay regression

src/core/control/Control.cpp, src/core/gui/TextEditor.cpp
If this looks good, I will fast forward the merge commit manually. The actual changeset is:
* https://github.com/xournalpp/xournalpp/commit/0091b48fe691b95d186f60b67ca762b0f5624063
* https://github.com/xournalpp/xournalpp/commit/38258a498f9edfc8cea0e842da745dcaa0fa7505
Merging in 24 hours if there are no objections. @xournalpp/core
=> Merge release-1.1 into master

src/core/model/Image.cpp
Fixes #4009.
This was tested with the document provided by @aberetta145.
=> Fix image loading failure on some images

CMakeLists.txt, src/core/gui/inputdevices/AbstractInputHandler.cpp, src/core/gui/inputdevices/HandRecognition.cpp
=> Fixed X11 Hand Recognition not working 

src/core/gui/MainWindowToolbarMenu.cpp, src/core/gui/toolbarMenubar/AbstractItem.h, src/core/gui/toolbarMenubar/AbstractToolItem.h, src/core/gui/toolbarMenubar/ColorToolItem.cpp, src/core/gui/toolbarMenubar/ColorToolItem.h, src/util/NamedColor.cpp, src/util/include/util/NamedColor.h
Will merge after I found out, if this also happens in the newest release
=> Fixed Undefined Behaviour in ColorToolItem.cpp:142

windows-setup/xournalpp.nsi
=> windows: fix installer crash

src/core/control/tools/StrokeHandler.cpp
Discussed here: https://github.com/xournalpp/xournalpp/discussions/4072
=> Prevent fractional translation of mask surface

src/core/control/jobs/RenderJob.cpp, src/core/control/tools/VerticalToolHandler.cpp, src/core/control/tools/VerticalToolHandler.h, src/core/gui/PageView.cpp, src/core/model/PageHandler.cpp, src/core/model/PageHandler.h, src/core/model/PageListener.cpp, src/core/model/PageListener.h, src/core/undo/ColorUndoAction.h, src/core/undo/FillUndoAction.h, src/core/undo/FontUndoAction.h, src/core/undo/InsertUndoAction.h, src/core/undo/LayerRenameUndoAction.h, src/core/undo/LineStyleUndoAction.h, src/core/undo/MoveUndoAction.h, src/core/undo/RecognizerUndoAction.h, src/core/undo/SizeUndoAction.h, src/core/undo/TextBoxUndoAction.h, src/core/undo/TextUndoAction.h, src/core/view/DebugShowRepaintBounds.h, src/core/view/DocumentView.cpp, src/core/view/DocumentView.h, src/core/view/LayerView.cpp, src/core/view/LayerView.h
This is a code cleanup PR in the View Refactor series :)
There are non-trivial changes in VerticalToolHandler that limit the unnecessary rerenderings (see 4bef970d).
@Technius: I'm sorry I've been asking you a lot of reviews lately, but I think you're the most qualified for the VerticalToolHandler business in this PR. :-)
=> View Refactor 4 - Code cleanup & VerticalToolHandler

.clang-tidy, src/core/gui/dialog/PluginDialog.cpp, src/core/gui/dialog/PluginDialogEntry.cpp, src/core/plugin/Plugin.cpp, src/core/plugin/Plugin.h, src/core/plugin/PluginController.cpp, src/core/plugin/PluginController.h, ui/pluginEntry.glade
=> Add several plugin loading paths

windows-setup/package.sh
=> copy gtk-sourceview shared data

mac-setup/build-app.sh, mac-setup/xournalpp.bundle, src/CMakeLists.txt, src/exe/Xournalpp.cpp, src/exe/osx/setup-env.cpp, src/exe/osx/setup-env.h, src/util/PathUtil.cpp
Cherrypicks the first commit of #4090, so that a working.app bundle is created for the master branch as well.
=> remove macos-launcher and simplify build-app.sh

src/core/control/latex/LatexGenerator.cpp, src/util/include/util/raii/GLibGuards.h
- Fixed memory leak
- Fixed Crash with utf8 paths on windows
=> Minor Bugfixes:

src/core/view/StrokeView.cpp
Fixes a bug where filled highlighter strokes do not have the right resolution when zoomed in.
The bug was introduced by fc17f8555.
=> Fix low resolution filled highlighter stroke bug

src/plugin/luapi_application.h
=> fix applib_getDocumentStructure layer name

src/control/tools/StrokeHandler.cpp
This PR plugs a memory leak happening when the stroke recognizer replaces the stroke.
Esssentially, StrokeHandler::strokeRecognizerDetected clones the recognized stroke (i.e. the result of the recognition process) and adds the clone to the layer. The recognized stroke (not the clone) is then never deleted, and is no longer referenced anywhere once the StrokeRecognizerResult gets deleted.
This PR just removes the clone and directly adds the recognized stroke to the layer (which then owns it).
=> Plug leaking Stroke in StrokeHandler::strokeRecognizerDetected

src/core/control/LatexController.cpp, src/core/control/settings/LatexSettings.h, src/core/control/settings/Settings.cpp, src/core/gui/dialog/LatexSettingsPanel.cpp, ui/latexSettings.glade
Closes #4251. Modeled after the "genCmd" setting key.
Verification:
- Manual testing
=> Allow the default LaTeX text when inserting to be configurable

ui/main.glade
=> Bind Ctrl+Shift+Z to redo

src/core/control/latex/LatexGenerator.cpp, src/core/control/tools/StrokeHandler.cpp, src/core/gui/TextEditor.cpp, src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHelper.cpp, src/core/plugin/luapi_application.h, src/util/Util.cpp, src/util/include/util/Util.h
I had to resolve some conflicts, so please double check @bhennion @rolandlo.
This should be fast-forwarded on to master. Please do not merge through GitHub's UI.
=> Merge changes from release-1.1

src/core/gui/PdfFloatingToolbox.cpp
Fixes #3971.
Previously, `PdfFloatingToolbox::createStrokes` would incorrectly no-op if the page number (of the document) is not equal to the page number of the background PDF that the text selection is over.
This commit changes the fix to instead retrieve the PDF page number of the current document page, and compare that against the PDF page number of the text selection.
=> Fix PDF toolbox stroke actions when PDF page num is not current page

CHANGELOG.md, CMakeLists.txt, debian/changelog, desktop/com.github.xournalpp.xournalpp.appdata.xml, mac-setup/Info.plist, rpm/fedora/xournalpp.spec, src/exe/osx/setup-env.cpp
This merges the 1.1.2 version changes (adjusted for master branch).
=> Merge release 1.1.2 commits

src/core/control/tools/EllipseHandler.cpp
Fixed issues #4318 and #4316 relative to the ellipse drawing.
=> Fix problems when drawing an ellipse

src/core/control/Control.cpp
Fixes a regression caused by #4315.
=> Fix segfault when switching from text to selection tool

src/core/plugin/luapi_application.h
Cherrypicked a6d59bdc2f582dbd08c29f67bae70d1dac364c22 from #3830
=> add Lua plugin API app.openFile

src/core/control/ClipboardHandler.cpp, src/core/control/ClipboardHandler.h, src/core/control/Control.cpp, src/core/control/Control.h, src/core/gui/PageView.cpp, src/core/gui/TextEditor.cpp, src/core/gui/TextEditor.h, src/core/gui/TextEditorWidget.h, src/util/include/util/raii/CStringWrapper.h, src/util/include/util/raii/CairoWrappers.h, src/util/include/util/raii/IdentityFunction.h, src/util/include/util/raii/PangoSPtr.h, src/util/raii/CStringWrapper.cpp
This is the first half of #4271, to ease the reviewing process.
=> First half of #4271

CHANGELOG.md
The changelog update already incorporates the yet unmerged #4420
=> Update changelog for 1.1.3

src/core/gui/PageView.cpp, src/core/gui/TextEditor.cpp, src/core/gui/TextEditor.h, src/core/gui/TextEditorWidget.h
Renamed 
copyToCliboard
to
copyToCli**p**board
=> Fixed typo in method name

src/core/control/Actions.h, src/core/control/Control.cpp, src/core/control/Control.h, src/core/gui/GladeGui.cpp, src/core/gui/GladeGui.h, src/core/gui/GladeSearchpath.cpp, src/core/gui/GladeSearchpath.h, src/core/gui/MainWindow.cpp, src/core/gui/MainWindow.h, src/core/gui/toolbarMenubar/AbstractItem.cpp, src/core/gui/toolbarMenubar/AbstractItem.h, src/core/gui/toolbarMenubar/AbstractToolItem.cpp, src/core/gui/toolbarMenubar/ColorToolItem.cpp, src/core/gui/toolbarMenubar/ColorToolItem.h, src/core/gui/toolbarMenubar/FontButton.cpp, src/core/gui/toolbarMenubar/FontButton.h, src/core/gui/toolbarMenubar/ToolMenuHandler.h, src/core/gui/toolbarMenubar/model/ToolbarData.cpp, src/core/gui/toolbarMenubar/model/ToolbarData.h, src/core/plugin/luapi_application.h, src/util/include/util/raii/CLibrariesSPtr.h
This PR is the first part of an attempt to split #4372 into reviewable PR's.
Here are just preliminary inoccuous changes (unused variables, const-correctness and smart pointers in gui/)
=> Preliminary work to removing GtkMenu 

src/core/control/RecentManager.cpp
Implements #4410.
I only wrote the code, the `"Clear list"` string needs to be translated.
=> Implemented clear function for recent files list

readme/Compile.md, readme/LinuxBuild.md, readme/Releases.md
- Fixes issues with incorrect whitespace
- Fix issue with bad heading
- Add shell command in `Compile.md` so steps are more clear
=> docs: Fix whitespace, heading level issues

src/core/control/Control.cpp, src/core/control/Control.h, src/core/model/GeometryTool.cpp, src/core/model/GeometryTool.h, src/core/model/Setsquare.cpp, src/core/view/SetsquareView.cpp, src/core/view/SetsquareView.h
Preparation for #4443 
The rendering issues when activating or deactivating the setsquare fixed in this PR are fully visible when combined with #4502
=> Fix setsquare activation and deactivation, fix toolRange

src/core/gui/toolbarMenubar/ColorToolItem.cpp, src/core/gui/toolbarMenubar/ColorToolItem.h
`ColorToolItem::freeIcons` was not used -> removed
=> Remove 'ColorToolItem::freeIcons' dead code

src/core/gui/toolbarMenubar/ColorToolItem.cpp
IMHO better to use ostringstream to generate the `getId` string
=> Use ostringstream to generate id string

src/core/control/pagetype/PageTypeMenu.cpp, src/core/gui/toolbarMenubar/ToolPageLayer.cpp
I have run xournalpp with valgrind. Based on the output I have found and fix the following memory leaks.
=> Fix memory leaks

src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
=> Add individual line styles as toolbar items

src/core/control/Control.cpp, src/core/control/Control.h, src/core/control/XournalMain.cpp
This improves const-correctness for:
- Member accessors in `Control.cpp`
- Variables in `XournalMain.cpp`
=> chore: Improve const-correctness

.gitignore
.clangd is a config file 😅
Also I'm not sure what the `Debug` entry is for. It was added in #3326, to me it seems like it was just added _somewhere_, probably unrelated to clangd? @aeghn @Technius
=> Fixup 3971c1a051293f6ef45f68a80ba49b96354062dd

src/core/gui/PageView.cpp
Fixes #4627.
Merging in 24 hours if no objections are raised.
=> Make pdf links popup without pressing Alt

src/core/control/settings/Settings.cpp, src/core/control/settings/Settings.h
Due to RAII there is no need to delete buttons in destructor.
=> Use std::array of unique_ptr for Settting::buttonConfig

src/core/model/Stroke.cpp, src/core/model/Stroke.h
=> Fix bounding box for pressure-sensitive strokes

src/core/view/overlays/VerticalToolView.cpp
=> Fix lifetime of references

src/core/control/jobs/ImageExport.cpp
Fixes #4704 
This is the fix suggested by @bhennion in https://github.com/xournalpp/xournalpp/issues/4704#issuecomment-1461063896. I tested that it works.
Merging in 24 hours if no objections are raised.
=> fix png export for PDF background

src/core/control/tools/StrokeStabilizer.cpp
For a while now, the last point of the StrokeHandler::stroke has carried the pressure value of the last input event.
This change was not repercuted to `StrokeStabilizer::quadraticSplineTo()`.
This tiny PR fixes that.
=> Fix StrokeStabilizer::quadraticSplineTo()'s handling of pressure values

readme/Releases.md
This adds a checklist on the release process to help current and future maintainers.
@xournalpp/core please take a look to see if there's anything missing.
=> Add release checklist to readme/Releases.md

azure-pipelines/clang-format-applied.yml
=> Debug attempt: clang-format test ignores AllowShortBlocksOnASingleLine: Empty option

src/core/control/xojfile/LoadHandler.cpp, src/util/include/util/BasePointerIterator.h, src/util/include/util/CircularBuffer.h, src/util/include/util/DispatchPool.h, src/util/include/util/GListView.h, src/util/include/util/Interval.h, src/util/include/util/LoopUtil.h, src/util/include/util/PairView.h, src/util/include/util/Rectangle.h, src/util/include/util/SmallVector.h, src/util/include/util/TinyVector.h, src/util/include/util/UnionOfIntervals.h, src/util/include/util/safe_casts.h
Merging in 24 hours unless the pipeline fails or someone objects.
=> Apply include-what-you-use to headers in util/ without associated .cpp file

azure-pipelines/continuous-integration.yml, azure-pipelines/create-installers.yml, azure-pipelines/jobs/release_ubuntu.yml, azure-pipelines/release.yml, azure-pipelines/translation.yml
Needed in view of https://github.com/actions/runner-images/issues/6002
=> Drop Ubuntu 18.04, build AppImage on Ubuntu 20.04

src/core/control/Control.cpp, src/core/control/settings/Settings.cpp, src/core/control/settings/Settings.h, src/core/control/settings/SettingsEnums.h, src/core/gui/PagePreviewDecoration.cpp, src/core/gui/PagePreviewDecoration.h, src/core/gui/dialog/SettingsDialog.cpp, src/core/gui/sidebar/AbstractSidebarPage.h, src/core/gui/sidebar/Sidebar.cpp, src/core/gui/sidebar/Sidebar.h, src/core/gui/sidebar/indextree/SidebarIndexPage.cpp, src/core/gui/sidebar/indextree/SidebarIndexPage.h, src/core/gui/sidebar/previews/page/SidebarPreviewPageEntry.cpp, src/core/gui/sidebar/previews/page/SidebarPreviewPageEntry.h, src/core/gui/sidebar/previews/page/SidebarPreviewPages.cpp, src/core/gui/sidebar/previews/page/SidebarPreviewPages.h, ui/settings.glade
Hi, I would like to submit this pull request. 
I have implemented that the page numbers are displayed on the sidebar for the page previews.
This is the first time I'm doing a pull request. I hope that I have done everything right, otherwise please let me know. 
Related issue: (#4624)
=> Issue #4624 add page numbers

src/core/control/tools/EditSelection.cpp, src/core/control/tools/EditSelection.h, src/core/control/tools/EditSelectionContents.cpp, src/core/control/tools/EditSelectionContents.h, src/core/gui/XournalView.cpp
=> Add undo action for selection moved with keyboard

src/core/control/Control.cpp, src/core/control/ToolHandler.cpp, src/core/control/ToolHandler.h
Fixes #4823 (and and issue mentioned in https://github.com/xournalpp/xournalpp/issues/4823#issuecomment-1520073515)
Fixes #4827
=> fix button activation of fill tool and line style

src/core/control/settings/Settings.cpp, src/core/control/settings/Settings.h, src/core/gui/dialog/SettingsDialog.cpp, src/core/model/Document.cpp, src/util/SaveNameUtils.cpp, src/util/include/util/SaveNameUtils.h, ui/settings.glade
=> Add GUI for setting default Pdf export name

desktop/com.github.xournalpp.xournalpp.desktop, src/core/control/XournalMain.cpp
=> Fix missing titlebar icon on wayland.

mac-setup/xournalpp.modules
All modules have been updated. The macOS Gtk blob already uses the new modules.
=> Update macOS modules

CHANGELOG.md
Had lots of time on a long international flight, so I decided to write up the changelog. Looking back, there's a lot of changes that have been added over the past year and a half since 1.1.0's release.
@xournalpp/core I'm sure there are obvious mistakes and omissions in this list, so please take a look and point out any problems.
Last checked against: `d3cd981aa94843ea6d32f532659970eaa1568988`
=> Update changelog in preparation for 1.2.0 release

src/core/control/ToolEnums.cpp, src/core/control/ToolEnums.h, src/core/control/tools/Selection.cpp, src/core/control/tools/Selection.h, src/core/gui/PageView.cpp, src/core/gui/PageViewFindObjectHelper.h, src/core/gui/inputdevices/AbstractInputHandler.cpp, src/core/gui/inputdevices/AbstractInputHandler.h, src/core/gui/inputdevices/PenInputHandler.cpp, src/core/gui/inputdevices/PenInputHandler.h
Hi,
I modified the selection tools to allow for aggregate selections when Shift is pressed (within the same layer). 
Fixes #1838.
=> Issue #1838 Group selections

src/core/plugin/luapi_application.h
As already written in https://github.com/xournalpp/xournalpp/pull/4652#discussion_r1133074071 I started refactoring the complete `luapi_application.h` regarding the use of the lua-stack. The main things I found were
1. function returns `!= 0` while effectively no value is supposed to be returned (at least I think so) (for example [`applib_scaleTextElements`](https://github.com/atticus-sullivan/xournalpp/blob/949edbe11a9f58e71f14e2735de5ca6a541e865d/src/core/plugin/luapi_application.h#L1896), [`applib_setBackgroundName`](https://github.com/atticus-sullivan/xournalpp/blob/949edbe11a9f58e71f14e2735de5ca6a541e865d/src/core/plugin/luapi_application.h#L1851), [`applib_uiActionSelected`](https://github.com/atticus-sullivan/xournalpp/blob/949edbe11a9f58e71f14e2735de5ca6a541e865d/src/core/plugin/lu …
=> Lua api refactor stack

src/core/gui/toolbarMenubar/model/ColorPalette.cpp
- fixes #4994 
- preventing empty Palettes, in case of reading errors.
`auto Palette::getColorAt(size_t i) const` should never fail, since the `namedColors` attribute must be non-empty. This could happen, if a path was existent, but not readable (permission, directory, reading error). Enabling exceptions for the stream fixes that.
=> Added exeption handling to Palette::load

src/core/control/CrashHandlerUnix.h, src/core/control/XournalMain.cpp
Limits the crashlogs reported by the popup at startup to those issued during the last week.
=> Add age filter on crash logs reported at startup

README.md, debian/control, desktop/com.github.xournalpp.xournalpp.appdata.xml, package_description
The additions to the package description are the same for the 4 files. They should always remain synchronized.
=> Update package description

CHANGELOG.md
@xournalpp/core Please check!
For the package description update (which we forgot for v1.2.0) I will open a PR.
=> Update changelog in preparation for 1.2.1 release

CHANGELOG.md, cmake/include/GitRepo.cmake
=> Hardcode bugreport link address and update changelog

src/core/control/Control.cpp, src/core/control/jobs/BlockingJob.cpp, src/core/control/jobs/BlockingJob.h, src/core/control/jobs/Job.cpp, src/core/control/jobs/Scheduler.cpp, src/core/control/jobs/Scheduler.h, src/core/control/tools/EditSelection.cpp, src/core/control/tools/EditSelectionContents.cpp, src/core/control/tools/EditSelectionContents.h, src/core/control/tools/TextEditor.cpp, src/core/control/zoom/ZoomControl.cpp, src/core/gui/MainWindow.cpp, src/core/gui/XournalView.cpp, src/core/gui/XournalView.h, src/core/gui/inputdevices/HandRecognition.cpp, src/core/gui/inputdevices/InputContext.cpp, src/core/gui/sidebar/indextree/SidebarIndexPage.cpp, src/core/gui/sidebar/indextree/SidebarIndexPage.h, src/core/gui/sidebar/previews/base/SidebarPreviewBase.cpp, src/core/gui/widgets/SpinPageAdapter.cpp, src/core/model/Document.cpp, src/core/view/Mask.cpp, src/util/Util.cpp, src/util/include/util/Util.h, src/util/include/util/glib_casts.h
Many callbacks had the return value `bool`, which is a c++ only type, but the C API from gtk/gdk/glib expected `gboolean`.
The reinterpret_cast to the corresponding functions is undefined behavior.
=> Fixed UB due to incompatible callbacks

src/core/gui/toolbarMenubar/ToolButton.cpp
Fix #5145 
Merging in 24 hours unless an objection is raised.
=> Fix orientation of new page item in vertical toolbars

src/core/gui/MainWindow.cpp
=> Fix empty toolbars being shown

plugins/MigrateFontSizes/main.lua
=> Fix MigrateFontSizes plugin

src/core/gui/dialog/SettingsDialog.cpp, src/core/gui/dialog/SettingsDialog.h
Fix #5182 
Merging as soon as the CI passes.
=> Fix SegFault when assigning tools to buttons in SettingsDialog

src/core/gui/ToolitemDragDrop.cpp, src/core/gui/ToolitemDragDrop.h, src/core/gui/dialog/toolbarCustomize/ToolItemDragCurrentData.cpp, src/core/gui/dialog/toolbarCustomize/ToolItemDragCurrentData.h, src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp, src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp, src/core/gui/toolbarMenubar/model/ToolbarModel.cpp
Trying to figure out what could go wrong in #5199, I found a couple of memleaks.
Merging once the CI passes.
=> Fix some memleaks in toolbar customization

src/core/control/XournalMain.cpp
=> Add info on how to prevent bugreport popup

CHANGELOG.md, CMakeLists.txt, debian/changelog, desktop/com.github.xournalpp.xournalpp.appdata.xml, mac-setup/Info.plist, rpm/fedora/xournalpp.spec
Draft PR. Do not merge. This will be fast forwarded onto the release branch.
@xournalpp/core Please have a look
=> Release 1.2.2

src/core/control/xojfile/SaveHandler.cpp
=> Fix redundant negative pressure.

src/core/control/Control.cpp, src/core/control/Control.h, src/core/control/XournalMain.cpp, src/core/control/actions/ActionProperties.h
=> Add CLI option to open PDF in attach mode

src/core/gui/XournalppCursor.cpp, src/core/gui/XournalppCursor.h
Just implemented the proposed solution in #4807, since there was no activity for a while.
Credit goes to @jen-kosek and @rolandlo.
Fixes #3090, #4807.
=> Fix updating of the cursor size

src/core/plugin/luapi_application.h, src/util/Color.cpp
=> Fix color handling in Lua API

src/core/control/jobs/BaseExportJob.cpp, src/core/gui/dialog/ExportDialog.cpp, ui/mainmenubar.xml, ui/settings.glade
Most importantly this fixes a regression from #4763 in the export dialog, which made it impossible to set the quality parameter for png-export.
=> Fix UI stuff

resources/default_template.tex, resources/legacy_template.tex
This change was proposed in #3293.  Based on release-1.2.
=> Fix long text being truncated in LaTeX tool

src/core/control/XournalMain.cpp
=> Add CLI-option to save out.xopp file for in.pdf

readme/Compile.md
=> Fix typo in Compile.md

debian/rules, resources/default_template.tex, resources/legacy_template.tex, src/config.h.in, src/core/control/Control.cpp, src/core/control/Control.h, src/core/control/CrashHandlerUnix.h, src/core/control/ToolHandler.cpp, src/core/control/ToolHandler.h, src/core/control/jobs/AutosaveJob.cpp, src/core/control/latex/LatexGenerator.cpp, src/core/control/settings/PageTemplateSettings.cpp, src/core/control/settings/Settings.cpp, src/core/control/tools/PdfElemSelection.cpp, src/core/control/xojfile/SaveHandler.cpp, src/core/control/xojfile/XojExportHandler.cpp, src/core/gui/MainWindow.cpp, src/core/gui/MainWindow.h, src/core/gui/PageView.cpp, src/core/gui/inputdevices/PenInputHandler.cpp, src/core/view/overlays/SearchResultView.cpp, src/core/view/overlays/StrokeToolView.cpp, src/core/view/overlays/VerticalToolView.cpp, src/util/CMakeLists.txt, src/util/Color.cpp, src/util/OutputStream.cpp, src/util/Stacktrace.cpp, src/util/include/util/OutputStream.h, src/util/include/util/safe_casts.h
@xournalpp/core Please check if I didn't mess things up in the merge commit. There were no real difficulty resolving the conflicts so it should be ok.
=> Merge release branch into master

src/core/plugin/luapi_application.h
Since https://github.com/xournalpp/xournalpp/pull/2379 has been merged, xournalpp uses a color-palette for the colors in the toolbar. It would be nice for functions like `changeToolColor` to use already configured colors from that palette.
This PR adds a function to get an RGB color-value which then can be used in functions like `changeToolColor`.
Since maybe we'd want to extend the api for this function, I chose to use a table, even if currently there is only one argument. Maybe in the future we'd also like to allow querying for names and then an api like `app.getPaletteColor(nil, "name")` (or interpreting the argument depending on the type) would be rather ugly.
Using negative indices result in a wrap around, but I'm not sure whether we should disallow values out of bounds of the …
=> [luaAPI] add getPaletteColor function to query the current palette

azure-pipelines/steps/install_deps_ubuntu.yml
=> Add gtk3-immodules for generating AppImages.

src/core/plugin/luapi_application.h
Really rough draft for this so we have a place for discussion (like discussed [here](https://github.com/xournalpp/xournalpp/pull/5029#discussion_r1295293761).
Open questions:
TODO:
=> luaAPI refactoring: get elements from selection/layer helper function

CHANGELOG.md
Here is the changelog for version 1.2.3. I suggest to follow up with the 1.2.3 release soon.
=> Update changelog for 1.2.3

CHANGELOG.md, CMakeLists.txt, debian/changelog, desktop/com.github.xournalpp.xournalpp.appdata.xml, mac-setup/Info.plist, rpm/fedora/xournalpp.spec
Draft PR. Do not merge. This will be fast forwarded onto the release branch.
@xournalpp/core Please have a look
=> Release 1.2.3

CHANGELOG.md, CMakeLists.txt, azure-pipelines/steps/install_deps_ubuntu.yml, debian/changelog, mac-setup/Info.plist, resources-templates/com.github.xournalpp.xournalpp.appdata.xml.in, src/core/control/Control.cpp, src/core/gui/menus/menubar/ToolbarSelectionSubmenu.cpp, src/core/pdf/base/XojCairoPdfExport.cpp, src/core/pdf/base/XojCairoPdfExport.h
@xournalpp/core Please take a look.
This must be fast-forwarded on to master branch.
Note to self: 
```term
git checkout master
git merge merge-release-1.2.3 --ff-only
git push upstream master
```
=> Merge release 1.2.3

src/core/control/latex/LatexGenerator.cpp, src/util/include/util/raii/GLibGuards.h
- GLibGuard only cleared the first set value.
- similar to c++23 out_ptr
=> Fixed Memory leaks for some GLibGuards, added out_ptr

mac-setup/Info.plist
Fixes #5635 
The solution is taken from https://github.com/sdasda7777/lmms/commit/95c4862d7f12685e7a97a59572101b8d4541ba98
=> Fix MacOS titlebar color

azure-pipelines/create-installers.yml, azure-pipelines/release.yml
=> Add Ubuntu 24.04 to builds

CHANGELOG.md
Please take a look @bhennion @Febbe
=> Update changelog for 1.2.4

CHANGELOG.md, CMakeLists.txt, debian/changelog, desktop/com.github.xournalpp.xournalpp.appdata.xml, mac-setup/Info.plist, rpm/fedora/xournalpp.spec
Draft PR. Do not merge. This will be pushed onto the release branch from CLI.
@xournalpp/core Please have a look
=> Release 1.2.4

src/core/control/Control.cpp, src/core/gui/inputdevices/CompassInputHandler.cpp, src/core/gui/inputdevices/SetsquareInputHandler.cpp, src/core/model/Compass.cpp, src/core/model/Compass.h, src/core/model/Setsquare.cpp, src/core/model/Setsquare.h, src/core/view/CompassView.h, src/core/view/SetsquareView.h
=> Make geometry tools appear in the middle of the visible part of the current page

src/core/plugin/luapi_application.h, src/core/undo/InsertUndoAction.cpp
=> Fix undo and redo when adding strokes from a plugin

mac-setup/jhbuild-version.lock, mac-setup/xournalpp.bundle, src/core/control/Control.cpp, src/core/control/Control.h, src/core/control/actions/ActionProperties.h, src/core/enums/Action.enum.h, src/core/enums/generated/Action.NameMap.generated.h, ui/mainmenubar.xml, windows-setup/package.sh
As suggested in https://github.com/xournalpp/xournalpp/issues/6189#issuecomment-2578126710
=> Add gtk3-demo on MacOS and Windows

mac-setup/CI_jhbuild.sh, mac-setup/cmake-find.patch, mac-setup/gtk-osx.patch, mac-setup/xournalpp.modules
Fixes #6167 . It will have to be checked if it builds and works.
=> Fix poppler's jpeg loading on MacOS

src/core/control/CompassController.cpp
=> Fix compass outline drawing

CHANGELOG.md, CMakeLists.txt, debian/changelog, desktop/com.github.xournalpp.xournalpp.appdata.xml, mac-setup/Info.plist, rpm/fedora/xournalpp.spec
@xournalpp/core Please take a look to see if everything is fine. I will test the PDF export on Windows to make sure the Cairo patch works.
MUST NOT BE MERGED VIA GITHUB
=> Release 1.2.6

plugins/ColorCycle/main.lua, plugins/Example/main.lua, plugins/Export/main.lua, plugins/LayerActions/main.lua, plugins/MigrateFontSizes/main.lua, plugins/QuickScreenshot/main.lua, plugins/ToggleGrid/togglegrid.lua
Trivial fix to palpate project for signs of life and potentially proposing more ;)
=> Fix intialize typo
